### ISSUE TITLE
Unicode email address

### ISSUE THREAD

**Issue by cosminstefanxp** [sendgrid/sendgrid-python#100]
Hi,

I'm trying to send some emails to addresses containing unicode characters. Example:
`KYÖSTI@example.org`. However, when I'm trying to send the email I'm getting:

> SendGridClientError: (400, '{"message": "error", "errors": ["Invalid email address KY\\u00d6STI@example.org"]}')

As you can see, for some reason it's double encoding the email address somewhere so `\u00d6` becomes `\\u00d6`

Any suggestions? 

I've tried making it work in a very large number of ways (various encodings, using `parse_and_add()` directly etc.), but to no success so far.

**Comment by elbuo8** [comment]
@cosminstefanxp which version of python?

**Comment by cosminstefanxp** [comment]
Python 2.7

Cosmin

**Comment by kunal732** [comment]
@cosminstefanxp Just wanted to let you know we are looking into it, we have just been busy working on a new version of the api.

**Comment by enkitosh** [comment]
Hi is there any update on this. I'm getting this as well, for now I return a custom error when this happens but this rules out any email containing unicode characters.

**Comment by tushdante** [comment]
Hey @elbuo8 I'm having some trouble trying to fix this. I'd appreciate your help, so feel free to reach out when you see this. Thanks!

**Comment by elbuo8** [comment]
I no longer have write access to this repo.

But based on what I can see from looking at the code and what you mention, this is probably the culprit: https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/message.py#L63

Is the email contained in a `str` or a `unicode` type variable? Since it seems you already have performed the encoding, try casting it to `str` before calling the addition method.

**Comment by thinkingserious** [comment]
@cosminstefanxp Unfortunately, we do not currently support this functionality. 

We have added this to our backlog and every voice/vote counts towards prioritization. If you would like to see this implemented, I encourage you to let your voice be heard [here](https://community.sendgrid.com/sendgrid).

Thanks for bringing this issue to our attention.

**Comment by RahavLussato** [comment]
i can't find anything related to that at https://community.sendgrid.com/sendgrid,
where i can vote for that ?

**Comment by thinkingserious** [comment]
In that case, please submit a new idea. Thanks!
