### ISSUE TITLE
Does it support with Python 3.9?

### ISSUE THREAD

**Issue by XiaoYiyichonga** [sendgrid/sendgrid-python#1000]
Hello Team,
Now, the sendgrid api cannot be used with python 3.9.
If it could be improved which can be used to applied to python 3.9 it would add more benifits.
Could you kindly consider to add it?
Best Regards
Face of Sendgrids

**Comment by JenniferMah** [comment]
Hi @XiaoYiyichonga!
Please track the progress on adding support for Python 3.9 in issue #965. Adding a +1 to the issue summary in issue #965 will help it move up in our backlog. This github issue will be closed out as a duplicate.
