### ISSUE TITLE
"TypeError: Object of type Content is not JSON serializable"

### ISSUE THREAD

**Issue by john0017** [sendgrid/sendgrid-python#1004]
`sg = sendgrid.SendGridAPIClient(api_key=API_KEY)

from_email = Email("xzy@abc.com")
to_email = To("fgh@abc.com")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "hi")

attachment = Attachment()
attachment.file_content = FileContent(csv)
attachment.file_type = FileType('text/csv')
attachment.file_name = FileName('test.csv')
attachment.disposition = Disposition('attachment')

mail = Mail(from_email, to_email, subject, content)
mail.attachment = attachment

response = sg.client.mail.send.post(request_body=mail.get())
`print(response.status_code)``

The csv above is a pandas df converted to csv and then encoded.

The code works fine on jupyter notebook, however on VScode/ Pycharm i get the error "TypeError: Object of type Content is not JSON serializable"

**Comment by john0017** [comment]
> Can you post the stack trace of the exception?

Hi, 

Any thoughts on this?

**Comment by eshanholtz** [comment]
How is the variable `csv` being defined?

**Comment by john0017** [comment]
> How is the variable `csv` being defined?

Thank you for your response. The code works fine on jupiter notebook but not on Pycharm or VS code. 

The csv file is defined as -

`with open('filename.csv', 'rb') as f:
    data = f.read()
    csv = base64.b64encode(data).decode()`

**Comment by eshanholtz** [comment]
Can you please print the output of printing the request body and post it here? Make sure to redact sensitive information. You can follow our [troubleshooting guide](https://github.com/sendgrid/sendgrid-python/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) for guidance on how to properly print the request body.

**Comment by john0017** [comment]
> Can you please print the output of printing the request body and post it here? Make sure to redact sensitive information. You can follow our [troubleshooting guide](https://github.com/sendgrid/sendgrid-python/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) for guidance on how to properly print the request body.

hi, any update?

**Comment by JenniferMah** [comment]
Hi @john0017,
Can you update to the latest version of the sendgrid-python library v6.8.1 and try re-running your code to see if you still see the JSON serializable error?

**Comment by john0017** [comment]
> Hi @john0017,
> Can you update to the latest version of the sendgrid-python library v6.8.1 and try re-running your code to see if you still see the JSON serializable error?

Thank you for your response. However, that did not work either. I updated the script by not using the Mail helper class and that seems to work.
