### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support

### ISSUE THREAD

**Issue by rabcau** [sendgrid/sendgrid-python#1010]
Hello! I registered my new SendGrid account today and I had an authorization issue. I cannot contact Support since when I click on **Support** > **Trouble Logging In**? > **I am having a different login issue**  I'm being redirected to the page that says:

![image](https://user-images.githubusercontent.com/64354988/133785170-e86eb556-e6f2-4dc8-8cf3-b32676e86a22.png)

Also I tried to contact dx@sendgrid.com and received the response immediately - "Thank you for your inquiry. This email address is no longer monitored. If you need help with a SendGrid product, please head to https://support.sendgrid.com/ to open a support ticket."
Of course I already read a lot of closed issues with same trouble but almost every time users was sent to Support.
 
Vicious circle. Help me please.
My email: romanromanian@gmail.com

**Comment by shwetha-manvinkurke** [comment]
@rabcau I opened up a ticket with support for you. Closing this issue as it's something we can't help you with.

**Comment by rabcau** [comment]
> @rabcau I opened up a ticket with support for you. Closing this issue as it's something we can't help you with.

thank you, hope to get help soon

**Comment by Kamalakannan-Ramaswamy** [comment]
I had created the send grid account but I'm not able to login,  It showing "**You are not authorized to access SendGrid, please contact Support."**. I raise the ticket I'm getting mail only issues not yet solve how to connect to sendgrid support team.
