### ISSUE TITLE
High Severity Security Issue in Dependency

### ISSUE THREAD

**Issue by vahedq** [sendgrid/sendgrid-python#1024]
### Issue Summary
We use sendgrid python sdk, and recently noticed that one of the dependencies have security issue and need to update to 
```
Remediation
Upgrade starkbank-ecdsa to version 2.0.1 or later. For example:

starkbank-ecdsa>=2.0.1
```

However sendgrid depends on
```
starkbank-ecdsa>=1.0.0,<2.0.0
```

Given SOC2 guidelines, we won't be able to use sendgrid if this update isn't applied. Please let us know how to proceed.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-python version: 
* python version:

**Comment by mikeckennedy** [comment]
See also #1023

**Comment by JenniferMah** [comment]
Closing as a duplicate. Please track progress on this update in issue #1023.
