### ISSUE TITLE
Bad link to Event Webhook documentation

### ISSUE THREAD

**Issue by padamson** [sendgrid/sendgrid-python#1026]
The [link to the Event Webhook](https://github.com/sendgrid/sendgrid-python/blob/a3cbe32bd270db4fc2d81b92f73baf6ddab113a7/use_cases/email_stats.md?plain=1#L5) documentation in the API is broken.

**Comment by JenniferMah** [comment]
Hi @padamson! Thanks for submitting a Github issue. I've linked to the correct documentation for [Event Webhooks](https://github.com/sendgrid/sendgrid-python/blob/main/use_cases/email_stats.md) in the email stats read.me.
