### ISSUE TITLE
Use random characters for API keys

### ISSUE THREAD

**Issue by hashbackup** [sendgrid/sendgrid-python#1033]
Issue: Sendgrid API keys have a known prefix, making it easy to find them in executables and core dumps.

Suggestion: use a string of random characters for API keys, with no pattern, ie, don't use XXXX-YYYY-ZZZZ, SG.S-blah, etc.

**Comment by JenniferMah** [comment]
Hi @hashbackup! In order to properly help with this request, please file a [support ticket](https://support.sendgrid.com/hc/en-us).
