### ISSUE TITLE
Attachment not going with sendgrid python client

### ISSUE THREAD

**Issue by vi3k6i5** [sendgrid/sendgrid-python#107]
Attachment not going from Sendgrid python client Version : sendgrid (1.4.0)

OS: 
Ubuntu 14.04, Ubuntu 15.04

How to reproduce:

import sendgrid
recipients = ['<to@mail.com>']
sg = sendgrid.SendGridClient('user_name', 'passowrd')
message = sendgrid.Mail()
message.add_to(recipients)
message.set_subject("Hi ")
message.set_html("how you doing?")
message.set_from('from@mail.com')
message.add_attachment('file.txt', '/tmp/file.txt')
status, msg = sg.send(message)

But parallel code is working with ruby client:

require 'sendgrid-ruby'

client = SendGrid::Client.new(api_user: 'user_name', api_key: 'passowrd')

mail = SendGrid::Mail.new do |m|
  m.to = 'to@mail.com'
  m.from = 'from@mail.com'
  m.subject = 'Hi'
  m.text = 'how you doing?'
end

mail.add_attachment('/tmp/file.txt', 'file.txt')

puts client.send(mail) 

While both the mails get delivered to the inbox the 2nd one comes with an attachment and the 1st one comes without an attachment. Please fix the issue..

**Comment by vi3k6i5** [comment]
The code is working now. i guess it was not a client error rather a back-end issue.

**Comment by tushdante** [comment]
Hey @vi3k6i5 thanks for sending in the issue. I've tried to replicate your problem but can't seem to on my end. I'm closing out this issue for now, but if you see this happening feel free to open this up again, and mention the details.
