### ISSUE TITLE
Allow setting Friendly Name for the Reply-To header

### ISSUE THREAD

**Issue by tgwizard** [sendgrid/sendgrid-python#110]
Hi,

It would be great if it was possible to specify Reply-To email addresses of the form

```
Buffy Summers <buffy123@example.com>
```

Currently it's only possible to set reply-to to the `buffy123@example.com` value. sendgrid-python allows setting both the name and the email for the `To` and `From` fields though.

From my reading of the API (https://sendgrid.com/docs/API_Reference/Web_API/mail.html) it also seems that the API would need to be updated to allow a `replytoname` field.

Somewhat related to this: It seems the API allows Friendly Names for both cc and bcc, but not the python library.

What do you think?

**Comment by tgwizard** [comment]
Has there been any progress on this issue?

**Comment by mbernier** [comment]
We are actively working on this one internally, along with a couple other tickets. You should see a response from @tushdante or @thinkingserious very soon.

Thanks for following up!

**Comment by tushdante** [comment]
This issue has been fixed in sendgrid/sendgrid-python#122
