### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by kengruven** [sendgrid/sendgrid-python#116]
README.rst says:

    To configure API keys, visit https://app.sendgrid.com/settings/api_keys.

That link just redirects back to https://sendgrid.com now.

**Comment by kunal732** [comment]
Can you check if you're logged in before accessing that link.

**Comment by kengruven** [comment]
Oh, I didn't realize it was a settings page.  Yes, it works if I'm logged in.

I would have expected it to ask me to log in, and then take me to that page.  I've reported it to sendgrid.com.

BTW, it says "API Key is the preferred method. API Keys are in beta."  Do you know if this is still true?  It seems odd that the preferred method is a beta system.

thanks!
