### ISSUE TITLE
Substitutions with template engine

### ISSUE THREAD

**Issue by SchubmannM** [sendgrid/sendgrid-python#117]
When adding multiple add_to addresses or having add_to and add_cc addresses, the substitutions only happen in the first mail that is being sent out, not to the rest of them. 

            message.add_to(['email1', 'email2])
            message.add_cc('email3')           
            message.add_substitution('%carehome_name%', carehome_name)
            message.add_substitution('%deadline%', deadline)
            message.add_substitution('%next_stage_date%', next_stage_date.ctime())

Only email1 receives the correct substitutions, email2 and email3 have an empty string instead of the variables.

**Comment by thinkingserious** [comment]
Thanks for reporting this bug, I have verified it and am debugging.

**Comment by elbuo8** [comment]
For `substitutions` you recipients need to be added to the `smtpapi` `to` field.

`message.smtpapi.add_to('email1')`

**Comment by thinkingserious** [comment]
Thanks for checking in @elbuo8 :)

I tried that and I still get the same error: https://github.com/sendgrid/sendgrid-python/tree/issue-177-substitutions

Only the first email correctly gets the substitutions, the rest are blank.

Please see example_v2_test.py

**Comment by SchubmannM** [comment]
It's not that big of an issue, as running all add_substitution in a loop (number of times = number of recipients) fixes the problem. Was still a bit annoying though :)

**Comment by thinkingserious** [comment]
Thanks for the update @SchubmannM, glad you solved it!

As part of [updating our libraries with the new v3 endpoints](https://github.com/sendgrid/sendgrid-python#announcements), I will be writing a new class to access this functionality and I'll do my best to make it intuitive.
