### ISSUE TITLE
problem sending subject/body with non-ascii characters

### ISSUE THREAD

**Issue by ricpdx** [sendgrid/sendgrid-python#12]
When I send an email with non-ascii characters in the subject or body, these appear as question marks when the email arrives. Perhaps this is due to me sending the email incorrectly, or perhaps this is a core sendgrid issue more than a sendgrid-python issue, but I have not been able to sort it out. I have tried setting the encoding of my Python script (via the Python "magic comment"), but that doesn't help.

Here is a simple script that shows what I am talking about:
# 

import sendgrid 
s = sendgrid.Sendgrid('username', 'password', secure=True) 
message = sendgrid.Message('donotreply@somewhere.net', u'Que día más bueno hace', u'Que día más bueno hace')
message.add_to('someone@somewhere.net') 
s.web.send(message) 
# 

I have also tried these two versions of the sendgrid.Message call:

message = sendgrid.Message('donotreply@somewhere.net', 'Que día más bueno hace', 'Que día más bueno hace')
message = sendgrid.Message('donotreply@somewhere.net', u'Que d\u00EDa m\u00E1s bueno hace', html=u'Que d\u00EDa m\u00E1s bueno hace') 

In all three cases, the emails come through with question marks where the non-ascii characters are.

I also tried adding this filter, but it did not help:

message.add_header("Content-Type", "text/html charset=utf-8") 

Am I making an obvious mistake? Thanks.

**Comment by carlosds730** [comment]
I tried this and it doesn't work

**Comment by thinkingserious** [comment]
Hello @carlosds730,

Do you mind opening a new ticket and proving the sample code so we can try to reproduce and fix?

Thanks!
