### ISSUE TITLE
Python 3.3/3.4/3.5 support

### ISSUE THREAD

**Issue by kengruven** [sendgrid/sendgrid-python#121]
In b17fb6da8, Python 3.3/3.4 were removed from .travis.yml:

    "removing python 3.3 and 3.4 due to issue with the test failing; will investigate in another issue"

but I didn't see any new issue opened for this yet.

(I'm including Python 3.5 here because it's 2 days away from release, and I assume it has the same issue here as 3.3/3.4, but I haven't confirmed that.)

**Comment by mbernier** [comment]
We are actively working on this issue right now internally. You are right that we should have communicated this in an issue, that's my fault. We jumped right on it and didn't look back. We'll keep this issue running while @tushdante completes the work he's doing for this issue.

**Comment by thinkingserious** [comment]
Fixed with https://github.com/sendgrid/sendgrid-python/pull/130

Thanks!
