### ISSUE TITLE
Poor documentation + smtpapi

### ISSUE THREAD

**Issue by paulocheque** [sendgrid/sendgrid-python#139]
Could you guys write a simple example of using the `sendgrid-python` with the `smtpapi` library?

I am keep receiving `JSON in headers could not be parsed` and `Invalid SMTPAPI header` errors.

The README file has many lines, but I suggest to change the README to only simples 3 examples:
1) send a simple email with all basic properties (this example is ok)
2) example of sending an e-mail with a Sendgrid template with variables
3) example of sending an e-mail using the smtpapi library

**Comment by paulocheque** [comment]
Other complains: https://github.com/sendgrid/sendgrid-python/issues/80

Stackoverflow has many questions about the documentation too.

**Comment by mbernier** [comment]
@paulocheque yes, we will do this and let you know when it's done. Thanks for the suggestion and apologies for the trouble!

**Comment by thinkingserious** [comment]
@paulocheque Thanks for your suggestions!

I have updated the README here: https://github.com/sendgrid/sendgrid-python/tree/139-smtpapi-doc-update

Also, I've updated the examples: https://github.com/sendgrid/sendgrid-python/blob/139-smtpapi-doc-update/example_v2_test.py

Could you please take a look and offer additional feedback? Thanks!

With regards to your particular error, could you please provide some sample code? Thanks!

**Comment by thinkingserious** [comment]
@paulocheque just checking in

**Comment by paulocheque** [comment]
I was able to use the Sendgrid templates.

About the examples, I did not understand the `Template Engine Example` https://github.com/sendgrid/sendgrid-python/blob/139-smtpapi-doc-update/example_v2_test.py

Since you have `message.add_filter('templates', 'template_id', 'TEMPLATE-ALPHA-NUMERIC-ID')
`, why do you need `set_subject` and `set_text/set_html`?

**Comment by thinkingserious** [comment]
Thanks @paulocheque, that was valuable feedback. I have updated the example to clarify. Could you please take another look? Thanks!

**Comment by paulocheque** [comment]
Great!
