### ISSUE TITLE
Mail uses old-style class again

### ISSUE THREAD

**Issue by kengruven** [sendgrid/sendgrid-python#144]
This was fixed by PR #106 for bug #103.  Then it was reverted by 79cc7db (along with lots of other changes) with the comment "Fixing the tests".

**Comment by thinkingserious** [comment]
Good catch, thanks! I'll get that fixed ASAP.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-python/commit/338fa0d3f4468ea5d4adfeafc926a46c96bbe68e
