### ISSUE TITLE
Don't hardcode the timeout value

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#145]
https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/sendgrid.py#L111

**Comment by tgehrs** [comment]
Will this be changed to be no longer hardcoded? This seems to be the root of a timeout error I am getting after ten seconds when trying to attach a larger file:
```408 The write operation timed out```

**Comment by thinkingserious** [comment]
@tgehrs,

Yes, but I'm not sure on the timeline just yet.

**Comment by tgehrs** [comment]
@thinkingserious, thanks for the response. just added pull request #157 with a solution for this issue
