### ISSUE TITLE
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

### ISSUE THREAD

**Issue by lekksi** [sendgrid/sendgrid-python#150]
Hi,
we tried using sendgrid-python for contact db updates through WEB API v3 but we get the error below. 

On line 65 in `SendGridAPIClient._build_request` method the `data` variable is serialized to JSON using `json.dumps` and then given `urllib_request.urlopen` as a parameter. The problem seems to be that the return type for [dumps](https://docs.python.org/3.4/library/json.html#json.dumps) is `str` but [urlopen](https://docs.python.org/3.4/library/urllib.request.html#urllib.request.urlopen) expects `bytes` or an iterable of bytes.

Noticed this with sendgrid-python version 1.5.14, but the lines seem to be unmodified in the latest 1.5.17.
Our python version is 3.4.2.

    File ".../python3.4/site-packages/sendgrid/client.py", line 87, in post
    response, body = self._build_request(url, True, 'POST', data)
    File ".../python3.4/site-packages/sendgrid/client.py", line 65, in _build_request
    response = urllib_request.urlopen(req, json.dumps(data))
    File "/usr/local/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
    File "/usr/local/lib/python3.4/urllib/request.py", line 453, in open
    req = meth(req)
    File "/usr/local/lib/python3.4/urllib/request.py", line 1104, in do_request_
    raise TypeError(msg)
    TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

**Comment by thinkingserious** [comment]
Hi @lekksi,

We have not added support for the contact db endpoint yet. Could you provide example code?

**Comment by lekksi** [comment]
@thinkingserious Yep, we subclassed `SendGridAPIClient` and added that support ourselves using the same pattern for defining the API as the ones already provided by sendgrid-python. We call the `self.client.post(self, data)` the exact same way as i.e. the `ASMSuppressions` API does. The cause of the error can be seen directly from the code, though, or are we missing something? I haven't tested this with python 2.x, only 3.4, so cannot confirm whether it's a python version issue.

Also, the `ASMSuppressions` gives the same error with the following simple example:

    client = SendGridAPIClient("SENDGRID_API_KEY", raise_errors=True)
    client.asm_global_suppressions.post(["foo@example.com"])

Here's our quick implementation for the Lists:

    class Lists(object):
        def __init__(self, client, **opts):
            """
            Constructs SendGrid Marketing Lists API
    
            https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/api.html
            """
            self._name = None
            self._base_endpoint = "/v3/contactdb/lists"
            self._endpoint = "/v3/contactdb/lists"
            self._client = client
    
        @property
        def base_endpoint(self):
            return self._base_endpoint
    
        @property
        def endpoint(self):
            endpoint = self._endpoint
            return endpoint
    
        @endpoint.setter
        def endpoint(self, value):
            self._endpoint = value
    
        @property
        def client(self):
            """
            @rtype: SendGridAPIClient
            """
            return self._client
    
        def get_all(self):
            return self.client.get(self)
    
        def create(self, name):
            """
            @type name: str
            """
            data = dict(name=name)
    
            return self.client.post(self, data)
    
        def add_recipients_to_list(self, list_id, recipients):
            """
            @type list_id: int
            @type recipients: list of str
            """
    
            self._endpoint = self._base_endpoint + '/' + str(list_id) + '/recipients'
    
            # Generate SendGrid b64 recipient ids
            create_sendgrid_id = lambda email: base64.b64encode(email.encode()).decode()
            data = [create_sendgrid_id(email) for email in recipients]
    
            return self.client.post(self, data)
    
        def delete(self, list_id):
            """
            @type list_id: int
            """
            self._endpoint = self._base_endpoint + '/' + str(list_id)
    
            return self.client.delete(self)

**Comment by thinkingserious** [comment]
Awesome, thanks! This will help us push out a fix as soon as we can.

**Comment by thinkingserious** [comment]
v2.0.0 of our library should fix this issue. I just successfully tested with this code: 

```python

import sendgrid
import os

path = os.path.abspath(os.path.dirname(__file__))
sg = sendgrid.SendGridAPIClient(path=path)

# We have to treat "global" special, because it's a Python reserved word
response = sg.client.asm.suppressions._('global')._('test1+v2@example.com').get()
print(response.status_code)
print(response.response_body)

response = sg.client.asm.suppressions._('global')._('test2+v2@example.com').get()
print(response.status_code)
print(response.response_body)

request_body = {
  "recipient_emails": [
    "test1+v2@example.com",
    "test2+v2@example.com"
  ]
}

response = sg.client.asm.suppressions._('global').post(request_body=request_body)
print(response.status_code)
print(response.response_body)

response = sg.client.asm.suppressions._('global')._('test1+v2@example.com').get()
print(response.status_code)
print(response.response_body)

response = sg.client.asm.suppressions._('global')._('test2+v2@example.com').get()
print(response.status_code)
print(response.response_body)
```
