### ISSUE TITLE
bug in sendgrid home page example code

### ISSUE THREAD

**Issue by adridcode** [sendgrid/sendgrid-python#151]
Hi,

Not sure, if it is the place to report this.
But there is a bug in the python example code present in the home page:
![sendgrid_home_page](https://cloud.githubusercontent.com/assets/9308387/11338758/393ab13e-91f6-11e5-94d1-291d2e8a0c41.png)

The code should be:
```python
# using SendGrid's Python Library - https://github.com/sendgrid/sendgrid-python
import sendgrid
 
sg = sendgrid.SendGridClient(api_user, api_key)
message = sendgrid.Mail()
 
message.add_to("test@sendgrid.com")
message.set_from("you@youremail.com")
message.set_subject("Sending with SendGrid is Fun")
message.set_html("and easy to do anywhere, even with Python")
 
sg.send(message)
```

sg = sendgrid.SendGridClient(api_user, api_key)
and not
sendgrid = sendgrid.SendGridClient(api_user, api_key)

sg.send(message)
and not sendgrid.send(message)

**Comment by thinkingserious** [comment]
Thanks, we appreciate your report! 

We are aware of these bugs and it's on our radar to fix.
