### ISSUE TITLE
User not authorized error for - client asm_groups get method

### ISSUE THREAD

**Issue by adityapingle** [sendgrid/sendgrid-python#153]
When a client object, created using sendgrid.SendGridAPIClient('API_KEY'), is used to get unsubscribe groups throws an error stating user needs to be authorized. There is no authorize_user, or something related, available in the docs, at least.

**Comment by thinkingserious** [comment]
This generally happens with incorrect credentials. Can you executing this example? https://github.com/sendgrid/sendgrid-python/blob/master/example_v3_test.py

**Comment by adityapingle** [comment]
i tried using the example code..same error, I can send emails perfectly but it gives error when trying to get unsubscribe groups...
do you want me to post screen-shots or the script i try?

**Comment by adityapingle** [comment]
I tried using above example, it raises same error..
Whereas I can send emails perfectly..
I have attached a screen-shot, which shows sendgrid function calls in python shell..
1) Send Email function executes well
2) APIClient function raises authorization error
![sendgrid_api_error_1](https://cloud.githubusercontent.com/assets/2194051/11421249/9afe43bc-9459-11e5-9068-3b7688ffbe54.png)

**Comment by thinkingserious** [comment]
Ah, now I see the problem.

For sending emails, you are using the old method, which utilized a username and password. So in the above example API_KEY is really your password. To generate a proper API_KEY, please go here: https://app.sendgrid.com/settings/api_keys

Once you have generated your API_KEY, you can construct both objects like so:
sg = sendgrid.SendGridClient(API_KEY)
client = sendgrid.SendGridAPIClient(API_KEY)

Thanks for supplying the extra details!

**Comment by adityapingle** [comment]
Thank you...creating key from the provided url solved my issue..

there is a method in the documentation...for generating API keys
the code goes like this...
client = sendgrid.SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
name = "My Amazing API Key"
status, msg = client.apikeys.post(name)

how someone is supposed to create the "first" API_KEY? he needs to create SendGridAPIClient object, which requires authentication. How can someone get authenticated without the API_KEY?

**Comment by thinkingserious** [comment]
Sorry for the confusion, I have updated the README to clarify: https://github.com/sendgrid/sendgrid-python/commit/e7ae3e6d21c42921731c5a8b314782273bd51986

Thanks for the valuable feedback, we appreciate it!
