### ISSUE TITLE
Can't install normally

### ISSUE THREAD

**Issue by seadog007** [sendgrid/sendgrid-python#155]
When I install sendgrid, it can't install normally. And I also tried to clone from this repo and install it
![photo_2015-12-04_08-28-46](https://cloud.githubusercontent.com/assets/5138409/11578506/431963f8-9a61-11e5-898f-62222a023a68.jpg)

I tried to clear the README.rst, and it works, please fix it.

**Comment by thinkingserious** [comment]
Fixed with [this release](https://github.com/sendgrid/sendgrid-python/releases/tag/v1.5.19), thanks for bringing this to our attention!
