### ISSUE TITLE
Syncing users

### ISSUE THREAD

**Issue by tschellenbach** [sendgrid/sendgrid-python#156]
Hi, is there support in this client library for syncing users?
https://sendgrid.com/docs/API_Reference/Web_API_v3/user.html

**Comment by tschellenbach** [comment]
To add a bit more detail. For getstream.io I'd like to sync my userbase to Sendgrid. Stream is python/django based. It looks as though I can do this using your subuser (what a name) API endpoint:
https://sendgrid.com/docs/API_Reference/Web_API_v3/subusers.html

However that doesn't seem to be supported by your python client.

**Comment by tschellenbach** [comment]
Ok, so contacts is the right name: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html

**Comment by thinkingserious** [comment]
@tschellenbach We have plans to add this endpoint to the library, but I don't have a realistic estimate right now. 

In the mean time, if you want to fork this repo and implement that endpoint yourself, I suggest you take a look at this code: https://github.com/sendgrid/sendgrid-python/tree/master/sendgrid/resources

Thanks!
