### ISSUE TITLE
DELETE method in SendGridAPIClient should include a body (data)

### ISSUE THREAD

**Issue by fotopher** [sendgrid/sendgrid-python#158]
The delete method in SendGridAPIClient should allow the caller to provide a body. For a usecase, see:
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Delete-Recipient-DELETE

**Comment by mbernier** [comment]
We just reworked our library to include all v3 endpoints, which also included modifying this endpoint. Could you please check to see if this issue is still there in the new version?

**Comment by thinkingserious** [comment]
The new library, now depends on python_http_client, which supports adding a body to a DELETE endpoint: https://github.com/sendgrid/python-http-client/blob/master/python_http_client/client.py#L189

Thanks!
