### ISSUE TITLE
Template Engine usage

### ISSUE THREAD

**Issue by VictorAcatrinei** [sendgrid/sendgrid-python#159]
What does `'TEMPLATE-ALPHA-NUMERIC-ID'` mean when using the template engine in the SMTPAPI header? Is it the same as the previous parameter, the `'template_id'`?

Also, what is the use of `message.add_substitution('key', 'value')` in this case? Why is it included in this section?

Thanks!

**Comment by mbernier** [comment]
Please check out the new documentation that we have for the API endpoints and let us know if you still have questions!

**Comment by thinkingserious** [comment]
@VictorAcatrinei please reach back out if you continue to experience any issues. Thanks!
