### ISSUE TITLE
Can't install 2.0.0 from pypi with pip

### ISSUE THREAD

**Issue by samwillis** [sendgrid/sendgrid-python#167]
#### Issue Summary

It looks like version 2.0.0 hasn't been uploaded to PyPI properly, there is no packages attached and so pip cant install it.

#### Steps to Reproduce

1. > pip install sendgrid==2.0.0

#### Technical details:

* sendgrid-python Version: 2.0.0
* Python Version: All

**Comment by elbuo8** [comment]
@samwillis should be up now. Sorry for that :sob:

**Comment by thinkingserious** [comment]
Thanks @elbuo8!
