### ISSUE TITLE
Explicit information about where/how env variables are set

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#168]
#### Issue Summary

> The API Key has to be defined as SENDGRID_API_KEY as an OS variable and can't be passed to the Client API in any other way.

This is not explicit in the documentation here or on the site.

**Comment by thinkingserious** [comment]
Fixed with release [v2.1.1](https://github.com/sendgrid/sendgrid-python/releases/tag/v2.1.1)

You can now pass in an API key to the client or use an OS variable.

Thanks!
