### ISSUE TITLE
Update help for pydoc in Python library

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#170]
#### Issue Summary

Try running `pydoc sendgrid` for an example.

Here is a reference on how to implement: https://docs.python.org/3/library/pydoc.html

At a minimum, we should provide reference points to the docs and examples.

**Comment by talaniz** [comment]
I'd like to take a look at this if that's ok. I'm familiar with sendgrid.

**Comment by thinkingserious** [comment]
Awesome! Thanks @talaniz!

Please be sure to sign our CLA so we can merge your work: https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#cla

**Comment by gabrielkrell** [comment]
Working on this one now.
