### ISSUE TITLE
Update example code and documentation with better default data

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#171]
The current default example data for the [examples](https://github.com/sendgrid/sendgrid-python/tree/master/examples) and [USAGE](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md) should be based on "real" fake data. See the [SendGrid docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html) for examples.

**Comment by austinlyons** [comment]
Hey Elmer! The current example for creating a recipient via the contacts db API isn't runnable. It seems that the endpoint is expecting an array, like so:

```
##################################################
# Add recipients #
# POST /contactdb/recipients #

data = [{'email': 'joe@example.com'}]
response = sg.client.contactdb.recipients.post(request_body=data)
print(response.status_code)
print(response.response_body)
print(response.response_headers)
```

Wanted to mention this here in case anyone else is looking at or trying to run the examples.

**Comment by thinkingserious** [comment]
Thanks!

I'll be updating all the examples with real example data derived from our updated Swagger spec: https://github.com/sendgrid/sendgrid-swagger, which will be updated soon to include the same example response body data in our current documentation.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-python/commit/df108a2b0b039cd2cdb99ae717ac571358652c10

cc @austinlyons

**Comment by austinlyons** [comment]
Thanks!
