### ISSUE TITLE
Api endpoint check if a recipient  is in suppressions

### ISSUE THREAD

**Issue by inputjoker** [sendgrid/sendgrid-python#175]
`sg.client.asm.groups._(asm_group_id).suppressions.get()` gets me the list of unsubscribers, is there an api to check whether an email is in suppressions?

**Comment by thinkingserious** [comment]
Hello @inputjoker,

Thanks for reaching out!

Currently you can only directly check if an email is in global suppressions: https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/global_suppressions.html#Determine-if-an-email-address-belongs-to-the-Global-Unsubscribes-collection-GET

I suggest you request this functionality here: https://community.sendgrid.com/sendgrid

With Best Regards,

Elmer
