### ISSUE TITLE
Status 202

### ISSUE THREAD

**Issue by anselal** [sendgrid/sendgrid-python#182]
#### Issue Summary

I get status 202 but the email gets send successfully. What does this status mean ?

#### Technical details:

* sendgrid-python Version: 3.0.0
* Python Version: 2.7.9

**Comment by thinkingserious** [comment]
Hi @anselal,

That means: "Your message is both valid, and queued to be delivered."

Here is a list of the possible status codes: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html

Thanks!

**Comment by fenderjair** [comment]
I get the same message but the email is not received.

Do you have any suggest?

**Comment by thinkingserious** [comment]
Hello @fenderjair,

It's possible the email may have ended up in SPAM. If not, I suggest you reach out to [our support team](https://support.sendgrid.com) to dig deeper into your account. 

With Best Regards,

Elmer
