### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 415: Unsupported Media Type

### ISSUE THREAD

**Issue by kajala** [sendgrid/sendgrid-python#183]
#### Issue Summary

I tried to run the first ("Hello Email") example but it does not work. Terminates with
urllib.error.HTTPError: HTTP Error 415: Unsupported Media Type

#### Steps to Reproduce

1. Copy-paste the Hello Email
2. Replace with your own apikey
3. Get urllib.error.HTTPError: HTTP Error 415: Unsupported Media Type as result

#### Technical details:

* sendgrid-python Version: 3.0.0
* Python Version: 3.5.1+
* OS: Ubuntu Linux 16.04 LTS

**Comment by thinkingserious** [comment]
Thanks for the report @kajala.

I have a couple of follow up questions:

1. How did you install the library?
2. By "replace with your own API key", did you setup an environment variable? Your code with the API key removed would help here. The example assumes you are storing your API key in an environment variable.

Thanks!

**Comment by kajala** [comment]
got it working now, python-http-client install had failed in venv but didn't notice. thanks for prompt reply!
