### ISSUE TITLE
Getting HTTP Error 406 when getting bounces

### ISSUE THREAD

**Issue by arielnoname** [sendgrid/sendgrid-python#185]
#### Issue Summary

When I do: response = sg.client.suppression.bounces.get()
I get HTTP Error 406: NOT ACCEPTABLE in the console
Doesn't happen getting invalid emails, for example.

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7.11

**Comment by thinkingserious** [comment]
Hello @arielnoname,

I found the bug, we need to set the header "Accept" to be "application/json".

A workaround until we fix it is:

headers = {'Accept': 'application/json'}
response = sg.client.suppression.bounces.get(request_headers=headers)

Thanks!

**Comment by thinkingserious** [comment]
This is now fixed in https://github.com/sendgrid/sendgrid-python/releases/tag/v3.0.1
