### ISSUE TITLE
Cannot submit multiple categories to Categories Statistics endpoint

### ISSUE THREAD

**Issue by chrishenry** [sendgrid/sendgrid-python#186]
#### Issue Summary

When using the client to get [statistics for categories](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#retrieve-email-statistics-for-categories), it's not possible to submit multiple categories.
#### Steps to Reproduce

```
fun_stats = sg.client.categories.stats.get(query_params={
    'start_date': "2016-06-30",
    'categories': ['category1', 'category2'],
})
```

The above code makes a GET to this URL. Sendgrid returns a `404` for this request.

```
https://api.sendgrid.com/v3/categories/stats?categories=[u'category1', category2']&start_date=2016-06-30
```

When the correct behaviour is a GET with both `category1` and `category1` as values to `categories`. Sendgrid returns the expected response.

```
https://api.sendgrid.com/v3/categories/stats?categories=category1&categories=category2&start_date=2016-06-30
```

This seems to be a bug, as the [Sendgrid docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/categories.html#-GET-statistics) clearly state sending multiple categories is supported, and there doesn't seem to be a way to do that with this client.

I believe the issue is actually [here, in the python-http-client lib](https://github.com/sendgrid/python-http-client/blob/master/python_http_client/client.py#L101). `urlencode` should be passed a second parameter, (`doseq`), which will correctly format multiple values for parameters. ([urlencode docs](https://docs.python.org/2/library/urllib.html#urllib.urlencode))
#### Technical details:
- sendgrid-python Version: 3.0.0
- Python Version: 2.7

**Comment by thinkingserious** [comment]
Solved with https://github.com/sendgrid/python-http-client/pull/11

**Comment by ninadamondikar** [comment]
While multiple categories can be passed for Category Statistics, passing any more than 10 categories in the params leads to a 400 Bad Request error.

**Code to Reproduce**
cats = ['T1', 'T2, 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11']
params = {'categories': cats,'start_date': '2017-05-01', 'end_date': '2017-09-01', 'aggregated_by': 'day',}

Is there a way this limit can be lifted?

Thanks!

**Comment by thinkingserious** [comment]
Hi @ninadamondikar,

This is a [limitation of the API](https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html#-Example). I will pass along your feedback to the product team. Could you please describe your use case?

With Best Regards,

Elmer

**Comment by ninadamondikar** [comment]
Hi - 

My use case is that I am looking to export a dataset with all the stats for every single email category in my SendGrid account (which at this point is over a 100). This dataset will be used for internal reporting and analytics on email performance by being imported into a business intelligence software.

Currently, I have a workaround for this: making multiple calls offsetting each call by 10 starting from 0 and then combining the output. However as the number of categories keeps increasing lifting the cap on number of categories will help streamline the code.

Thanks!
Ninad

**Comment by thinkingserious** [comment]
Hello @ninadamondikar,

Do you mind opening up a new issue specifically for this request? I'd like to try and get better visibility to increase its priority.

Thanks!

With Best Regards,

Elmer
