### ISSUE TITLE
Python 3 incompatible sources at PyPI

### ISSUE THREAD

**Issue by Krejdom** [sendgrid/sendgrid-python#191]
Hi,
I have downloaded sources (version 3.0.6) from PyPI and I am trying to modify the specfile to be Python 3 compatible in Fedora. Unfortunately there is a one line which cannot be executed with Python 3.
Could you please update the sources?

It is a file sendgrid/**temp.py**, **line 36**:
`      print e.read()`        >        `      print(e.read())`

**Comment by kevin-brown** [comment]
Given that this file appears to be ignored by `.gitignore`, my guess is that it shouldn't have been included in the source that was pushed up.

**Comment by thinkingserious** [comment]
@Krejdom thanks for letting us know! I will be updating this repo later today and I will remove that file, it does not belong there.

@kevin-brown  you are correct, that file was supposed to be ignored :/ I will remove it with an update I will be publishing today.

**Comment by thinkingserious** [comment]
@Krejdom actually, I don't see the file in there right now: https://github.com/sendgrid/sendgrid-python

It is safe to just delete that file.
