### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by jasonab** [sendgrid/sendgrid-python#193]
#### Issue Summary

Currently, all error handling is through raw returns of HTTP status codes. The library should throw standard Python exceptions on failure, hopefully giving error messages explaining what happened and why.
#### Technical details:
- sendgrid-python Version: 3.0.6

**Comment by thinkingserious** [comment]
Hello @jasonab,

Thanks for the feedback! 

We will definitely be refactoring the error handing system. Thanks for providing some specific feedback that we can consider while we do so.

We will leave this ticket open so others can vote and comment, pushing the priority up.

For now, you can do the following: https://github.com/sendgrid/sendgrid-python/blob/troubleshooting/TROUBLESHOOTING.md#error-messages

**Comment by thinkingserious** [comment]
Reference: https://github.com/sendgrid/sendgrid-python/issues/299

**Comment by ke2ulpatani** [comment]
I am hoping to work on this issue, is it still open?

**Comment by thinkingserious** [comment]
Hi @ke2ulpatani,

This issue has been addressed [here](https://github.com/sendgrid/python-http-client/issues/16). However, we are currently upgrading this SDK and would [love your feedback](https://github.com/sendgrid/sendgrid-python/issues/323).

With Best Regards,

Elmer

**Comment by Logan1x** [comment]
Is there any beginner friendly issue in python or documentation?

**Comment by thinkingserious** [comment]
Hi @Logan1x,

Yes!

Please follow [this search](https://github.com/sendgrid/sendgrid-python/labels/difficulty%3A%20easy) as we'll be adding new issues all throughout Hacktoberfest and beyond.

With Best Regards,

Elmer
