### ISSUE TITLE
'api_key' override 'apikey' in 'SendGridAPIClient' constructor

### ISSUE THREAD

**Issue by RaphaelJ** [sendgrid/sendgrid-python#199]
#### Issue Summary

Calling `SendGridAPIClient`with the `apikey` parameter does not work, contrarily to what the README's example states.

#### Steps to Reproduce

    import sendgrid as sg
    s = sg.SendGridAPIClient(apikey='<API KEY>')
    print(s.client.request_headers['Authorization'])
    # Should print "'Bearer <API KEY>" but prints "Bearer None"

This is due to an error in `SendGridAPIClient`'s `__init__()` method. The third line override any value that has been written on the first line:

    self._apikey = opts.get('apikey', os.environ.get('SENDGRID_API_KEY'))
    # Support v2 api_key naming
    self._apikey = opts.get('api_key', os.environ.get('SENDGRID_API_KEY'))

#### Technical details:

* sendgrid-python Version: master (latest commit:  e56028b)
* Python Version: 3.4

**Comment by thinkingserious** [comment]
@RaphaelJ,

Apologies, I did not deploy the fix correctly: https://github.com/sendgrid/sendgrid-python/commit/22f406a4df17742ef96341e43f8ac776e533bf08

I'm going to redeploy with version number 3.1.10 in a moment.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-python/releases/tag/v3.1.10
