### ISSUE TITLE
Substitution with non-string arguments fails silently

### ISSUE THREAD

**Issue by cosmith** [sendgrid/sendgrid-python#201]
#### Issue Summary

Hi, when adding substitutions that are not strings in a Mail object, calls to `sg.client.mail.send.post` will fail with a `400` error and no message other than `Bad Request`.
After spending 2 or 3 hours tearing my hair out over this I think there should be an error message somewhere. Maybe prevent `Substitution` from taking non-string arguments? The best of course would be for the API to return an error message...

#### Steps to Reproduce

```python
    template_data = {"test": 123}
    mail = Mail()

    addresses = format_to(to)
    for email_address in addresses:
        personalization = Personalization()
        personalization.add_to(Email(email_address))
        for tag, substitution in template_data.iteritems():
            personalization.add_substitution(Substitution(tag, substitution))
        mail.add_personalization(personalization)

    mail.set_from(Email(from_address, from_name))
    mail.set_subject(" ")
    mail.add_content(Content("text/plain", " "))
    mail.add_content(Content("text/html", " "))
    mail.set_template_id(template_id)

    sg.client.mail.send.post(request_body=mail.get())
```
#### Technical details:

* sendgrid-python Version: 3.0.0
* Python Version: 2.7

**Comment by thinkingserious** [comment]
@cosmith,

Thank you for the feedback! 

To get the detailed error message from the API, please see: https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#error-messages

On our roadmap:
- Make it easy to grab the error from the API through this library
- Add data validation to the Mail Helper

If you run into issues again, please don't hesitate to reach out.

I've added your vote to the above items on the roadmap to help push them up the queue.

**Comment by cosmith** [comment]
Hi @thinkingserious, I did check the error returned from the API but it's not very useful... You might want to send this to the API team too :)
`Error sending the email: {"errors":[{"message":"Bad Request","field":null,"help":null}]}`

**Comment by thinkingserious** [comment]
@cosmith,

Thanks for the follow up, turns out that we have an update pending on our backlog to provide a useful error for this particular case. I will add a +1 :)
