### ISSUE TITLE
Can't attach PDF file

### ISSUE THREAD

**Issue by claudiowilson** [sendgrid/sendgrid-python#203]
I can't seem to add attachments to my mail message?

```
with open("file.pdf", "rb") as f:
    attachment = Attachment()
    attachment.set_content(f.read())                                                                                                                                                                                          
    attachment.set_type("application/pdf")
    attachment.set_filename("itinerary.pdf")
    attachment.set_disposition("attachment")
    attachment.set_content_id("Itinerary")
    mail.add_attachment(attachment)
```

Calling ```mail.get()``` raises UnicodeDecodeError because it's trying to encode the contents into json. Has anyone figured out a way to do this? 
     
Using python 2.7 and sendgrid 3.0.7

I tried calling f.read().encode('base64'), but it returns 400: Content must be base64 encoded.

**Comment by claudiowilson** [comment]
awesome, thanks

**Comment by petervela** [comment]
I'm also facing the same issue.
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb5 in position 11: invalid start byte

**'You need the function b64encode'** - I would like to know where should I want to this function b64encode.After this function f.read().encode('base64') ?

**Comment by petervela** [comment]
I'm also facing the same issue.
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb5 in position 11: invalid start byte

'You need the function b64encode' - I would like to know where should I want to add this function b64encode.After this function f.read().encode('base64') ?

**Comment by thinkingserious** [comment]
Hello @petervela,

Here is a full example using attachments: https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#attachment

Please let me know if you continue to have an issue.

Thanks!

With Best Regards,

Elmer

**Comment by mick88** [comment]
@thinkingserious the link does not work

**Comment by thinkingserious** [comment]
My apologies, here is the correct link: https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/attachment.md
