### ISSUE TITLE
The Mail Helper class should use properties

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#207]
#### Issue Summary

https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py

**Comment by denis90** [comment]
I'd like to work on this issue

**Comment by thinkingserious** [comment]
Hi @denis90,

Thank you!

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/sendgrid-php/pull/287) so that we can merge your changes?
