### ISSUE TITLE
Content-Type should be application/json

### ISSUE THREAD

**Issue by BillBrower** [sendgrid/sendgrid-python#214]
#### Issue Summary

I'm getting a Content-Type error from the SendGridAPI.

```
{
   "errors": [ 
      {
        "message": "Content-Type should be application/json.",
        "field":null,
        "help":null
      }
   ]
}
```

What's weird is that if I add a 'Content-Type':'application/json' header to the Email object, I still get the same response.
#### Steps to Reproduce
1. Make a transactional email template, with one substitution ('-url-), in the SendGrid web app.
2. Define default subject line for the above transactional email template
3. Set the SENDGRID_API_KEY environment variable to your SendGrid API key 
4. Run this code:

```
import sendgrid
import os
from sendgrid.helpers.mail import Email, Personalization, Substitution, Mail
try:
    # Python 3
    import urllib.request as urllib
except ImportError:
    # Python 2
    import urllib2 as urllib

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
from_email = Email("test@example.com")
to_email = Email("test@example.com")
mail = Mail(from_email, to_email)
personalization = Personalization()
personalization.add_substitution(Substitution("-url-", "http://localhost:4200/reset-password"))
mail.add_personalization(personalization)
mail.set_template_id("13b8f94f-bcae-4ec6-b752-70d6cb59f932")
try:
    response = sg.client.mail.send.post(request_body=mail.get())
except urllib.HTTPError as e:
    print e.read()
    exit()
print(response.status_code)
print(response.body)
print(response.headers)
```

The Email object's get method returns this:

```
{
   'template_id': '712a20ca-e4ba-4e93-a1ea-9c73f7ecaf53',
   'personalizations': [
      {
          'substitutions': {
             '-url-': 'http://localhost:4200/reset-password'
          }
      }
   ]
}
```
#### Technical details:
- sendgrid-python Version: 3.3.1
- Python Version: 3.4

**Comment by thinkingserious** [comment]
Hello @BillBrower,

Please try the following: https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#with-mail-helper-class

If you are still running into trouble, please let me know.

Thanks!

**Comment by dhensen** [comment]
Hi @thinkingserious ,

I am experiencing the same problem even when using your example.
We're using python 3.5.2 and sendgrid 3.4.0.

**Comment by BillBrower** [comment]
@dhensen Including a subject and a content body in the Mail constructor fixed the issue for me. It turns out the library expects both, and won't work if either is missing.

```
class Mail(object):
    """Creates the response body for v3/mail/send"""
    def __init__(self, from_email = None, subject = None, to_email = None, content = None):
        self.from_email = None
        self.subject = None
        self.personalizations = None
        self.contents = None
        self.attachments = None
        self.template_id = None
        self.sections = None
        self.headers = None
        self.categories = None
        self.custom_args = None
        self.send_at = None
        self.batch_id = None
        self.asm = None
        self.ip_pool_name = None
        self.mail_settings = None
        self.tracking_settings = None
        self.reply_to = None

        # Minimum required to send an email
        if from_email and subject and to_email and content:
            self.set_from(from_email)
            personalization = Personalization()
            personalization.add_to(to_email)
            self.add_personalization(personalization)
            self.set_subject(subject)
            self.add_content(content)
```

@thinkingserious would you consider this to be a bug? It certainly isn't expected behavior since a template might be the only thing you want to send, and you can define a default subject for each template.

**Comment by thinkingserious** [comment]
@BillBrower 

Thanks for circling back to share the work around! Please email us at dx@sendgrid.com with your mailing address and T-shirt size :)

Yes, I consider this a bug.

Soon, we are going to be expanding the Mail Helper to make sending emails with templates, among other common use cases much easier. Please keep an eye on the issues section for details.

Finally, if you have a moment, your insight on this would be appreciated: https://github.com/sendgrid/sendgrid-python/issues/217

**Comment by BillBrower** [comment]
Thanks so much @thinkingserious. I've also noticed the same issue with the nodejs library. Would it be helpful for me to open an issue on that repo as well?

I'd be happy to look at #217. Let me know if there is anything else I can do to help, with sendgrid-python or sendgrid-nodejs!

**Comment by thinkingserious** [comment]
@BillBrower yes, an issue on the Node.js would be helpful :)

Thanks for providing your feedback on #217!

With regards to changes to our Mail Helper, check out: https://github.com/sendgrid/sendgrid-python/projects

Thanks again for your support!

**Comment by huygir** [comment]
@thinkingserious - "Soon, we are going to be expanding the Mail Helper to make sending emails with templates, among other common use cases much easier"..

Has this happened for the v3 PHP API?  I feel I'm wasting a lot of time on this.  Every approach has some issue from namespace to this kind (which I still cannot get around despite the feedback here).

I have a client who signed up for SendGrid, and I am new to it... these little errors in even published examples are driving me insane.  I was successful sending stupid simple emails, but I have to use my client's templates and every attempt to do so generates some sort of arcane error message.

**Comment by thinkingserious** [comment]
Hello @huygir,

Not yet, but perhaps I can help. Can you please open an issue in the PHP repo with your specific problem and perhaps some sample code?

Sending a simple email in PHP: https://github.com/sendgrid/sendgrid-php#hello-email
Using a template in PHP: https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional_templates

Thanks!

**Comment by thinkingserious** [comment]
Please refer to [this example](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#transactional_templates) for working with transactional templates. Thanks!
