### ISSUE TITLE
urllib2.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by anakinsolo** [sendgrid/sendgrid-python#216]
I have this issue when I try the sendgrid v3 with my python application. Here is how I implemented it from the sendgrid python example

import sendgrid
from sendgrid.helpers.mail import *

sg = sendgrid.SendGridAPIClient(apikey='API_KEY')

    from_email = Email('abcd@abcd.com')
    to_email = Email(email)
    subject = 'Job confirmation!'
    content = Content('text/plain','Hey '+str(name)+', here is the confirmation of your job from abcd\
                    Job: '+str(category)+' \
                    Price: '+str(price)+' \
                    Location: '+str(address))
    mail = Mail(from_email, subject, to_email, content)
    sg.client.mail.send.post(request_body=mail.get())

Then I try the example, exactly what it is from the website, I still have that same problem.

**Comment by thinkingserious** [comment]
Hello @anakinsolo,

This error means there is an issue with the API Key.

Please reach out to our support team so that they may look deeper into your account: https://support.sengdgrid.com

Thanks!

**Comment by nbosco** [comment]
@thinkingserious I receive the same error :(

**Comment by thinkingserious** [comment]
@nbosco,

Our support team should be able to help with that. They can be reached here: https://support.sendgrid.com

Thanks!

**Comment by jifferent** [comment]
@thinkingserious 

I have a same issue and  https://support.sendgrid.com cannot open. "This site can’t be reached"

**Comment by anakinsolo** [comment]
@jifferent 
I generated another API key and I dont have that error.

But still, I don't like the sendgrid v3. v2 was much better and easier to use to me

**Comment by jifferent** [comment]
@anakinsolo 

Thank you for the reply.

I generated another API with full access to everything, still the same error, I am just running their examples on Github

**Comment by thinkingserious** [comment]
Hello @jifferent,

I've just tested the support link and all appears to be good. Could you please try again?

**Comment by thinkingserious** [comment]
@anakinsolo,

We would love to explore how we can make v3 easier and better for you. 

This project is a step in that direction: https://github.com/sendgrid/sendgrid-python/projects

Please feel free to comment there or open issues expressing the details of what you would like to see changed.

Thanks!

**Comment by yuz835** [comment]
mine did work either, and had the same problem

**Comment by johnsenner** [comment]
Same over here! Just hit this tonight and fairly new to python and sendgrid. Still trying stuff.

**Comment by thinkingserious** [comment]
@yuz835, @johnsenner,

This is usually an issue with your account. Please reach out to our support team so that they can look into your specific account: https://support.sendgrid.com

Thank you!
