### ISSUE TITLE
Email to_names with commas causes sending issue.

### ISSUE THREAD

**Issue by prschmid** [sendgrid/sendgrid-python#22]
Attempting to send an email to someone with the name, for example

```
John Smith, PhD
```

will end up sending an email to

```
phd@<RANDOMTEXT>
```

As such, the `add_to` method for `Message` should auto-quote such names.

**Comment by patelnav** [comment]
This seems to have crept up again. https://github.com/sendgrid/sendgrid-ruby/issues/77
Just had this happen in Python

Perhaps add quotes around the name field on the get() method on helpers.mail.Email object to avoid this. 
Until then I've used the Email object with only the e-mail address and no name

**Comment by thinkingserious** [comment]
Hello @patelnav,

The email name can not have a ;, ., or ,. 

Reference: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters

Thanks!
