### ISSUE TITLE
Is there a way to use different whitelabel for sending Email

### ISSUE THREAD

**Issue by debugger22** [sendgrid/sendgrid-python#228]

**Comment by thinkingserious** [comment]
Hello @debugger22,

Please send your question over to https://sendgrid.support.com, we arehappy to help!

**Comment by debugger22** [comment]
<img width="396" alt="screenshot 2016-09-28 22 09 06" src="https://cloud.githubusercontent.com/assets/2821646/18922962/3fa9d11e-85c8-11e6-9cea-550d09744200.png">

I am still sad. :(

**Comment by debugger22** [comment]
I did see your codebase first before creating this issue. I didn't find any code to specify `whitelabel` in mail request.

**Comment by thinkingserious** [comment]
Hi @debugger22,

I just checked and the support site should be available. 

I think that the settings you want to modify are here: https://github.com/sendgrid/sendgrid-python/blob/master/examples/whitelabel/whitelabel.py

**Comment by debugger22** [comment]
Hi @thinkingserious 

Well, there was a typo. You directed me to https://sendgrid.support.com instead of https://support.sendgrid.com.

Examples at https://github.com/sendgrid/sendgrid-python/blob/master/examples/whitelabel/whitelabel.py shows how to create/update/delete whitelables. It doesn't show how to use a particular whitelabel for sending an E-mail.

**Comment by thinkingserious** [comment]
@debugger22,

Sorry about the typo!

I'm not sure how you would achieve what you want to do, but I think our support team will be able to help. Thanks!

**Comment by debugger22** [comment]
No problems! I'll talk to them.

Thanks Elmer!
