### ISSUE TITLE
Using .add_header()  raises a TypeError

### ISSUE THREAD

**Issue by elijah-schow** [sendgrid/sendgrid-python#230]
### Issue Summary
.add_header() cannot be used because python raises a TypeError exception.

### Steps to Reproduce
1. Create an instance of Mail `mail = Mail(  Email(from_email), subject, Email(to_emails), Content('text/html', message) )`
2. Add a header to the instance
`mail.add_header( {'Reply-To' : 'user@server.ext, user@server.ext'} )`
3. Send the Request
`response = sg.client.mail.send.post(request_body=mail.get())`

### Stack Trace
[File "mail.py", line 63](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L63), in **get**
> headers.update(key**.get()**)

TypeError: get expected at least 1 arguments, got 0

**Comment by thinkingserious** [comment]
Hello @elijah-schow,

Thanks for reporting this issue! We have added it to our backlog for a fix.
