### ISSUE TITLE
Substitutions allow non-strings for values

### ISSUE THREAD

**Issue by tylerreinhart** [sendgrid/sendgrid-python#232]
#### Issue Summary
API only allows strings for substitution values. This library will allow substitutions of non-strings and will fail on send attempt.

#### Steps to Reproduce
1. `message = Mail()`
2. `personalization = Personalization()`
3. `personalization.add_to(Email('test@email.com'))`
4. `personalization.add_substitution(Substitution('-test-, 1))`
5. `message.add_personalization(personalization)`
5. `sg.client.mail.send.post(request_body=message.get())` 400 returned because of int in substitution json

Should an error be thrown when attempting to create a non-string substitution?

**Comment by thinkingserious** [comment]
Hi @tylerreinhart,

Thanks for reporting this issue! I've added it to the backlog for execution.

I think we should make the conversion in the library and log a warning.

With Best Regards,

Elmer
