### ISSUE TITLE
400 Bad Request when sending transactional template from Django

### ISSUE THREAD

**Issue by koslibpro** [sendgrid/sendgrid-python#238]
#### Issue Summary

My code tries to send a transactional template email to a single recipient. I have created the template inside sendgrid dashboard and the code is taken from an example, without much stuff changed:
```
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
    data = {
        "personalizations": [
            {
                "to": [
                    {
                        "email": to_email  # variable on this method - str
                    }
                ],
                "subject": "Subject to be changed"
            }
        ],
        "from": {
            "email": "info@example.com"
        },
        "filters": {
            "templates": {
                "settings": {
                    "enable": 1,
                    "template_id": template_id  # variable on this method - str
                }
            }
        }
    }
    response = sg.client.mail.send.post(request_body=data)
```

#### Technical details:

* sendgrid-python Version: 3.6.0, installed from pip
* Python Version: 2.7.9
I use sendgrid as a Heroku add-on and the API key I've created has the greatest available access to any section. 

I suspect the data dict misses something, but cannot find what, or that my API key cannot authenticate though it has full access everywhere. Ideas?

**Comment by koslibpro** [comment]
How stupid am I on this? I shouldn't use filters key for this purpose, just the `template_id` key and set the template id in the value. It worked! Sorry guys for the inconvenience!

**Comment by thinkingserious** [comment]
No worries, I'm glad you solved your issue :)
