### ISSUE TITLE
Inbound parse webhook does not pass all bcc addresses in post data

### ISSUE THREAD

**Issue by c-w** [sendgrid/sendgrid-python#239]
#### Issue Summary

When receiving an email via the inbound parse webhook, some of the bcc recipients are dropped from the data that gets posted to the consuming flask application.
#### Steps to Reproduce
1. Set up a flask application to receive posted emails via the inbound parse webhook on some domain.
2. Send an email that lists in the bcc field two addresses on the domain.
3. Inspect `flask.request.form`

_Actual:_ The form contains a reference only to one of the bcc recipients.
_Expected:_ The form contains references to all the bcc recipients.
#### Example data

[Email sent](https://cloud.githubusercontent.com/assets/1086421/19826818/1326c2ca-9d4a-11e6-8bee-6bffad2d2cf1.png): contains references to "bcc1" and "bcc2".

[Post received](https://github.com/sendgrid/sendgrid-python/files/559718/form.json.txt): does not mention "bcc1" anywhere in the text.
#### Technical details:
- sendgrid-python Version: 3.4.0
- Python Version: 3.5

**Comment by thinkingserious** [comment]
Thanks @c-w!

We have added this to our backlog for review.

**Comment by c-w** [comment]
Hi @thinkingserious. Did you manage take a look at this report yet? Were you able to repro the issue? Do you need any more clarification?

It would be great if you could get around to investigating this: not being able to reliably receive BCCed emails seems like a pretty big hole in the inbound parse webhook and means that I'll likely have to go with a different EaaS vendor in the long term.

**Comment by thinkingserious** [comment]
Hello @c-w,

Not yet, but I've added @saicoder's vote to help push this up our queue.

**Comment by mbernier** [comment]
I am a bit confused. I believe that this is expected behavior of a Blind Carbon Copy (BCC) - the other recipients, as well as the BCC recipients,  should not be able to see each other. The sender of the email actually generates completely separate emails for each BCC recipient, so that there is no crossover. 
If you would like to have people copied on the emails and be able to see them, CC or multiple TOs should be used.
