### ISSUE TITLE
Empty response.body

### ISSUE THREAD

**Issue by ramuta** [sendgrid/sendgrid-python#245]
#### Issue Summary

I'm receiving an **empty** response.body when sending emails via SendGrid Python library:

    INFO     2016-11-02 09:31:32,046 email_worker.py:73] body: 
    INFO     2016-11-02 09:31:32,047 email_worker.py:74] headers: content-length: 0
    server: nginx
    x-message-id: LrnZRsWQTPy-ItZ3IJR2vQ
    connection: close
    date: Wed, 02 Nov 2016 09:31:32 GMT
    x-frame-options: DENY
    content-type: text/plain; charset=utf-8
    INFO     2016-11-02 09:31:32,047 email_worker.py:75] status: 202

The email is sent, but the response body is empty.

#### Steps to Reproduce

I use webapp2 framework on Google App Engine. I fetch the sendgrid Python library using pip. The above logs were printed like this:

```python
response = sg.client.mail.send.post(request_body=email_message.get())

logging.info("body: " + str(response.body))
logging.info("headers: " + str(response.headers))
logging.info("status: " + str(response.status_code))
```

#### Technical details:

* sendgrid-python Version: I have 3.2.10 version in PIP requirements
* Python Version: 2.7 (Google App Engine)

**Comment by ittus** [comment]
Hi @ramuta:
You can check Sendgrid document at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

It only indicates that response status code is 202, which means `Your message is both valid, and queued to be delivered`.

I think empty `body` is intended behavior.

**Comment by ramuta** [comment]
Hm, might be it - thanks :)
