### ISSUE TITLE
No support for attachments names with UTF-8 characters

### ISSUE THREAD

**Issue by jplaza** [sendgrid/sendgrid-python#248]
#### Issue Summary

The accent marks in the subject and HTML content show correctly, the name of the attachment prints as:
`nota-de-crÃ©dito`

#### Steps to Reproduce

```python
import sendgrid

sg = sendgrid.SendGridClient(settings.SENDGRID_API_KEY)
doc_name = u'Nota de Crédito'
message = sendgrid.Mail()
message.add_to(u'{} <{}>'.format(u'Juan Antonio Plaza', 'jplaza@datil.co'))
message.set_subject(doc_name)
message.set_html(u'<h1>Buenos días</h1>')
message.set_from('clientes@datil.co')
document_xml = u"""
    <?xml version="1.0" encoding="UTF-8"?>
    <autorizacion>
        <estado>AUTORIZADO</estado>
    </autorizacion>
"""
message.add_attachment_stream(u"{0}.xml".format(doc_name), document_xml)
sg.send(message)
```
#### Technical details:

* sendgrid-python Version: 2.2.1
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hello @jplaza,

It looks like you are not using an attachment object, like so: https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L65

Can you verify?
