### ISSUE TITLE
redundant to: field and content may not be empty

### ISSUE THREAD

**Issue by cl1ent** [sendgrid/sendgrid-python#276]
Hello,

i'm currently trying to send personalized emails to different recipients. However i have two open questions. The code can be found here: [https://gist.github.com/cl1ent/f6abeeec37ba9b65327aa5507ef80363](https://gist.github.com/cl1ent/f6abeeec37ba9b65327aa5507ef80363)
- when i try to send an email with a personalization (without adding another to field) i get the following error:

> The to array is required for all personalization objects, and must have at least one email object with a valid email address

But i've already declared a to field when i initially created the mail (line 9&11). why do i have to set two to: fields when i only want to send the mail to one recipient?

- second, my mails are static templates with placeholders. why do i have to create the mail object with a forced content? I've tried `mail = Mail(from_email, subject, to_email, None)` but that just gave me the following error:

> The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter.

What can i do to circumvent these two errors?

Thanks in advance,
cl1ent

**Comment by thinkingserious** [comment]
Hello @cl1ent,

Thanks for reaching out, I'm hoping this example will help you: https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#transactional_templates

With Best Regards,

Elmer

**Comment by cl1ent** [comment]
Hi @thinkingserious,

thanks for your response. `mail.personalizations[0].add_substitution()` worked for me! However I still wonder how to create a mail object without the subject field. This is because my subject field is already defined in the template.

Thanks,
cl1ent

**Comment by gstanek** [comment]
Hello @thinkingserious ,
I also have similar questions as @cl1ent regarding the v3 Mail python client and the use of personalizations.  

The biggest issue I have been facing is that the the `to:` field as part of the `mail = Mail(from_email, subject, to_email, content)` constructor is required.  If I use that same email for an individual personalization, as @cl1ent has done: `custom.add_to(Email("cl1ent@redact.ed", "cl1ent"))`, that email address will then receive two emails: 1 with all substitutions blank, and the other with all substitutions resolved.  

How do you recommend setting the `to:` fields with the v3 Mail client when using personalizations?

Thank you,
Gabe

**Comment by thinkingserious** [comment]
@cl1ent, @gstanek,

Here is a full example that does not use the helper constructor (that constructor was designed for the most basic of use cases): https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L20

Please take a look and let me know if you still have any issues.

With Best Regards,

Elmer

**Comment by gstanek** [comment]
Hi Elmer,
Thanks for following up.  With the help of the example you referenced, I was able to use the no-arg `Mail` constructor to create the Mail client and only send emails to the to emails specified within each personalization.

Thanks,
Gabe
