### ISSUE TITLE
Inconsistent format of email from header “name <email>”

### ISSUE THREAD

**Issue by andriisoldatenko** [sendgrid/sendgrid-python#277]
#### Issue Summary

Current implementation restrict use default `email_from` behavior. For more info please see https://tools.ietf.org/html/rfc2822#section-3.4

#### Steps to Reproduce
1. When user try to create `Email` instance from https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L173-L179. You must specify 
`from_email` and `from_name` as seperate parametrs
```
    def get(self):
        email = {}
        if self.name != None:
            email["name"] = self.name
        if self.email != None:
            email["email"] = self.email
        return email

from_email = Email("test@example.com", "Example Name")
```
As a result client should split `from_email`:
```
try:
    import rfc822
except ImportError:
    import email.utils as rfc822


from_name, from_email = rfc822.parseaddr(email.from_email)
# Python sendgrid client should improve
# sendgrid/helpers/mail/mail.py:164
if not from_name:
    from_name = None
Mail(from_email, from_name)
```

Proposal to how to improve this bahaviour.
Because if user now create `Email` from:
```
from_email = Email("Andrii Soldatenko <hello@asoldatenko.com>")
```
**Actual result:**
![image](https://cloud.githubusercontent.com/assets/1374633/20647168/e2159a04-b495-11e6-95f9-20c2bb5fc21f.png)

#### Technical details:

* sendgrid-python Version: master
* Python Version: all

#### References:
- https://github.com/sendgrid/sendgrid-python/issues/277
- RFC: https://tools.ietf.org/html/rfc2822#section-3.4
- Django docs: https://docs.djangoproject.com/en/1.10/topics/email/#emailmessage-objects

**NOTE:**
In `sengrid-python==1.4` this feature is working

**Comment by thinkingserious** [comment]
Nice work @andriisoldatenko!

I will add this to our backlog for an update. Thanks!

**Comment by mbernier** [comment]
@andriisoldatenko I know it's been a minute since you submitted this, but I am curious if my change accomplishes your request?
