### ISSUE TITLE
Mail Helper throws ascii uncode error on Russian last name

### ISSUE THREAD

**Issue by iamgollum** [sendgrid/sendgrid-python#286]
#### Issue Summary
Currently Mail Helper does not support non-ascii names. "Sirmen Kızılcan" would fail on a last name subsitution.

#### Steps to Reproduce

1. Create a Sendgrid email using helper
2. Add mail.personalizations[0].add_substitution(Substitution(":lastname", "Kızılcan"))
3. It should throw UnicodeEncodeError: 'ascii' codec can't encode character u'\u0131' in position 1: ordinal not in range(128)

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7.2

**Comment by thinkingserious** [comment]
Hi @iamgollum,

Thanks for the heads up! We will investigate.

**Comment by LiYChristopher** [comment]
Hi @iamgollum 

Was taking a look at the issue you were experiencing, and it's definitely a bit annoying to constantly need to encode Python 2.7 strings, which are by default in ASCII, to UTF-8. 

It would be great if the helper methods would enforce encoding based on Python version, but in the meantime if you need to continue using the SendGrid library w/ Python 2.7 you can try inserting:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

at the beginning of your .py file that's sending mail. Within most code editors (I tested on Vim), this will safely change the default encoding to UTF-8 when the file is executed. This allowed me to send mail with the substitution value `"Kızılcan"` without issue.

**Comment by iamgollum** [comment]
@LiYChristopher Thank you sir. I will try this out this weekend. Much appreciated!

**Comment by mehronkugler** [comment]
@iamgollum I encountered a similar error, and recently made a small code tweak to address this issue with unicode characters being used in Substitutions. Can you update your version of SendGrid and see if the issue still exists? I think it should not be a problem any more.
