### ISSUE TITLE
Mail received with email subject without mail body

### ISSUE THREAD

**Issue by sohamnavadiya** [sendgrid/sendgrid-python#289]
#### Issue Summary

I sent around 1400 mail to users using `sendgrid==3.6.3` lib. I have sent grid premium account.
I received 202 from sendgrid server. But all user received only email subject without email body.
Then after I tried to send email from my local machine using the same script then I got an email with email body. So, I am missing something over here or not. I can't understand the real reason behind it.
I am using django framework.

#### Steps to Reproduce

Above case happened in the production environment. So I can't execute the same script again until I am not confident.

#### Below is my sendgrid import statement.

```
import sendgrid
from sendgrid.helpers.mail import Email, Content, Substitution, Mail
try:
   # Python 3
   import urllib.request as urllib
except ImportError:
   # Python 2
   import urllib2 as urllib
```

#### Technical details:

* sendgrid version==3.6.3
* Python Version: 2.7

**Comment by sohamnavadiya** [comment]
I am facing this issue in iphone gmail application only. Other browser or application showing in clipped message form.

**Comment by thinkingserious** [comment]
@sohamnavadiya,

Thanks for the update. Does this mean your issue is resolved? Is there anything else I can help with?

Thanks!

**Comment by sohamnavadiya** [comment]
Yes, Issue has been resolved.

**Comment by aleksarias** [comment]
@sohamnavadiya, what resolved your issue?
I'm using python 3.8 and I can't get html or plain text body to get sent.
