### ISSUE TITLE
The `__str__` method of the `Mail` class, doesn't actually return anything

### ISSUE THREAD

**Issue by dpapavas** [sendgrid/sendgrid-python#292]
#### Issue Summary

The `__str__` method of the `Mail` class, doesn't actually return anything, hence trying something like `logging.debug("Mail: %s\n", some_mail)`, where `some_mail` is an instance of the `Mail` class, will result in an exception.

#### Steps to Reproduce

1. Instantiate the `Mail` class
2. Print the instance

This will result in a `TypeError` exception:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-119834a39903> in <module>()
----> 1 print(message)

TypeError: __str__ returned non-string (type NoneType)
```

One possible fix would be to replace

```python
    def __str__(self):
        self.get()
```

with

```python
    def __str__(self):
        return str(self.get())
```

#### Technical details:

* sendgrid-python Version: master (latest commit: [bdba1940c100d85b1978cd32ab95a1618c35a4b9])
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Thanks @dpapavas!

I've added this to our backlog for a fix.

**Comment by belfazt** [comment]
Created pull request https://github.com/sendgrid/sendgrid-python/pull/338
