### ISSUE TITLE
response code 202 followed by No-CORS headers from python server 

### ISSUE THREAD

**Issue by AntonioReyes** [sendgrid/sendgrid-python#298]
#### Issue Summary

Hi,

I got a script to send emails to multiple recipients using different templates 

I'm looping the email templates(10) then creating the email personalizations and send that template before continuing with the next:

	for template in campaign.campaign_templates.all():
		sg = sendgrid.SendGridAPIClient(apikey=settings.SENDGRID_API_KEY)
		print(template.subject)
		all_targets = campaign.campaign_items.filter(status=Target.PENDING)[:template.quantity]
		categories.append('template_{}'.format(template.template_id))
		categories.append('subject_{}'.format(slugify(template.subject)))
		# Perzonalization limit set by sendgrid 1000
		paginator = Paginator(all_targets, 500)
		mail = Mail()
		mail.set_from(Email("tce@tce.com", "Tom from tce"))
		mail.set_reply_to(Email("etc@etc.com"))
		mail.set_template_id(str(template.template_id))
		mail.set_subject(str(template.subject))
		for cat in categories:
			mail.add_category(Category(str(cat)))

		for page_number in paginator.page_range:
			page = paginator.page(page_number)
			targets = page.object_list
			for t in targets:
				name = <name>
				url = <url>

				personalization = Personalization()
				personalization.add_to(Email(str(t.content_object.email),str(name)))
				personalization.set_subject("Hello World from the Personalized SendGrid Python Library")
				personalization.add_substitution(Substitution(":name", str(name)))
				personalization.add_substitution(Substitution(":url_artist", str(url)))
				personalization.add_substitution(Substitution(":source_network", t.content_object.get_source_network_name()))
				mail.add_personalization(personalization)

			try:
				response = sg.client.mail.send.post(request_body=mail.get())
			except Exception as e:
				print(e)
				print(response.status_code)
				print(response.headers)
				print(response.body)
			print(response.status_code)
			

Results:

Only the first email get sent successfully, all the rest get the following response :  

Response code : 202

Server: nginx
Date: Fri, 24 Feb 2017 11:52:49 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: close
X-Message-Id: -iZ41PiCR6OVZ3o7fcpIlg
X-Frame-Options: DENY
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html

#### Technical details:

* sendgrid-python Version: sendgrid==3.6.3
* Python Version:  2.7.6

**Comment by AntonioReyes** [comment]
I have a feeling that it has something todo with sending the email from a loop and the rates of the api call ? maybe? :(

**Comment by AntonioReyes** [comment]
I found the issue and possible another bug in the api, I was adding categories in the loop which will were not cleared for every loop, so after  the first loop there were more categories added on the previous array, so I believe there is a limit on the number of categories on an email. However, the api error didn't make sense, so I guess this needs to be handle on the api side.

**Comment by thinkingserious** [comment]
Hi @AntonioReyes,

There is a limit of [10 categories per message](https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html).

The [202 response code](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html) means that "Your message is both valid, and queued to be delivered."

The headers you are viewing do not indicate an error, they are informational. If you received an error from the SendGrid API, you would receive a non 2XX status code and the error would be delivered in the body.

I hope that helps!

With Best Regards,

Elmer
