### ISSUE TITLE
Unwanted spaces in subject

### ISSUE THREAD

**Issue by blixt** [sendgrid/sendgrid-python#302]
I'm seeing unwanted spaces in the subject when sending through Sendgrid.

Here's the JSON of the `email.get()` object I'm passing into `….post(request_body=…)`:

```
{
    "content": [
        {
            "type": "text/plain",
            "value": "Welcome …"
        },
        {
            "type": "text/html",
            "value": "<!DOCTYPE html …"
        }
    ],
    "from": {
        "email": "hello@fika.io",
        "name": "fika.io"
    },
    "personalizations": [
        {
            "to": [
                {
                    "email": "andreasblixt@gmail.com",
                    "name": "Blixtson"
                }
            ]
        }
    ],
    "subject": "\ud83c\udf89 Congratulations Blixtson, your fika.io pass is here"
}
```

Here's the resulting email subject, as seen in Inbox:
<img width="1016" alt="screen shot 2017-03-29 at 6 22 40 pm" src="https://cloud.githubusercontent.com/assets/158591/24479328/c58a68b6-14ac-11e7-82a9-871d94f775d6.png">

Note the space after the `.` in "fika. io" (should be "fika.io").

And the raw Subject header in the email:

```
…
To: Blixtson <andreasblixt@gmail.com>
Message-ID: <WXNI-k4JTfOwc3IgHh9Z5A@ismtpd0006p1iad1.sendgrid.net>
Subject: 🎉 Congratulations Blixtson, your fika. io pass is here
…
```

This does not happen when I use another email service. Since the raw JSON appears correct, this might not be Python related, but I posted it here since it's the API interface I'm using.

#### Technical details:

* sendgrid-python Version: 3.6.4
* Python Version: 2.7

**Comment by SendGridDX** [comment]
Hello @blixt,

I suspect there is an encoding issue going on with your editor. I was not able to reproduce, but when I copied your sample code, I received the following error:

SyntaxError: Non-ASCII character '\xe2' in file temp.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

When I removed the `…` that error went away.

Could you please check the encoding on your editor?

Here is the code I used:

```python
import sendgrid
import os

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
data = {
  "personalizations": [
    {
      "to": [
        {
          "email": "elmer@sendgrid.com"
        }
      ]
    }
  ],
  "from": {
    "email": "dx@sendgrid.com"
  },
  "content": [
    {
            "type": "text/plain",
            "value": "Welcome"
        },
        {
            "type": "text/html",
            "value": "<bold>Testing</bold>"
        }
  ],
  "subject": "\ud83c\udf89 Congratulations Blixtson, your fika.io pass is here"
}
response = sg.client.mail.send.post(request_body=data)
print(response.status_code)
print(response.body)
print(response.headers)
```

And here was the result: https://screencast.com/t/m5QlVp6ZXr8

With Best Regards,

Elmer

**Comment by blixt** [comment]
Ah, the `…` were manually added for illustrational purposes, so you wouldn't have to look at all my HTML. You can safely remove them if you want to reproduce my case, because they aren't there in the actual sample (sidenote: in Python, to use Unicode in a string you have to use `u'…'`, which would work in this case).

The important part is what I send in as the `"subject"` value, and what comes out in the resulting email. I'm also unsure what the condition to reproduce this is. Here are two similar, but different email subjects we use, and as you can see they result in different outcomes:

```
# In our Python dict before formatting:
'subject': u'🎉 Congratulations %(invited_name)s, your fika.io pass is here',
# As JSON:
"subject": "🎉 Congratulations Blixt Test, your fika.io pass is here"
```

Results in (note the space after `fika.`):

> Subject: 🎉 Congratulations Blixt Test, your fika. io pass is here

But,

```
# In our Python dict before formatting:
'subject': u'🎉 %(invited_name)s, you\'re invited to join me on fika.io',
# As JSON:
"subject": "🎉 me+xyz, you're invited to join me on fika.io"
```

Results in:

> Subject: 🎉 me+xyz, you're invited to join me on fika.io

**Comment by blixt** [comment]
Here are the emails which were successfully sent and received (so no encoding error or anything), but obviously were delivered with an unwanted space after `fika.` in one of them:

<img width="974" alt="screen shot 2017-03-30 at 1 44 35 pm" src="https://cloud.githubusercontent.com/assets/158591/24518207/2b133792-154f-11e7-928a-17e497a999c0.png">

Since there is no space after the `fika.` in our template (I copied/pasted without altering it above), I can only assume there's something in the SendGrid API that attempts to add a space after periods in some cases, maybe in this case because `"fika.io"` was followed by `" pass is here"`?

**Comment by blixt** [comment]
Actually, I just had the bug occur on the exact same email flow (no code has been deployed on our end between the two emails in the screenshot below), which makes it less likely that it's a code problem.

<img width="975" alt="screen shot 2017-03-30 at 2 45 13 pm" src="https://cloud.githubusercontent.com/assets/158591/24520786/b16d377c-1557-11e7-8d58-1ffad5674ee2.png">

It could still be because of the string length (the string is longer in the buggy cases), or maybe because of different behavior depending on which API server is handling the request?

**Comment by blixt** [comment]
Another addition to the above, I just noticed that the space is inconsistently being added before OR after the period, which is even more confusing. Here is a sample of subjects in my inbox (formatting of `fika.io` added by me for the purposes of this comment, to make spacing more visible):

> 🎉 adamhowardprice, you're invited to join me on `fika .io`
> 🎉 me+bob@blixt.nyc, you're invited to join me on `fika. io`
> 🎉 me+xyz, you're invited to join me on `fika.io`
> 🎉 Blixtson, you're invited to join me on `fika.io`
> 🎉 Congratulations Blixt Test, your `fika. io` pass is here
> 🎉 Congratulations Bobby Blixt, your `fika. io` pass is here
> Ricardo Vice Santos sent you a video on `fika.io`
> #random has an update on `fika.io`

**Comment by mbernier** [comment]
Does it only happen when the 🎉  is included? 

For example, what happens in the first case without it?

> adamhowardprice, you're invited to join me on fika .io

**Comment by blixt** [comment]
I've now tried sending 1-40 characters long names for different templates using different characters for the names, and I'm seeing some interesting patterns:

* It only happens with emoji (I tried without the emoji and I couldn't get it to happen)
* It seems to always happen near punctuation, but not only periods
* It appears to be dependent on the length of the string and/or the offset of the punctuation
* It only happens to one punctuation in the subject – which one is dependent on the length/offset

Here's a sample of the subjects. I've added `^` below the lines that exhibit the bug:

```
🎉 A, you're invited to join me on fika.io
🎉 AA, you're invited to join me on fika.io
🎉 AAA, you're invited to join me on fika.io
🎉 AAAA, you're invited to join me on fika.io
🎉 AAAAA, you're invited to join me on fika.io
🎉 AAAAAA, you're invited to join me on fika.io
🎉 AAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAAAAA, you're invited to join me on fika .io
                                                    ^
🎉 AAAAAAAAAAAAAAA, you're invited to join me on fika .io
                                                     ^
🎉 AAAAAAAAAAAAAAAA, you're invited to join me on fika .io
                                                      ^
🎉 AAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                          ^
🎉 AAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                           ^
🎉 AAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                            ^
🎉 AAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                             ^
🎉 AAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                              ^
🎉 AAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                               ^
🎉 AAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                 ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                  ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                   ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                    ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                     ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                      ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                       ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                        ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                         ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                          ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                           ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                            ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                             ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you' re invited to join me on fika.io
                                              ^
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you're invited to join me on fika.io
🎉 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, you're invited to join me on fika.io
🎉 ., you're invited to join me on fika.io
🎉 .., you're invited to join me on fika.io
🎉 ..., you're invited to join me on fika.io
🎉 ...., you're invited to join me on fika.io
🎉 ....., you're invited to join me on fika.io
🎉 ......, you're invited to join me on fika.io
🎉 ......., you're invited to join me on fika.io
🎉 ........, you're invited to join me on fika.io
🎉 ........., you're invited to join me on fika.io
🎉 .........., you're invited to join me on fika.io
🎉 ..........., you're invited to join me on fika.io
🎉 ............, you're invited to join me on fika.io
🎉 ............., you're invited to join me on fika.io
🎉 .............., you're invited to join me on fika.io
🎉 ..............., you're invited to join me on fika.io
🎉 ................, you're invited to join me on fika.io
🎉 ................., you're invited to join me on fika.io
🎉 .................., you're invited to join me on fika. io
                                                         ^
🎉 ..................., you're invited to join me on fika. io
                                                          ^
🎉 ...................., you're invited to join me on fika .io
                                                          ^
🎉 ....................., you' re invited to join me on fika.io
                              ^
🎉 ......................, you' re invited to join me on fika.io
                               ^
# And so on
```

**Comment by blixt** [comment]
And finally, here's the complete, unedited JSON payload I sent for one of the faulty subjects above:

```
{
    "categories": [
        "debug"
    ],
    "content": [
        {
            "type": "text/plain",
            "value": "Just a test"
        },
        {
            "type": "text/html",
            "value": "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html lang=\"en\">\n<head>\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n  <meta name=\"format-detection\" content=\"telephone=no\">\n  <title></title>\n  <style type=\"text/css\">\nbody {\n  margin: 0;\n  padding: 0;\n  -ms-text-size-adjust: 100%;\n  -webkit-text-size-adjust: 100%;\n}\ntable {\n  border-spacing: 0;\n}\ntable td {\n  border-collapse: collapse;\n}\na.button {\n  border: #219653 solid 3px;\n  border-radius: 10px;\n  color: #219653;\n  display: block;\n  font-size: 22px;\n  font-weight: 500;\n  margin: 0 auto;\n  padding: 12px 0;\n  text-align: center;\n  text-decoration: none;\n}\nspan.code {\n  background: #000;\n  border-radius: 5px;\n  color: #fff;\n  display: block;\n  font-size: 36px;\n  font-weight: 500;\n  margin: 0 auto;\n  padding: 20px 0;\n  text-align: center;\n}\n.ExternalClass {\n  width: 100%;\n}\n.ExternalClass,\n.ExternalClass p,\n.ExternalClass span,\n.ExternalClass font,\n.ExternalClass td,\n.ExternalClass div {\n  line-height: 100%;\n}\n.ReadMsgBody {\n  width: 100%;\n  background-color: #ebebeb;\n}\ntable {\n  mso-table-lspace: 0pt;\n  mso-table-rspace: 0pt;\n}\nimg {\n  -ms-interpolation-mode: bicubic;\n}\n.yshortcuts a {\n  border-bottom: none !important;\n}\n.container {\n    margin: 2em 0;\n}\n@media screen and (max-width: 599px) {\n  .force-row, .container {\n    margin: 0;\n    width: 100% !important;\n    max-width: 100% !important;\n  }\n}\n@media screen and (max-width: 400px) {\n  .container-padding {\n    padding-left: 12px !important;\n    padding-right: 12px !important;\n  }\n}\n.ios-footer a {\n  color: #aaaaaa !important;\n  text-decoration: underline;\n}\n</style>\n</head>\n<body style=\"margin:0; padding:0;\" bgcolor=\"#F0F0F0\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n<table border=\"0\" width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#F0F0F0\">\n  <tr>\n    <td align=\"center\" valign=\"top\" bgcolor=\"#F0F0F0\" style=\"background-color: #F0F0F0;\">\n      <table border=\"0\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\" class=\"container\" style=\"width:600px;max-width:600px\">\n        <tr>\n          <td class=\"container-padding content\" align=\"left\" style=\"padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff;\">\n            <p style=\"text-align:center;\"><img alt=\"fika.io\" src=\"https://c.fika.io/s/fika-logo.png?v=20170312\" width=\"160\" height=\"50\"></p>\n<br>\n<div class=\"body-text\" style=\"font-family:Helvetica, Arial, sans-serif;font-size:16px;line-height:20px;text-align:left;color:#000\">Just a test</div>\n          </td>\n        </tr>\n      </table>\n    </td>\n  </tr>\n</table>\n</body>\n</html>\n"
        }
    ],
    "from": {
        "email": "hello@fika.io",
        "name": "fika.io"
    },
    "personalizations": [
        {
            "to": [
                {
                    "email": "me@blixt.nyc"
                }
            ]
        }
    ],
    "subject": "\ud83c\udf89 AAAAAAAAAAAAAAA, you're invited to join me on fika.io"
}
```

**Comment by SendGridDX** [comment]
Hello @blixt,

Thank you for taking the time to provide additional details. I believe this is an API level issue, so I'm going to dig in with the API team and provide feedback here as I learn more. 

With Best Regards,

Elmer

**Comment by SendGridDX** [comment]
Hello @blixt,

I have verified that this is a known bug on our end and it's in our backlog for a fix. I am monitoring the backlog item and I'll notify you here when its fixed. Unfortunately, I don't have an ETA.

With Best Regards,

Elmer

**Comment by taiyanzu** [comment]
We are facing the exact same issue. We do not use emoji characters. Our subject lines are like this `John, here's your update for June 20 – July 2, 2017`.
Expected:
```... here's ...```
Actual:
```... here' s ...```

Could you provide an update on the fix? Thanks!

**Comment by blixt** [comment]
Is the dash a regular figure dash (ASCII) or an en/em dash (extended character set)? If it's one of the latter, that could be the common ground with emoji.

**Comment by thinkingserious** [comment]
Hi @taiyanzu,

Unfortunately, I do not have an update, but I will be alerted when the issue is addressed and I will notify this thread. 

I'll pass along your vote to help gain some priority.

Thanks!

With Best Regards,

Elmer

**Comment by taiyanzu** [comment]
@blixt Yes, the dash is Unicode #2013(EN DASH). So the cause of the issue could be the same.

@thinkingserious Thanks for the reply and passing along the report!

**Comment by thinkingserious** [comment]
@blixt, @taiyanzu, 

I have some great news! This issue is finally resolved. 

@blixt,

With thanks for your detailed report, we would love to [offer you some swag](https://dx.sendgrid.com/swag) :)

With Best Regards,

Elmer

**Comment by blixt** [comment]
Yay! Thank you!

**Comment by VG13** [comment]
Hi there, we are seeing the same issue in the body of the email. In each email, spaces get added at random spots - there's no pattern that we can see so have no idea how to fix them. @SendGridDX @thinkingserious

**Comment by thinkingserious** [comment]
Hello @VG13,

Can you please [open a ticket with our support team](https://support.sendgrid.com)? Thank you!

With Best Regards,

Elmer

**Comment by VG13** [comment]
Done, thanks Elmer.
