### ISSUE TITLE
pip package ships with test package

### ISSUE THREAD

**Issue by blixt** [sendgrid/sendgrid-python#303]
This breaks any project that has the `sendgrid` package on its path and that imports a local `test` package without using relative import syntax.

Tests should only be used during development, and excluded from the published package.

#### Technical details:

* sendgrid-python Version: 3.6.4
* Python Version: 2.7

**Comment by SendGridDX** [comment]
Hi @blixt,

Thanks for taking the time to create this issue. We will resolve this issue soon with this PR: https://github.com/sendgrid/sendgrid-python/pull/300

I have added your vote to that issue to help move it up our queue.

With Best Regards,

Elmer
