### ISSUE TITLE
Not able to add 'Category' as header when sending mail through django app

### ISSUE THREAD

**Issue by aashvi** [sendgrid/sendgrid-python#304]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hello @aashvi,

Could you please provide a code snippet that demonstrates the issue?

Thanks!

With Best Regards,

Elmer

**Comment by aashvi** [comment]
Sure 


`                template = get_template('mailer.html')
                context = Context({'user': str(obj.name).title()})
                content = template.render(context)
                subject = "Hey "+str(obj.name).title() 
                to = [obj.email]
                from_email = 'CatchThatBus Team <noreply@catchthatbus.com>'
                msg = EmailMessage(subject, content, from_email, to, headers= {'Reply-To': 'mail@domain.com','X-SMTPAPI': {"category":"mycategory"}})  
                msg.content_subtype = 'html' 
                msg.send()`

**Comment by SendGridDX** [comment]
Hello @aashvi,

It appears that you are using a different SDK. This one does not have a `EmailMessage` object.

Could you please verify the SDK and version you are using?

Thanks!

Elmer

**Comment by kevin-brown** [comment]
> This one does not have a EmailMessage object.

I'm 80% sure that they are using Django with one of the Django / SendGrid adapters that are out there.

**Comment by aashvi** [comment]
It does have a EmailMessage object...

From above code only..

msg = EmailMessage(subject, content, from_email, to, headers= {'Reply-To': 'mail@domain.com','X-SMTPAPI': {"category":"mycategory"}})

**Comment by SendGridDX** [comment]
Hello @tricknotes,

This SDK has a [Mail](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L4) and [Email](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L183) object, but no 

I believe the code you have provided is from a different SDK. If you let me know how you installed the SDK, I could help you figure out what version and SDK you are using.

Thanks!

Elmer

**Comment by aashvi** [comment]
I'm using this

https://docs.djangoproject.com/en/1.10/topics/email/#the-emailmessage-class

**Comment by aashvi** [comment]
And I'm EmailMessage object only...

msg = EmailMessage(stuff)

**Comment by kevin-brown** [comment]
@aashvi What Django package are you using for integrating SendGrid with Django?

**Comment by aashvi** [comment]
"did you just set the SMTP settings for Django to the SendGrid SMTP server?" Exactly this

**Comment by SendGridDX** [comment]
Ah, thanks for clarifying @aashvi. This is an issue with our SMTPAPI and not this SDK. I suggest you reach out to our support team for help on that one: https://support.sendgrid.com.
