### ISSUE TITLE
Send-Grid response 400 if same email in Blind-carbon-copy and TO parameters is written

### ISSUE THREAD

**Issue by MuhammadTanveerAshraf** [sendgrid/sendgrid-python#306]
#### Issue Summary
I am using send-grid to send emails in a c# application. If I use different emails in TO and Blind-Carbon-Copy, it works fine. But when I tried it with same email addresses (e.g test@example.com in Blind Carbon Copy and same in TO), it gives Bad-request response (i-e 400). I didn't receive even a single email in that case. Can anyone have the same issue before?

#### Technical details:
* sendgrid-v3
* c#

**Comment by thinkingserious** [comment]
Hello @MuhammadTanveerAshraf,

This is expected behavior, duplicate emails are not allowed.

You should have received an error message to that effect in the [response body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#error).

Thanks!

With Best Regards,

Elmer
