### ISSUE TITLE
Disable Click Tracking not working

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#308]
#### Issue Summary

See https://github.com/sendgrid/sendgrid-python/pull/287

**Comment by dirtycoder** [comment]
@thinkingserious it seen to be solved already.

The current output is this:
`ClickTracking()` -> `{'click_tracking': {}}`
`ClickTracking(False)` -> `{'click_tracking': {'enable': False}}`
`ClickTracking(True)` -> `{'click_tracking': {'enable': True}}`

Do you think it's worth to make a PR with a test to prevent a regression?

**Comment by thinkingserious** [comment]
Yes, that would be great. Thanks!

**Comment by dirtycoder** [comment]
@thinkingserious ok, I'll do it. :)
