### ISSUE TITLE
BCC in additional Personalization doesn't work 

### ISSUE THREAD

**Issue by sheepsy90** [sendgrid/sendgrid-python#309]
#### Issue Summary

We came across this at least inconvenience in user experience of the API.
With the following code we get a 400 Bad Request error:

from_email = Email(from_email)
to_email = Email(to_email)
content = Content("text/html", html)

mail = Mail(from_email, subject, to_email, content)

bcc_email = Email('some.email@domain.com')
ps = Personalization()
ps.add_bcc(bcc_email)

mail.add_personalization(ps)
return self.sg_client.mail.send.post(request_body=mail.get())

#### Steps to Reproduce

See above code

#### Technical details:

* sendgrid-python Version: 4.0.0
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hi @sheepsy90,

The Mail constructor is only for the most simple of use cases. Please see [this example](https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L20) for how to build a custom mail object.

Note that we will be improving the Mail Helper to support more simple use cases, such as yours. To follow that project, see the "Mail Helper Enhancement (v3 mail/send)" project [here](https://github.com/sendgrid/sendgrid-python/projects).

If you continue to have trouble, please let me know.

Thanks!

With Best Regards,

Elmer

**Comment by scottwilson312** [comment]
I am confused how the first person's code is different than the example? The only difference I can spot is using the mail constructor with some additional params as opposed to just Mail() ?
