### ISSUE TITLE
 Text content not sorted to in front of HTML

### ISSUE THREAD

**Issue by chaffeqa** [sendgrid/sendgrid-python#317]
#### Issue Summary

Text content not sorted to in front of HTML

#### Steps to Reproduce

1. Kitchen sink
2. Move `add_content('text/html'...)` in front of `add_content('text/plain'...)`
3. Run - get 400

#### Technical details:

* sendgrid-python Version: 4.1.0
* Python Version: 3.6.0

**Comment by thinkingserious** [comment]
Hi @chaffeqa,

Thanks for the heads up. We will implement this in the helper as part of [this PR](https://github.com/sendgrid/sendgrid-python/pull/316).

If you need that functionality now, I would suggest submitting a PR.

Thanks!

With Best Regards,

Elmer
