### ISSUE TITLE
BadRequesterror

### ISSUE THREAD

**Issue by priveras** [sendgrid/sendgrid-python#322]
Hi I'm having problems sending email using sendgrid-django. It works on my localhost without any problem and for some reason it won't work on the server. I have installed all dependencies and still no solution.

I'm getting this error

BadRequestsError at /accounts/twitter/login/callback/
No exception message supplied
Request Method:	GET
Request URL:	http://104.131.123.97/accounts/twitter/login/callback/?oauth_token=UKmg2wAAAAAAW_laAAABXRTN-1A&oauth_verifier=Jf4ULqwcU01sbA4t6EXI0vt0YrgYBkNW
Django Version:	1.9.8
Exception Type:	BadRequestsError
Exception Location:	/usr/local/lib/python2.7/dist-packages/python_http_client/client.py in _make_request, line 161
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/django/earlist',
 '/home/django',
 '/usr/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 5 Jul 2017 17:10:30 -0500

**Comment by thinkingserious** [comment]
Hi @priveras,

Do you mind posting this issue here: https://github.com/elbuo8/sendgrid-django

Thanks!
