### ISSUE TITLE
Cannot install sendgrid with pip

### ISSUE THREAD

**Issue by DannyLee12** [sendgrid/sendgrid-python#325]
#### Issue Summary

(dentsu) ➜  Development pip install sendgrid
Collecting sendgrid
  Could not find a version that satisfies the requirement sendgrid (from versions: )
No matching distribution found for sendgrid

#### Steps to Reproduce
pip install sendgrid

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 3.6
* Mac osx Sierra 10.12.5 (16F2073)

**Comment by thinkingserious** [comment]
Hello @DannyLee12,

I am having trouble reproducing this issue. I'm not sure what this means: (dentsu) ➜ Development, could you please elaborate on that step?

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @DannyLee12,

Were you able to resolve this issue?

Thanks!

Elmer
