### ISSUE TITLE
python-http-client compatibility issues with new 4.2.1 version

### ISSUE THREAD

**Issue by Pieter19** [sendgrid/sendgrid-python#328]
#### Issue Summary

Latest version of sendgrid-python causes huge compatibility issues, due to missing Response's methods (e.g. to_dict), exceptions and so on in the older python-http-client.

Issue correlates with #321 

In my opinion package shouldn't drop features unless those features were tagged as deprecated at least for a while.

How should I interpret it? Should I refactor my code?

#### Technical details:

* sendgrid-python Version: 4.2.1
* Python Version: 3.6.1

**Comment by thinkingserious** [comment]
Hi @Pieter19,

Please revert to v4.2.0 while I figure out the best solution.

The issue with #321 was that we introduced a breaking change in python-http-client that was not intended to make it up to this SDK just yet. So 4.2.1 was a fix for that.

I'm thinking that I'll need to make a breaking change in this SDK, to version 5.0.0 to incorporate the latest changes in v4.2.1.

Thank you very much to alerting us to this issue!

With Best Regards,

Elmer

**Comment by sklarsa** [comment]
Are you going to bring back the custom exceptions in `python_http_client.exceptions` in v5.0.0?  My library, https://github.com/sklarsa/django-sendgrid-v4, depends on catching those exceptions.

**Comment by thinkingserious** [comment]
Hi @sklarsa,

Yes, v5.0.0 will depend on the latest version of python_http_client. I'm hoping to have that pushed out by the end of the week. My apologies for the delay.

With Best Regards,

Elmer
