### ISSUE TITLE
Mail helper library breaks with unicode recipient names

### ISSUE THREAD

**Issue by mehronkugler** [sendgrid/sendgrid-python#334]
I encountered an issue using the helper library to send mails to recipients with unicode first name / last name:

`  File "/usr/local/lib/python2.7/dist-packages/sendgrid/helpers/mail/mail.py", line 379, in __init__
    self.value = value `
`  File "/usr/local/lib/python2.7/dist-packages/sendgrid/helpers/mail/mail.py", line 395, in value
    self._value = str(value) `
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)`

https://github.com/sendgrid/sendgrid-python/blob/a5c156124668e9180ce6f0ee9bc1c1a4061ad220/sendgrid/helpers/mail/mail.py#L395

Setting the encoding of the python document to utf-8 does not resolve/affect this issue. The code is converting unicode values to ascii.

**Comment by thinkingserious** [comment]
Thanks for the heads up. I've added this to our backlog.

For my own reference, I think this should do the trick: `self._value = str(value).encode('utf-8')`

For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

**Comment by thinkingserious** [comment]
@mehronkugler,

Do you mind providing some sample content that is causing the breakage? Thanks!
