### ISSUE TITLE
[Question] -- Send an Image in html -- TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by sevenfourk** [sendgrid/sendgrid-python#340]
Hi guys, thanks for the lib.

I'm writing small snippet to send email with attached image withing html code.  Looking at the example here: https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L73

I don't quite understand how an image read to be attached. Didn't have a change to look into sendgrid-python itself for further investigation yet.

this part of my code inside of a function:
```
    with open(image_name, 'rb') as f:
        image = f.read()
        f.close()

    image_encoded = base64.b64encode(image)

    attachment = Attachment()
    attachment.content = image_encoded
    attachment.type = "image/png"
    attachment.filename = image_name
    attachment.disposition = 'attachment'
    mail.add_attachment(attachment)

    mail.add_content(Content("text/html", '<img src="cid:"' + image_name + '">'))
    mail.add_header(Header('Content-ID', '<' + image_name + '>'))
```

I'm getting this error:
```
TypeError: Object of type 'bytes' is not JSON serializable
```

OS: Windows 10
Python: 3.6.2

Ivan.

**Comment by thinkingserious** [comment]
Hello @sevenfourk,

Were you able to resolve the issue? We have an example [here](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#attachment).

With Best Regards,

Elmer

**Comment by sevenfourk** [comment]
@thinkingserious, thanks a lot. I considered my image too big and decided to remote images, instead of attaching it directly.

**Comment by jgabrielfreitas** [comment]
Hi @thinkingserious , your example link is returning 404.
could you upload it again? maybe a gist

**Comment by thinkingserious** [comment]
Thanks for the heads up @jgabrielfreitas, I have fixed the link.
