### ISSUE TITLE
Email content being altered between send and receipt

### ISSUE THREAD

**Issue by jeffoneill** [sendgrid/sendgrid-python#341]
I'm pretty sure that this is not a Sendgrid issue but posting just in case.

For, a very small percentage of emails I send, the content is slightly altered by the time it hits the recipient's inbox.  I have a button like this:

`<a href="https://www.example.com/foo" style="padding:10px 25px; color:#FFF; text-decoration:none; cursor:pointer; border-radius:5px; background-color:#3d486f;">Vote</a>`

But in the recipient's inbox, the link has been altered to `https://www.examplecom/foo` (the dot before com is removed) which results in a broken link.

Has anyone experienced this and know what the cause might be?

**Comment by thinkingserious** [comment]
Hello @jeffoneill,

Thanks for posting this! Could you also please alert our [support team](https://support.sendgrid.com)? Thanks!

With Best Regards,

Elmer

**Comment by jeffoneill** [comment]
Hi Elmer, I've done a support request for this as well.

**Comment by jeffoneill** [comment]
I've uncovered some more detail on this and sharing here in case it helps others.

The emails that are being altered in transit are sent to btinternet.com email addresses.  If the recipient views the email at the btinternet website (which is based on Yahoo! webmail), the email content is correct.

If the recipient downloads the email automatically using POP/IMAP the email content gets altered between the btinternet website and the recipient's computer.  This happened to one person who uses OS X Mail and another who uses Eudora.  

The problem seems to be with btinternet, but unfortunately tech support there has no interest in investigating this.

**Comment by thinkingserious** [comment]
Thank you for taking the time to follow up with this. Hopefully, enough people will query btinternet to affect a change.
