### ISSUE TITLE
Getting Error :  python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by atulmishra-cleartax** [sendgrid/sendgrid-python#342]
#### Issue Summary

Seen a same issue under same subject like this but tried everything still error is not resolving ....

Code goes  : -

 ```
sg =sendgrid.SendGridAPIClient(apikey=os.environ.get('SG.t_erFBTkT5y8pnMNcaTF7A.huwK2sgd2Jv9FZ2t
        from_email = Email("atul.mishra@gmail.com")
        to_email = Email("atul.mishra@gmail.com")
        subject = "Sending with SendGrid is Fun"
        content = Content("text/plain", "and easy to do anywhere, even with Python")
        mail = Mail(from_email, subject, to_email, content)
        response = sg.client.mail.send.post(request_body=mail.get())
        print(response.status_code)
        print(response.body)
        print(response.headers)

```

Getting Error : 

`python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized`

Having error in response .

1.  Tried echo $SENDGRIDKEY and it's showing my send_grid api key

* Python Version: 3.6

**Comment by thinkingserious** [comment]
Hello @atulmishra-cleartax,

This is an error related to your API Key. Our [support team](https://support.sendgrid.com) can best assist with this.

Thanks!

With Best Regards,

Elmer
