### ISSUE TITLE
BadRequestsError when sending mail to v3 api when calling from Python Flask

### ISSUE THREAD

**Issue by agentidea** [sendgrid/sendgrid-python#343]
#### Issue Summary
I am trying to send mails using sendgrid.

I have a helper class that does this perfectly when run standalone from terminal 

`class SendGridHelper():
    def __init__(self, apikey):
        self.api_key = apikey

    def sendGridMailFromBag(self, bag):
        return self.sendMail( bag['from'], bag['to'], bag['subject'], bag['body'])

    def sendMail(self, from_email,to_email, subject, body ):

        sg = sendgrid.SendGridAPIClient(apikey = self.api_key)
        from_email = Email(from_email)
        to_email = Email(to_email)

        content = Content("text/plain", body)
        mail = Mail(from_email, subject, to_email, content)
        try:
            response = sg.client.mail.send.post(request_body=mail.get())
        except Exception as e:
            logger.exception(e)
            raise e

        return {"result": { "status": response.status_code, "body":response.body, "headers":response.headers}}`

`bag = {
                'from':'GrantSteinfeld@gmail.com',
                'to':'GrantSteinfeld@gmail.com',
                'subject':'test generated email',
                'body':'chassis {}'.format(datetime.datetime.now())}`

#### Steps to Reproduce

1. `curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "password": "*********", \ 
   "email": "grantsteinfeld%40gmail.com" \ 
 }' 'https://yourlastplaylist.com/api/user/signup'`

2. this is the important part of the exception

    response = sg.client.mail.send.post(request_body=mail.get())
  File "/Users/grantsteinfeld/anaconda/lib/python2.7/site-packages/python_http_client/client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "/Users/grantsteinfeld/anaconda/lib/python2.7/site-packages/python_http_client/client.py", line 161, in _make_request
    raise exc
BadRequestsError

3. Further steps, etc.

Not sure this is a bug but not sure why it works fine from command line but not from Flask

#### Technical details:

* sendgrid-python Version: used pip ... sendgrid (5.2.0)
* Python Version: 2.7.13

**Comment by thinkingserious** [comment]
Hello @agentidea,

Could you please try extracting the underlying error message [like so](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#error-messages)?  Thanks!

With Best Regards,

Elmer

P.S. I updated your comment to remove your password.

**Comment by agentidea** [comment]
Hi Elmer,

Thank you so much for responding.  I was able to dig down into the debugger and find that in 2 cases the email addresses where invalid ( ie once without the @ sign, and the other was incorrectly
entered as <xyz> someone@me.com rather than xyz <someone@me.com>  

I found the errors in 

`except python_http_client.BadRequestsError as postex:
            logger.exception(postex)
            errBody = json.loads(postex.body)
` 
the errBody is a list and I found the error there.

I will make sure email address validation occurs before sending to sendgrid

Best regards,

Grant
