### ISSUE TITLE
How can I send an email to a private SMTP server?

### ISSUE THREAD

**Issue by dopplesoldner** [sendgrid/sendgrid-python#344]
I am trying to send emails to a private SMTP server and can do so using python smtplib as follows

```
s = smtplib.SMTP(server, port)
s.sendmail(me, you, msg.as_string())

```
Trying to convert the same to Sendgrid (as Azure blocks SMTP) but it has no option to specify a private SMTP server.

```
import sendgrid
import os
from sendgrid.helpers.mail import *

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
from_email = Email("test@example.com")
to_email = Email("test@example.com")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "and easy to do anywhere, even with Python")
mail = Mail(from_email, subject, to_email, content)
response = sg.client.mail.send.post(request_body=mail.get())
print(response.status_code)
print(response.body)
print(response.headers)
Any help would be much appreciated.

```

**Comment by thinkingserious** [comment]
Hello @dopplesoldner,

I'm not sure I follow. The first code example is using a SMTP relay configuration while the second example uses our Web API. I'm not sure about the result you are looking for. 

Are you trying to use another SMTP provider besides sendgrid? 

With Best Regards,

Elmer
