### ISSUE TITLE
Can't get stats by category

### ISSUE THREAD

**Issue by ej-white** [sendgrid/sendgrid-python#345]
#### Issue Summary

This issue applies to the method 'sg.client.stats.get(query_params=params)'.

```python
params = {'start_date': '2017-07-01', 
                  'end_date': '2017-07-03', 
                  'aggregated_by': 'day', 
                  'categories': 'my-category'}
response = sg.client.stats.get(query_params=params)
all_responses = json.loads(response.body)
```

No matter which category I specify, I seem to get ALL events within the date range, same as if I didn't specify any categories at all. 

For example, I created a category called 'october-emails' for all emails sent in October. I then checked the stats for this category in the month of May with this payload:
```python
params = {'start_date': '2017-05-01', 
                  'end_date': '2017-05-30', 
                  'aggregated_by': 'day', 
                  'categories': 'october-emails'}
```
I expect the daily aggregations to be 0 for all events, as no emails were sent during May for this category. However, I see non-zero totals correspond to emails sent from other categories. Similarly, for any date range I always see the same totals no matter which category I specify. It's like it's not having any effect at all.

What is the correct way to receive stats for ONE category only? I've scoured the internet and all examples indicate that what I'm doing should work. 

Everything else with the API seems to work just fine.

#### Technical details:

* sendgrid-python Version: sendgrid==4.1.0
* Python Version: 2.7.12

**Comment by thinkingserious** [comment]
Hello @ej-white,

We do not currently support retrieving stats by category on that endpoint.

To get that level of detail, you would need to setup an [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html).

I have passed along your use case to our product team.

With Best Regards,

Elmer

**Comment by ej-white** [comment]
OK, good to know. Thanks for you quick response!
