### ISSUE TITLE
Python Mail Helper Refactor

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#347]
#### Issue Summary

An interface to easily interact with the `mail/send` endpoint of the [SendGrid v3 Web API](https://sendgrid.com/docs/API_Reference/api_v3.html).

The specification for this project is [here](https://github.com/sendgrid/sendgrid-python/blob/master/proposals/mail-helper-refactor.md) and the discussion around this specification can be found [here](https://github.com/sendgrid/sendgrid-python/issues/323).

#### Acceptance Criteria

All of the use cases [defined here](https://github.com/sendgrid/sendgrid-python/blob/master/proposals/mail-helper-refactor.md) are implemented and all corresponding tests are passing.

WIP Branch: https://github.com/sendgrid/sendgrid-python/tree/v4

**Comment by yothinix** [comment]
@thinkingserious I'd like to help on this issue, I've been using this lib in my project for about a year now. Hope my familiarity with this lib would help.

**Comment by thinkingserious** [comment]
@yothinix,

Awesome! Please let me know how I can help. 

With Best Regards,

Elmer

**Comment by kira0204** [comment]
What is the status of this?

**Comment by yothinix** [comment]
@kira0204 Sorry I didn't have much time to finish this now, you can go agead.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-python/pull/769
