### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Heroku with Python using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#356]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by anshuman73** [comment]
Hey ! I'd like to work on this !
Are there any similar examples that I can see ?
Is a basic flask app using this SDK fine ?

**Comment by mbernier** [comment]
Go for it!  We do love flask :)  Maybe this is just a quick app that when you hit a page it says "Email Sent" and based on the credentials, an email is generated and sent to the user?

The idea is just to make something really simple, that allows someone to get this posted to heroku and it actually does something other than just output a single UI page, in this case, sending an email.

**Comment by anshuman73** [comment]
Sounds perfect !

**Comment by zkan** [comment]
@thinkingserious @mbernier May I try Django for this?

**Comment by anshuman73** [comment]
Hi, @mbernier I currently did not proceed with this as @zkan submitted in a PR the very next day, and it made no sense to redo the same thing. Should I still proceed or the submitted PR is up to the mark -enabling us to close this issue ?

**Comment by zkan** [comment]
@anshuman73 I think you can still write a basic Flask for this. Let's combine the tutorial? :)

**Comment by swapagarwal** [comment]
@anshuman73 Are you still working on this? If not, I'd love to give this a shot! This will be my first interaction with SendGrid. (I have heard about SendGrid before, but never got around to using it.) 😄

**Comment by anshuman73** [comment]
Hey, sure. Feel free to take this up. Unfortunately, I haven't been able to take the necessary time for this :(

**Comment by cmccandless** [comment]
This was resolved in #443
