### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Digital Ocean with Python using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#357]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by yothinix** [comment]
@thinkingserious I want to help on this issue

**Comment by thinkingserious** [comment]
Thank you @yothinix!

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
