### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Google App Engine with Python using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#359]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Google App Engine](https://cloud.google.com/).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by saxenanurag** [comment]
Hi! I am interested in submitting in example. But, how will it be different from the GAE documentation: https://cloud.google.com/appengine/docs/standard/python/mail/sendgrid
?

**Comment by thinkingserious** [comment]
HI @saxenanurag,

It could be that it is very similar or that we simply reference that tutorial from this repo.

Thanks!

With Best Regards,

Elmer

**Comment by saxenanurag** [comment]
So, should I work on this?

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
