### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Microsoft Azure with Python using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#360]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Microsoft Azure](https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-local-git).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by yashasvisharma** [comment]
I'll start working on it

**Comment by tonytran** [comment]
Would this be as simple as creating a small flask app that is a single page app and through some interaction (like a clicking a send email button) it will send an email. Maybe even having the user fill out a form for them to specify the email they'd want to to send to?

**Comment by jaykay12** [comment]
@thinkingserious Kindly have a look at https://demo-sendgrid.azurewebsites.net/

I have started writing documentation of the deployment and will shortly make a PR.

**Comment by eshanholtz** [comment]
Closing this issue as the v4 branch is no longer being maintained.
