### ISSUE TITLE
Create a tutorial to create a Slack event integration with Python using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#362]
Create a tutorial that explains how to create a simple [integration with Slack](https://api.slack.com/events-api) that allows an email to be triggered based on some [defined event](https://api.slack.com/events).

The example should utilize best practices for storing credentials.

Please add the tutorial to USE_CASES.md.

**Comment by navinpai** [comment]
Hey I'd like to take this up!

**Comment by thinkingserious** [comment]
Thank you @navinpai!
