### ISSUE TITLE
TravisCI is failing on a dependency

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#368]
#### Issue Summary

It looks like there may be a dependency issue that needs to be resolved. In the logs, there is a deprecation warning. 

#### Steps to Reproduce

1. Make a PR
2. Wait
3. Travis fails, click Details
4. Click the red box and get the error `python setup.py install failed and exited with 1` 

> Installed /tmp/easy_install-xVxFSM/unittest2-1.1.0/.eggs/traceback2-1.4.0-py2.6.egg
> Searching for linecache2
> Reading https://pypi.python.org/simple/linecache2/
> Downloading https://pypi.python.org/packages/44/b0/963c352372c242f9e40db02bbc6a39ae51bde15dddee8523fe4aca94a97e/linecache2-1.0.0.tar.gz#md5=7b25d0289ec36bff1f9e63c4329ce65c
> Best match: linecache2 1.0.0
> Processing linecache2-1.0.0.tar.gz
> Writing /tmp/easy_install-xVxFSM/unittest2-1.1.0/temp/easy_install-X88hlg/linecache2-1.0.0/setup.cfg
> Running linecache2-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xVxFSM/unittest2-1.1.0/temp/easy_install-X88hlg/linecache2-1.0.0/egg-dist-tmp-Y4r0ft
> /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/dist.py:26: DeprecationWarning: Do not call this function
>   warnings.warn("Do not call this function", DeprecationWarning)
> ERROR:root:Error parsing

**Comment by cmccandless** [comment]
It seems the issue only exists when building for Python2.6. As that version of Python is no longer supported by the Python team, is simply dropping Python2.6 support an option?

Alternatively, I seem to have found a hack that builds just fine, but only if you can force Python2.6 to use pip 1.5.4 (Python2.7).

**Comment by mbernier** [comment]
@thinkingserious Thoughts on dropping Python2.6?

**Comment by denvera** [comment]
Created PR #376 as a workaround to get the build to succeed for Python 2.6

**Comment by cmccandless** [comment]
I think @denvera 's solution is better than dropping support entirely. I will close my existing PR.
