### ISSUE TITLE
Add How to Setup a Domain Whitelabel and How to View Email Statistics to USE_CASES.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#383]
Please see [this](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#how-to-setup-a-domain-whitelabel) for an example.

**Comment by adityatandon007** [comment]
@thinkingserious taking this

**Comment by thinkingserious** [comment]
Thank you!

**Comment by Sidsharik** [comment]
Would love to contribute to this
