### ISSUE TITLE
Prevent secrets from sending in email

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#388]
Add a method that will check the content of the email before sending, to make sure that specific strings or patterns are not included.
For example, SG API keys look like this: SG.[a-zA-Z0-9_].[a-zA-Z0-9\-]
So the function could take a list of regex or specific strings to compare against. If a string is found, the mail/send should throw an exception

**Comment by soumya-ranjan7** [comment]
Can I work on this?

**Comment by thinkingserious** [comment]
Thanks @soumya-ranjan7!

**Comment by dsouzarc** [comment]
@thinkingserious I started working on it and left some comments [here](https://github.com/sendgrid/sendgrid-python/pull/452).

I'm looking for some feedback on my approach to fix [Issue 388](https://github.com/sendgrid/sendgrid-python/issues/388)

I'm not sure where to actually call the `validate_for_api_key()` but I'm thinking of doing it in the `Content` class whenever a `value` is added (see [here](https://github.com/sendgrid/sendgrid-python/blob/ae54113443032a26c1505af870207a6789ac0b58/sendgrid/helpers/mail/mail.py#L323)

**Comment by dsouzarc** [comment]
Fixed this issue in [this Pull Request](https://github.com/sendgrid/sendgrid-python/pull/534) as the complete structure of the project changed
