### ISSUE TITLE
Tests for app.py

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#418]
#### Issue Summary

CodeCov is showing that we're missing some testing on app.py. 
[Please see their page and add some tests](https://codecov.io/gh/sendgrid/sendgrid-python/compare/db608f74fbbb4b1d4d71c644da9614de6ed900e3...86abbc199800fefe9114cab7535d28a8114cca78/src/sendgrid/helpers/inbound/app.py)

**Comment by obernardovieira** [comment]
I'd like to give it a try, since I've done tests before.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-python/pull/433
