### ISSUE TITLE
Add Tests for sendgrid.py

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#419]
#### Issue Summary

CodeCov is showing that we're missing some testing on sendgrid.py. 
[Please see their page and add some tests](https://codecov.io/gh/sendgrid/sendgrid-python/compare/db608f74fbbb4b1d4d71c644da9614de6ed900e3...86abbc199800fefe9114cab7535d28a8114cca78/src/sendgrid/sendgrid.py)

**Comment by lafentres** [comment]
I'd like to try this.

**Comment by lafentres** [comment]
I'd like to try this one.
