### ISSUE TITLE
Repair Docker Build

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#426]
Please see: https://hub.docker.com/r/sendgrid/sendgrid-python/builds/bzvwzufztt652fqrebrxfgq

**Comment by jmweir** [comment]
Taking a look

**Comment by wspi** [comment]
I built it on a local machine, and it passed without a change, is it still failing?

**Comment by gabrielkrell** [comment]
@wspi I think this one is an intermittent bug.  See [this silly thread](https://github.com/moby/moby/issues/9547).

**Comment by mbernier** [comment]
Thanks @gabrielkrell!!
