### ISSUE TITLE
Getting UnsupportedMediaTypeError when running a simple example

### ISSUE THREAD

**Issue by yusun0715** [sendgrid/sendgrid-python#439]
Hi Guys,

I tried to follow a simple example in this repository but kept getting UnsupportedMediaTypeError:

setting up my own sendgrid object:
```
self.sg = sendgrid.SendGridAPIClient(
       apikey=my_own_key
)
```

```
data = {
            "personalizations": [
                {
                    "to": [
                        {
                            "email": "test@example.com"
                        }
                    ],
                    "subject": "Sending with SendGrid is Fun"
                }
            ],
            "from": {
                "email": "test@example.com"
            },
            "content": [
                {
                    "type": "text/plain",
                    "value": "and easy to do anywhere, even with Python"
                }
            ]
        }
response = self.sg.client.mail.send.post(request=data)
```
At this point, I am getting UnsupportedMediaTypeError. And I tried to send the same data in a rest client using my key, and it worked. 

Python: 2.7.10
Sendgrid_python: 5.3.0
Python-http-client: 3.0.0

Could you please take a look at this? Thank you

**Comment by zgoda** [comment]
It should be `request_body`, not just `request` - that's the right name of this arg (last line of your code).

**Comment by yusun0715** [comment]
@zgoda  thank you so much for spotting this! Now it works perfectly fine. I drove me nuts this morning

**Comment by mbernier** [comment]
Thank you @zgoda!!
