### ISSUE TITLE
Create a PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#445]
#### Issue Summary

We would like to have a template for describing what has changed in the pull request being submitted.

[Github docs on this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) 

You can use [this file](https://github.com/sendgrid/open-source-library-data-collector/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example

**Comment by Nisinghal** [comment]
Hi. I would like to work on this. Could you assign this to me?
