### ISSUE TITLE
Add a USAGE.md file

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#448]
Usage files are really nice when they exist in a repo, because it makes it really obvious where to look for information about how to use this tool. It can be frustrating when you expect this file to be there and it's not. 
Please add a USAGE.md file, you can see an example of this 
[here](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)

Please make sure you modify the file for this repo (hint: Most of this information should be in the README file)

**Comment by mbernier** [comment]
dupe
