### ISSUE TITLE
Fix "method_complexity" issue in sendgrid/helpers/mail/mail.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#457]
Function `get` has a Cognitive Complexity of 23 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py#issue_59f2b5d6a7918a0001000059

**Comment by Prashant-Surya** [comment]
Can I take this up?
