### ISSUE TITLE
Fix "file_lines" issue in sendgrid/helpers/mail/mail.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#459]
File `mail.py` has 979 lines of code (exceeds 250 allowed). Consider refactoring.

Move the classes to different files so that the files are easier to read and manage.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py#issue_59f2b5d6a7918a0001000058

**Comment by runz0rd** [comment]
Taken :)
