### ISSUE TITLE
Fix "method_lines" issue in examples/helpers/mail/mail_example.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#460]
Function `build_kitchen_sink` has 79 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/examples/helpers/mail/mail_example.py#issue_59f2b5d5a7918a0001000054

**Comment by suprithIUB** [comment]
I'll take this. I'll send a pr in few hours.
