### ISSUE TITLE
Fix "method_count" issue in sendgrid/helpers/mail/mail.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#461]
`Personalization` has 24 functions (exceeds 20 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py#issue_59f2b5d6a7918a000100005e

**Comment by prashuchaudhary** [comment]
@thinkingserious I want to take a chance at this. But how to proceed. All the methods defined in Personalization class are valid functions ??

**Comment by thinkingserious** [comment]
It's all yours @themousepotato, thanks!

**Comment by themousepotato** [comment]
@thinkingserious I'll be fixing the major issue soon. I tried two fix two of the issues mentioned in the given link and refactored the code. Please let me know your opinions on https://github.com/sendgrid/sendgrid-python/pull/625.

**Comment by thinkingserious** [comment]
Hi @themousepotato!

Can you please make this PR against [this branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thanks!

With Best Regards,

Elmer
