### ISSUE TITLE
Pep8 Compliance

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#464]
#### Issue Summary
According to this report, there are a lot of Pep8 issues. Can you fix them? 

https://codeclimate.com/github/sendgrid/sendgrid-python/pull/463

#### Acceptance criteria: 
Code climate should pass when you make your PR.

**Comment by blackpioter** [comment]
I'll take it @mbernier

**Comment by blackpioter** [comment]
BTW. Please consider ignoring PEP8 E501 (line too long). There are parts of code with i.e links that will be hard to shorten.

**Comment by mbernier** [comment]
That makes sense to me.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-python/pull/466
