### ISSUE TITLE
Add a unittest to check the license.md file date range

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#474]
The end year in the license file should be "this year" and this should be checked on every run of the tests. If the end year is no correct, fail the test.
example: 
> Copyright (c) 2012-2016 SendGrid, Inc.
It is 2017, so this should be:
> Copyright (c) 2012-2017 SendGrid, Inc.
and the  test should fail.
--done

**Comment by nishithshah2211** [comment]
Hey, I'd like to work on this. I am already working on the same issue in the `smtpapi-python` repo. Should I go ahead with using regex to parse  for the year or does anyone want to suggest a better way to do it?

Also, the license file is license.txt and not license.md right?
