### ISSUE TITLE
The biggest issue the unresponsive and irresponsible moderators like @thinkingserious  @mbernier

### ISSUE THREAD

**Issue by codervikash** [sendgrid/sendgrid-python#511]
#### Issue Summary

The biggest issue this repo has is unresponsive moderators. I understand they have to manage a lot of PR but still they don't have the courtesy to reply to comments and manage PR. 

I see a lot of people just coping others PR's changes to theirs and getting it merged. Do you guys really want people to contribute to your repo? I have this PR( #493  ) for two days and have pinged multiple times on issue and PR to code review or merge and I see no reply but other PRs are being merged and here I am back merging and resolving conflicts. Don't you guys have the courtesy to reply at least?

People like you and these shitty repos demotivate open source contributors. Don't be an ass! To hell with your hacktoberfest.

There are many popular and first-timer friendly repos on GitHub. Just add this in yours contributing guideline that we behave like this and don't have respect for others time. People will not bother wasting time here.

**Comment by mbernier** [comment]
We have had a ton of questions about what's going on, so we wrote up a response and tagged everyone with open Pull Requests at the time of posting!

https://github.com/sendgrid/sendgrid-python/issues/521
