### ISSUE TITLE
Add Code Review to Contributing.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#525]
- Add a "Code Reviews" section on CONTRIBUTING.md
- Put the following under the header:
> If you can, please look at open PRs and review them. Give feedback and help us merge these PRs much faster! If you don't know how, Github has some great [information on how to review a Pull Request](https://help.github.com/articles/about-pull-request-reviews/).
- Link the header in the Contributing.md Table of Contents
- Add a link to the README.md file: [Review Pull Requests]("CONTRIBUTING.md#Code-Reviews") under "Contributing Section"

**Comment by shorrock** [comment]
I'd like to take this and https://github.com/sendgrid/smtpapi-python/issues/59 please!

**Comment by jlax47** [comment]
I created a pull request to address this #526
