### ISSUE TITLE
attachment.py file missing when installed using pip

### ISSUE THREAD

**Issue by ShareinSK** [sendgrid/sendgrid-python#541]
I am working on a windows machine. I have installed sendgrid in virtualenv.

When trying to attach pdf files I am getting 400 error, stating Attachment has no attribute set_content.

When checking the installed sendgrid folder there is no attachment.py file. There is only '__init__.py' and 'mail.py' file. 

E-mail sending is working correctly the problem is only with attachment.

![capture](https://user-images.githubusercontent.com/11828635/33134716-7debf166-cfc6-11e7-9cce-955ca6d04455.JPG)

#### Steps to Reproduce

1. virtualenv Env
2. pip install sendgrid

* Python Version: 3.x

Do I have to download the project from github and use locally?

**Comment by mbernier** [comment]
@ShareinSK 

From the [kitchen sink example](https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py#L82), it looks like you can do the following:

```python
import base64
import os 

# create an attachment object
attachment = Attachment()

# get the file you want to attach and base64 the content

with open("yourfile.ext", "rb") as file_to_attach:
encoded_string = base64.b64encode(file_to_attach.read())

# add this base64 string to the object
attachment.content = encoded_string

# change this to your file's type here e.g. "application/pdf"
attachment.type = "application/pdf"

# this will get the file name itself, from your file system
attachment.filename = os.path.basename(file_to_attach)

# leave this for attached files, otherwise [see the RFC ](https://www.ietf.org/rfc/rfc1806.txt) 
#   for other options
attachment.disposition = "attachment"

# this is only used if you are inserting an image into the email itself, other wise it shouldn't be required
# attachment.content_id = 

# add the attachment to your mail/send object
mail.add_attachment(attachment)
```
