### ISSUE TITLE
Docker build was fixed in PR #430, but versions >5.2.1 haven't been uploaded

### ISSUE THREAD

**Issue by gabrielkrell** [sendgrid/sendgrid-python#544]
#### Issue Summary

A weird bug was discovered in #426 and fixed in #430, but in the meantime builds for 4.2.1 and 4.3.0 failed.  Is it possible to backport #430 to the old tags and then re-upload to Docker Hub?

#### Steps to Reproduce

(See the [builds page](https://hub.docker.com/r/sendgrid/sendgrid-python/builds/).)

#### Technical details:

The rest of the builds were fine, but Docker was broken in builds 4.2.1 and 4.3.0.  To get them up, you could:
 - Merge #430 into those releases and re-tag (or increment) to trigger the build.  This would also send out release notifications.
 - Check out those tags, manually make the change, and manually upload to Docker Hub.  Probably the cleanest.

#### Nontechnical details:

Happy New Year!

**Comment by thinkingserious** [comment]
Thanks @gabrielkrell! On the backlog ;)

Happy New Year!

**Comment by gabrielkrell** [comment]
Same to you!

**Comment by gabrielkrell** [comment]
Hey @thinkingserious, I've been fine!  Same to you; hope all are happy at Sendgrid :).  I'll take a look, but it may be a while until I get to it - lots on the backlog right now.

 - Gabe

**Comment by thinkingserious** [comment]
Thanks!

I hope a full backlog means that you are having a great time :)

**Comment by Warlord77** [comment]
Any one working on this ? @gabrielkrell can you just guide me how to fix this ?

**Comment by thinkingserious** [comment]
I am about to look into this one, but before I do, are you already working on this @Warlord77?

**Comment by childish-sambino** [comment]
Closing this out as the root-level Dockerfile is now functioning properly.

**Comment by jonodrew** [comment]
I seem to be having issues - I think this line requires a folder that's not in the repo. https://github.com/sendgrid/sendgrid-python/blob/50d50d240719a4abb392b8d758ac606f7a1b9aa0/Dockerfile#L6  

I can't find a guide to using Docker on the repo either - all the links seem to be broken.

**Comment by childish-sambino** [comment]
@jonodrew This should help: https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#testing

Which links are broken?

**Comment by jonodrew** [comment]
In https://github.com/sendgrid/sendgrid-python/blob/master/FIRST_TIMERS.md#setting-up-the-development-environment, the link to USAGE.md is broken. With that being said, I then looked at that file and it seemed to be a guide to the API rather than how to set up the container?

With that being said, once I'd run `make test-docker` the Docker file build itself without any issues on `docker build .`

**Comment by gabrielkrell** [comment]
Looks like the language there was copied from the old CONTRIBUTING.md (and would have been referencing the [old Docker usage file](https://github.com/sendgrid/sendgrid-python/blob/67289467bd56073fba261faac347b5c96b1a0156/docker/USAGE.md)). The `docker/` folder was removed in 91f4cd89aef7e4856706791c99cde460d26011af. Now that you mention it the Docker link at the top of the main README is also broken (that "new" section should be removed anyway, it's from 2017).

**Comment by childish-sambino** [comment]
Old links have now been removed.
