### ISSUE TITLE
for the love of god make it clear in the docs to base64 encode data before passing to attachment function

### ISSUE THREAD

**Issue by carnal0wnage** [sendgrid/sendgrid-python#547]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: X.X

**Comment by thinkingserious** [comment]
@carnal0wnage,

Thanks for the heads up! Which docs were you looking at?

With Best Regards,

Elmer

**Comment by carnal0wnage** [comment]
hey sorry for the frustration issue post. I've been looking at the docs in this repo specifically

https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail/mail_example.py line 82

which makes sense that it's b64 encode after you know it but wasnt clear to me at first that it needed to be.  Even making a comment in the code to pass a b64 encode blob to the attachment.content piece would probably help someone out later.

**Comment by thinkingserious** [comment]
Hi @carnal0wnage,

No worries, I view frustration posts as an opportunity to be better :) I'm glad you took the time to respond. I'm going to re-open this, so we can fix that documentation.

Here is where I would have hoped you [would look](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md#attachment). We clearly have to do better with guiding people to the appropriate documentation. Do you mind sharing the path you took that landed you to the example above?

Thanks!

**Comment by carnal0wnage** [comment]
yup that would have saved me some time. not sure how i missed it and ended up on that other example. thanks tons

**Comment by thinkingserious** [comment]
Ah nice, thanks for the follow up @carnal0wnage!
