### ISSUE TITLE
API not accepting posts >8K bytes despite docs claiming up 10K bytes.

### ISSUE THREAD

**Issue by ItsJustChad** [sendgrid/sendgrid-python#548]
#### Issue Summary

I'm working with a personalization substitution that uses HTML mark up for a table and can get large fairly quickly. When the total mail.get() size is under approximately 8,000 bytes (UTF8), it sends fine. But if it is over 8,000 bytes, I get a 400 Bad Request. [API documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) says it has to be below 10K bytes.

#### Steps to Reproduce
I haven't figured out the exact length of the string that is breaking the send, but it is close to 8K. Figured this out by removing all HTML tags and slowly adding back in, finding that the <td></td> tags broke it.

Error doesn't say that it is too long (something like 419), just that it is a bad request (400).

I've verified that everything else is fine and that the only thing that changes is the length of the string that gets substituted in the personalization section.

```
def personalize(html):
  personalization = Personalization()
  personalization.add_substitution(Substitution("-List-",html))
  personalization.add_to(Email("test@example.com"))
  return personalization

def main():
  html = create_content()
  //html creates a string that has the HTML which renders fine like this:
  //html="<table><tr><th>Domain</th><th>Title</th></tr><tr><td>example.com</td><td>Hi</td></tr> ... </table>
  if html is not False:
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
    mail = Mail()
    mail.from_email = Email("sender@example.com","Sender")
    mail.template_id = "valid-transactional-template-id"
    mail.add_personalization(personalize(html))

    try:
      response = sg.client.mail.send.post(request_body=mail.get())
    except urllib.error.HTTPError as e:
      print(e.read())
```

#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @ItsJustChad,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by ItsJustChad** [comment]
Thank you. I submitted a request. For the record, I managed to use CURL successfully with more than 8K bytes in the substitution field, so I'm not sure what is going on.

**Comment by thinkingserious** [comment]
Thanks @ItsJustChad!
