### ISSUE TITLE
Personalization Substitutions Fail with certain keys

### ISSUE THREAD

**Issue by logannc** [sendgrid/sendgrid-python#550]
#### Issue Summary

Personalization Substitutions seem to have additional, undocumented restrictions. 

This may be the wrong venue as this does not appear to be a bug in the module, rather a bug in Sendgrid's processing layer or an undocumented restriction that the library fails to protect us from.

Specifically, keys of the form `<%sometext%>` seem to not work while keys of the form `%sometext%` appear to.

#### Steps to Reproduce
```
from sendgrid.helpers.mail import Mail, Email, Content, Personalization, Substitution
import sendgrid
m = Mail()
m.from_email = Email('somefrom@address.com', 'Notifications or Something')
m.subject = 'Test Substitution'
m.add_content(Content('text/plain', 'This is my <%sub%> stuff.'))
ps = Personalization()
ps.add_to(Email('logan@mysite.com'))
ps.add_substitution(Substitution('<%sub%>', 'personalized'))
m.add_personalization(ps)
body = m.get()
body
{'personalizations': [{'substitutions': {'<%sub%>': 'personalized'}, 'to': [{'email': 'logan@mysite.com'}]}], 'subject': 'Test Substitution', 'from': {'email': 'somefrom@address.com', 'name': 'Notifications or Something'}, 'content': [{'type': 'text/plain', 'value': 'This is my <%sub%> stuff.'}]}
sg = sendgrid.SendGridAPIClient(apikey=apikey)
res = sg.client.mail.send.post(request_body=body)
res.status_code # 202
# I receive the above email with the substitutions unapplied. I receive the raw text.
# I receive the below email with the substitutions applied correctly. i.e., '<personalized>' is in the email.
body['personalizations'][0]['substitutions'] = {'%sub%' : 'personalized'}
res2 = sg.client.mail.send.post(request_body=body)
```

For additional clarity, the text of the first email:
```
This is my <%sub%> stuff.
```

and the second:
```
This is my <personalized> stuff.
```

#### Technical details:

* sendgrid-python 5.2.0
* Python Version: 3.5.3

**Comment by thinkingserious** [comment]
Hello @logannc,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
