### ISSUE TITLE
X-Message-ID is not the complete Message ID

### ISSUE THREAD

**Issue by dhruvg** [sendgrid/sendgrid-python#558]
#### Issue Summary

The `X-Message-ID` I get back from the V3 send API is something like `JQtrNr0IRR-slAi2eCUMSg`. However, when I see "Show Original" on my Gmail client, I see the `Message ID` as `<JQtrNr0IRR-slAi2eCUMSg@ismtpd0004p1iad1.sendgrid.net>`. The latter is useful if I want to send followup emails which show up in the same email thread as the first email (via the `In-Reply-To` and `References` email headers). But I cannot achieve that if I only have `JQtrNr0IRR-slAi2eCUMSg` to work with. How I can get the _full_ message ID?

#### Technical details:

* sendgrid-python Version: 3.6.3
* Python Version: 3.5.0

**Comment by ppruitt-sg** [comment]
Unfortunately there isn't a way to capture the full Message ID from the response, the X-Message-ID will always include just the first 22 characters of that Message ID, the rest of the information is appended to the ID after it has been accepted by SendGrid and before sending the message to the recipient. 

What you can do to correlate this info is use the [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Processed). The full Message ID that you would find in the email header on Gmail is posted as the `smtp-id` within the Event Webhook events.

**Comment by dhruvg** [comment]
Ah ha! Thanks.
