### ISSUE TITLE
UnauthorizedError: HTTP Error 401: Unauthorized error appears when sending e-mail

### ISSUE THREAD

**Issue by utkusen** [sendgrid/sendgrid-python#561]
#### Issue Summary
I can send e-mails with my api key by using curl with following examples: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/curl_examples.html

But when I try to send an e-mail with "Hello Mail/With Mail Helper Class" code, I get following error: 

```
Traceback (most recent call last):
  File "gridsend.py", line 11, in <module>
    response = sg.client.mail.send.post(request_body=mail.get())
  File "/usr/local/lib/python3.6/site-packages/python_http_client/client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "/usr/local/lib/python3.6/site-packages/python_http_client/client.py", line 161, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
```
#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 3.6

**Comment by utkusen** [comment]
Now I understand the issue. Example code contains this code `apikey=os.environ.get('SENDGRID_API_KEY')` what I understand from here, I just need to type my API key to here. However, it's the name of the environment variable. Documentation is not clear on this and it's very confusing. I suggest you to make this point clear for everyone. Cheers

**Comment by thinkingserious** [comment]
I have reopened this issue so that we can update the README to make this issue clearer.

Thanks @utkusen!

**Comment by bchandaka** [comment]
In addition to making that line clear in the python code, I think the README should also be updated with how to properly set the environment variable for the api key on windows. I found(after multiple attempts) that typing  `set SENDGRID_API_KEY=<insert_your_api_key>` into the cli works.

**Comment by thinkingserious** [comment]
Thank you @bchandaka!

If you don't mind and have the time, we are accepting PRs :)

**Comment by bchandaka** [comment]
My code worked with just the api key and I don't think I even got an api key password. Did you try printing the api key variable in the cli or in your python program to see if the variable is being read/set properly? 
@tollvam

**Comment by tollvam** [comment]
@bchandaka Yes i checked and the class  variable self.apikey is well set with my api key

**Comment by thinkingserious** [comment]
Hi @tollvam,

To confirm it's not an API Key issue, please try making the call [here](https://sendgrid.com/docs/API_Reference/api_v3.html) with your API Key.

Thanks!

With Best Regards,


Elmer

**Comment by tollvam** [comment]
Hi @thinkingserious, thanks for the link. It says "The provided authorization grant is invalid, expired, or revoked" so i have to regenerate one ? thanks

**Comment by thinkingserious** [comment]
Hello @tollvam,

Yes, that is what I would try.

Thanks!

With Best Regards, 

Elmer

**Comment by tollvam** [comment]
Just to be sure, do i have to put something in "Query String" on the page to test ?

**Comment by thinkingserious** [comment]
[Here](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/curl_examples.html#-Hello-World) is an even easier method to test your API Key.

**Comment by sr9yar** [comment]
OMG, I just quickly copy-pasted this example to test if my set-up works, then I spent 40 minutes trying to understand what's wrong with my account .... :(
gotta call it today

**Comment by JoeKhoa** [comment]
I think that this is because  window os. 
![image](https://user-images.githubusercontent.com/50235118/78678582-596ee200-7913-11ea-9034-1193357863de.png)

refer this https://github.com/sendgrid/sendgrid-python

**Comment by MuhammadSufyanMalik** [comment]
Hi, I am still facing a 401 error from my python code. I have checked my environment variable is set properly as well.
What should I do ?? :(

**Comment by childish-sambino** [comment]
@MuhammadSufyanMalik Try logging the error response body to get more details about why it's failing: `print(e.body)`
