### ISSUE TITLE
content formatting with \n 

### ISSUE THREAD

**Issue by qaturner** [sendgrid/sendgrid-python#563]
#### Issue Summary

setting content with a value of 
      'something\nsomething' 
will not format correctly where as 
      'something\n something' 
will format correctly in the received email.

#### Steps to Reproduce

1, Set up a mail object assigning the content as follows: 
         content=Content('text/plain','something\nsomething')
2. Send mail

I was creating an email whose contents is created by concatenating a string from popping off a list variable.  I spent a lot of time comparing the difference of when I hardcoded the value of content versus using my code.  Only after viewing debug printing of the content body was I able to discern this subtlety.

#### Technical details:

* sendgrid-python Version: 5.3.0 
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @qaturner,

I'm not sure if this is a library or API issue. I have added this to our backlog for further investigation. Thanks for bringing this to our attention!

With Best Regards,

Elmer

**Comment by meahow** [comment]
I am investigating this as part of the Hacktoberfest fun.

**Comment by meahow** [comment]
It seems that this is an API/backend issue. This is what I get when sending those to cases mentioned by qaturner:
- the one with correct formarting
```
Content-type: multipart/alternative; boundary="----------=_1538496091-12812-69"
------------=_1538496091-12812-69
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

this is good
 case
------------=_1538496091-12812-69
Content-Type: text/html; charset="UTF-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

<html><body>
<p>this is good</p>
<pre>case</pre>
------------=_1538496091-12812-69--
```
- the one with incorrect formarting:
```
Content-type: multipart/alternative; boundary="----------=_1538496076-20484-861"

------------=_1538496076-20484-861
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

this is bad
case
------------=_1538496076-20484-861
Content-Type: text/html; charset="UTF-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

<html><body>
<p>this is bad case</p>

</body></html>

------------=_1538496076-20484-861--
```

So it looks like the html alternative gets incorrect newline.
I am not ure if there is anything more I can do. If so, please give me some hints

**Comment by meahow** [comment]
@kylearoberts 
Just to be clear, I did not bring this issue up, I just investigated it :)

Anyway.
How I reproduced it is I ran the very simplest example for sendgrid in python.
It sends this json to the server (at least this is what I get from `sendgrid.helpers.mail.Mail.get()` ):
```json
{"content": [{"type": "text/plain", "value": "this is bad\ncase"}],
 "from": {"email": "hacktoberfest@sengrid.com"},
 "personalizations": [{"to": [{"email": "hacktoberfest@gmail.com"}]}],
 "subject": "sendgrida test"}```

But... when I was trying to reproduce it for the sake of this message, I was not able to repeat that same issue again.
So maybe you fixed it already ? :)
@qaturner Can you verify that ?

**Comment by kylearoberts** [comment]
@meahow 

Sorry for my confusion and thank you for your help with the issue.

@qaturner 

Are you still able to create this issue? If so please let us know with details of how so we can replicate the issue and get it to our engineers.
