### ISSUE TITLE
Enhancement request for examples/helpers/mail/mail_example.py

### ISSUE THREAD

**Issue by lohriialo** [sendgrid/sendgrid-python#566]
Would be so much more helpful for someone new to Sengrid if you can put in a Readme at `examples/helpers/mail` and explain what `mail_example.py` does. Comments in the example code isn't very helpful

**Comment by thinkingserious** [comment]
Great idea @lohriialo,

I've added this to our backlog and opened it up to the community for a PR.

Thanks!

With Best Regards,

Elmer

**Comment by thebrahminator** [comment]
Hey, I'll take this up.

**Comment by thinkingserious** [comment]
Thank you @thebrahminator!

**Comment by vipulgupta2048** [comment]
@thebrahminator Are you still working on this?

**Comment by tulikavijay** [comment]
No one seems to be working on this ,so i will be submitting a PR for review shortly!
