### ISSUE TITLE
A problem with a request.

### ISSUE THREAD

**Issue by artofkot** [sendgrid/sendgrid-python#568]
#### Issue Summary

Could you please point out to me what is wrong with my get request below?  Thank you in advance! This issue is very similar to [this one](https://github.com/sendgrid/sendgrid-python/issues/346).

#### Steps to Reproduce

my code: (took it from [here](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#stats))
`sg = sendgrid.SendGridAPIClient(apikey=current_app.config['SENDGRID_APIKEY'])`
`d=time.strftime("%Y-%m-%d")`
`params = {'aggregated_by': 'day', 'limit': 1, 'start_date': d, 'end_date': d, 'offset': 1}`
`response = sg.client.stats.get(query_params=params)`

raises:
> .../python_http_client/client.py", line 161, in _make_request: raise exc

#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 2.7

**Comment by artofkot** [comment]
Hi @thinkingserious,

Many thanks for your comment. I already achieved my goal through a different path, so I no longer really need to understand this error. Please go ahead and close this issue.

Best,
Artem

**Comment by thinkingserious** [comment]
Thanks for the update @artofkot!
