### ISSUE TITLE
Mail helper docstring is wrong

### ISSUE THREAD

**Issue by onecrayon** [sendgrid/sendgrid-python#569]
#### Issue Summary

The Mail helper docstring claims that all of its arguments are optional. However, if you fail to pass one of them then none of them are saved (it's all or nothing):

https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L44

This was a major annoyance to debug (kept getting 400 Bad Request errors because the "from" and "to" emails were getting silently discarded since I was using explicit `add_content` calls to populate both plain text and HTML content after initializing the Mail object).

My preference would be to have anything passed into the Mail helper populate its internal variables, thus making the docstring correct. Alternately, adjusting the docstring to make it clear the arguments are all or nothing would be very much appreciated.

#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 3.6.5

**Comment by thinkingserious** [comment]
Hi @onecrayon,

Thanks for the heads up! In the short term, I think we should fix the docstrings. I'm adding this to our backlog, but feel free to submit a PR if you like.

In the [next version](https://github.com/sendgrid/sendgrid-python/issues/347), we will make these optional. If you have any feedback on the next version, we would love to have it :)

With Best Regards,

Elmer
