### ISSUE TITLE
Feature request: Support for sending email.message.EmailMessage

### ISSUE THREAD

**Issue by brettlangdon** [sendgrid/sendgrid-python#571]
I am working on integrating SendGrid into an application where I already have email messages as [email.message.EmailMessage](https://docs.python.org/3.6/library/email.message.html#email.message.EmailMessage), it would be really awesome if there was a way for me to send an `EmailMessage` directly rather than having to reconstruct .

**Comment by thinkingserious** [comment]
Great idea @brettlangdon, thanks for creating the issue!
