### ISSUE TITLE
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by JohnnyQQQ** [sendgrid/sendgrid-python#580]
I've gone through nearly everything on the help pages here but I'm still getting an HTTP Error 401: Unauthorized error.

I have created about 4 new api's and different configurations but still the same error

This is a new account and was hoping to use sendgrid for email.

I've done the curl examples and everything runs fine.

The code is directly from sendgrid:

import sendgrid
import os
from sendgrid.helpers.mail import *

SENDGRID_API_KEY = '***sendgrid***api***'

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get(SENDGRID_API_KEY))
from_email = Email("john@johnquirke.com")
to_email = Email("mullinahone@gmail.com")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "and easy to do anywhere, even with Python")
mail = Mail(from_email, subject, to_email, content)
response = sg.client.mail.send.post(request_body=mail.get())
print(response.status_code)
print(response.body)
print(response.headers)

**Comment by thinkingserious** [comment]
Hello @JohnnyQQQ,

This line: `SENDGRID_API_KEY = '***sendgrid***api***'` is not necessary. Your API Key should have been set in your environment like so: https://github.com/sendgrid/sendgrid-python#setup-environment-variables

The method `os.environ.get` gets the API key from the envoronment variable `SENDGRID_API_KEY`, but you have set `SENDGRID_API_KEY` directly. So when `os.environ.get` attempts to read the `SENDGRID_API_KEY` environment variable, it is empty, causing your API key to be blank and thus the 401 error.

With Best Regards,

Elmer

**Comment by JohnnyQQQ** [comment]
Thanks, I'm also on a windows system so I'll have to set up the path.

**Comment by stefangordon** [comment]
Not path, just `set SENDGRID_API_KEY xxxxx`

**Comment by JohnnyQQQ** [comment]
For some reason that didn't work, but once I set the environment variable it worked

**Comment by sakthips** [comment]
I'm getting this 401 Unauthorized exception. i did this environment stuff. I'm not able to debug this exception. In local it's working, when deployed in nginx+gunicorn that time i'm getting this exception.

**Comment by JairusLopes** [comment]
Hello,
I created the environment variable, with export.
And it worked.

**Comment by thinkingserious** [comment]
Hello @sakthips,

I suggest that you check the value of your SendGrid API Key in your deployed environment. I'm guessing the key is not getting set properly in the deployed environment.

With Best Regards,

Elmer

**Comment by Coder0111** [comment]
i facing having same error unauthorized 401 error  eve i have set enviroment variable  should give sendgrid api full access from my dashboard???

**Comment by Coder0111** [comment]
resp =sg.send(message)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sendgrid\sendgrid.py", line 95, in send
    response = self.client.mail.send.post(request_body=message.get())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\python_http_client\client.py", line 262, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\python_http_client\client.py", line 178, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized    
how to fix it

**Comment by childish-sambino** [comment]
@Coder0111 Please post some sample code that illustrates the issue. Are you reading the API key from an env var? If so, could you try logging the value to help debug if it's being set properly?

**Comment by Coder0111** [comment]
@childish-sambino my sendgrid details are correct though iam getting this may u help me for this
![Screenshot_20200330-224713](https://user-images.githubusercontent.com/53976052/77944646-bdbcf080-72d8-11ea-8d04-d58fcff1bbec.png)

**Comment by Coder0111** [comment]
actually its all cause of this

**Comment by childish-sambino** [comment]
@Coder0111 Submit a ticket here for login issues: https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by Coder0111** [comment]
![Screenshot_20200330-234601](https://user-images.githubusercontent.com/53976052/77949654-c4e7fc80-72e0-11ea-9c3e-66eab4a53ee0.png)
bro i did they relied me this as u can see in screen shot

**Comment by Coder0111** [comment]
is there another service in your mind who provide emailing api for free

**Comment by arycloud** [comment]
There's another solution works for me to overcome `HTTP Error 401: Unauthorized `. You can use `dotenv` package instead. Here are the steps:

1. `cd ~/my-project-dir`
2.  `echo "export SENDGRID_API_KEY=YOUR_KEY" >> .env`
3. `pip install python-dotenv` in your virtualenv
4. `echo python-dotenv >> requirements.txt`
5.  Add this to your WSGI file:
```
from dotenv import load_dotenv
project_folder = os.path.expanduser('~/my-project-dir')  # adjust as appropriate
load_dotenv(os.path.join(project_folder, '.env'))
```
6. Access your key as:  `SECRET_KEY = os.getenv("SECRET_KEY")`

**Comment by Coder0111** [comment]
@arycloud  bro i have been done it but still i am getting an error see in my comments i posted a screen shoot of sendgrid account they are not authorizing me to login in to my sendgrid account and when i sent them a mail what they replied me back i have post in comments see that error then let me know how to fix that error i think its all cause of that account error cause they are not letting me to login in my account

**Comment by Coder0111** [comment]
@arycloud see this bro wht they replied me https://github.com/sendgrid/sendgrid-python/issues/580#issuecomment-606175964
