### ISSUE TITLE
Attempting to set substitutions on Personalization helper causes infinite regress

### ISSUE THREAD

**Issue by richardnias** [sendgrid/sendgrid-python#582]
#### Issue Summary

Attempting to set substitutions on a `Personalization` helper directly (rather than with `add_substitution`) throws a `RecursionError`.

#### Steps to Reproduce

```python
from sendgrid.helpers.mail import Personalization
p = Personalization()
p.substitutions = [{'a': 0}, {'b': 1}]
```

This throws a `RecursionError`. The offending line is [personalization.py#L119](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/personalization.py#L119).

I will open a PR as this is an easy fix.

#### Technical details:

* sendgrid-python Version: `5.3.0`
* Python Version: 3.6

**Comment by richardnias** [comment]
Accidentally closed by merging a pr in my own fork, apologies, reopened.

**Comment by thinkingserious** [comment]
Thanks @richardnias! This is now on our backlog for a merge.
