### ISSUE TITLE
Wrong docstring for add_category

### ISSUE THREAD

**Issue by henrybetts** [sendgrid/sendgrid-python#587]
#### Issue Summary

The docstring for the add_category method in the mail helper claims that category is of type 'string', but it should actually be of type 'Category'.

https://github.com/sendgrid/sendgrid-python/blob/1ac58c6fc491554bc24573393ae6242e579dbabb/sendgrid/helpers/mail/mail.py#L381

This produces a warning in some editors when passing in a Category object.

#### Technical details:

* sendgrid-python Version: 5.4.1

**Comment by thinkingserious** [comment]
Thanks @henrybetts!

I have added this to our backlog. For this issue to gain priority in our backlog, we need additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

**Comment by thinkingserious** [comment]
Fixed with #595
