### ISSUE TITLE
Add Dynamic Template Support

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#591]
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#v3-mail-send). 

Now, we need to create helper code and examples for this SDK.

#### Acceptance Criteria

* [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transational_templates.md)
* Update the [transactional_templates.md](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transational_templates.md) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [Reference Implementation](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

**Comment by qgreg** [comment]
So I ended up starting my startup's transactional email project without knowing dynamic templating was new. While the management decision to make dynamic templating default when the SDK didn't support the new feature was questionable, with a bit of help from your support team, I wrote some code so I could use the SDK. Here's a Gist.

https://gist.github.com/qgreg/4ea19b0241b8b74b88011e36b2641c3a

The pieces & parts are there for a real update. I hope others can take what I wrote and run with it. Good luck!

**Comment by thinkingserious** [comment]
Thank you for your support @qgreg! 

Please follow [this link](https://dx.sendgrid.com/swag ) so that we can send you some SendGrid swag as a small token of our appreciation.

With Best Regards,

Elmer

**Comment by leebenson** [comment]
that's nice @qgreg.

But for anyone relying on the SDK to stay in sync with the API, I find that extending classes and monkey patching the internals is overkill.

A SendGrid API request is just JSON. Since `mail.get()` returns a dictionary object, you can apply new keys directly to it without the SDK abstractions.

For example - adding dynamic templates to an existing `Mail()` instance is as simple as this:

```py
# build the request
request = mail.get()

# attach whatever data you want directly...
request['dynamic_template_data'] = {
  'whatever': 'data you want'
}

# mail it out
sg.client.mail.send.post(request_body=request_body)
```

The SDK isn't doing anything magical. It's literally just building an internal dict, which is dumped to JSON via the call to `.send.post()`.

**Comment by Giaco9** [comment]
Do you have an ETA for either #593 or #591 to be released?

**Comment by thinkingserious** [comment]
Hello @Giaco9,

Those are next up in the backlog :) I'm currently building from #593.

**Comment by adriancast** [comment]
Hi ! I am not being able to find the documentation to add dynamic_template_data to the mail using this package. I only found how to configure the request body to accept dynamic data, [link](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/)

I want to use this package to create the request_body with the dynamic_template_data. Could you guys provide a snippet or some documentation please ? 

Thanks for your time

**Comment by leebenson** [comment]
@adriancast - does my snippet [above](https://github.com/sendgrid/sendgrid-python/issues/591#issuecomment-411730441) help?

**Comment by adriancast** [comment]
Hi @leebenson ,
Your snippet helped me a lot to understand how this python package works. But I wanted to use this client in order to build the request body.

I just checked this [commit](https://github.com/sendgrid/sendgrid-python/commit/68b9eb0a85b840ddc90345ca7b096e883a395694#diff-5212d0703ea8cbd464c94213312b909f) and I found the example of how to use this new feature.

Thanks for your time ! 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by thinkingserious** [comment]
HI @adriancast,

You may also find updated documentation [here](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transational_templates.md).

Thanks!

With Best Regards,

Elmer

**Comment by pavs94** [comment]
@thinkingserious The new documentation link gives 404

**Comment by vlad-tokarev** [comment]
@pavs94 I've found out that actual docs could be found here https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md

**Comment by parokshsaxena** [comment]
I tried using the same code as in the below link
https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md

But I am still getting 400 bad request error. I am using sendgrid==6.0.4. Any idea what could be the issue?

**Comment by parokshsaxena** [comment]
Got the issue. I have been using legacy templates. Using the transactional template solved the issue.
