### ISSUE TITLE
Requests being made to send email, but email is never received

### ISSUE THREAD

**Issue by DiscoMushroom** [sendgrid/sendgrid-python#594]
# Issue Summary

Hi, I'm using django 2 with python 3.5, the sendgrid web api (not smtp), and the [django-sendgrid-v5 package](https://github.com/sklarsa/django-sendgrid-v5) to try to send emails because my vps (digital ocean) blocks smtp emails for the first 60 days. Here's the settings.py, and a test function I'm running.

My domain host points to my vps on digital ocean. I also have all the MX and CNAME records verified with both my email host (fastmail), and sendgrid (in settings--> sender authentication). Everything has a green checkmark, no gray, red, or other questionable error indicators anywhere. I also have DKIM and DMARC records set properly on my digital ocean vps. I can also send email directly from my fastmail host through the browser or client (me@MY_DOMAIN.com), but not from my website.

Side note: This is my first time deploying anything and I'm not a pro, so I'm sorry if I missed some 'obvious' thing. I've been trying to debug this for the past 4 days now, going for about 10+ hours a day and I'm really aggravated. I fixed a bunch of errors from what I originally had, and finally got what you see below, but I'm lost on what's going wrong. Any help is extremely appreciated, even if it's along the lines of something obvious like "check your error logs", because I don't know where to find any error logs anywhere, if they even exist. So if there are some, I'd like to know where to check them. So the problem might be my lack of knowledge, but I don't know.

```
# settings.py
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# the following key is necessary for the django package
SENDGRID_API_KEY = 'SG.adjfgiyaud_a_very_long_string_different_from smtp_one_below'
EMAIL_HOST_USER = 'apikey'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # goes with ports 587 or 25
# EMAIL_USE_SSL = True  # goes with port 465

# I edit out the following two because I'm not using smtp, though I have uncommented them and the result is still the same.
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_PASSWORD = 'SG.guyfdakud_another_very_long_string_that_didnt_work_because_digitalocean_blocks_smtp_for_first60_days'


# views.py
import sendgrid
from sendgrid.helpers.mail import *
from .settings import SENDGRID_API_KEY
def email_test(request):
    sg = sendgrid.SendGridAPIClient(apikey=SENDGRID_API_KEY)
    from_email = Email("me@MY_DOMAIN.com")
    to_email = Email("my_personal_email@YAHOO.com")
    subject = "Subject of the email"
    content = Content("text/plain", "Body of the email.")
    mail = Mail(from_email, subject, to_email, content)
    response = sg.client.mail.send.post(request_body=mail.get())
    print(response.status_code)
    print(response.body)
    print(response.headers)
    return render(request, 'email_test.html')
```

And my urls.py file is set to mydomain.com/email_test

#### Steps to Reproduce

1. I log into my sendgrid account to check the total number of requests I have made to send emails this month at the bottom left of the screen. For example, it says 4 for this month.
2. I go to mydomain.com/email_test. The page loads fine with no errors.
3. I wait a minute and reload my sendgrid dashboard. It now says 5 email requests have been made.
4. I check my personal email in the browser and the spam folder, and nothing ever shows up. Ever. Not even 24+ hours later.
5. So I change my EMAIL_PORT in settings.py to 25, 2525, and 587: Doesn't work. I also enabled the EMAIL_USE_SSL setting to True and disabled the TLS one, then changed the port to 465, but nothing works.
6. I also tested if everything was working with telnt by following the directions [here.](https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html). The same thing as above happens. I'll get shown that another request was made to send an email, but nothing is ever received. Despite it showing at the end: "250 Ok: queued as VeYEQgLWT9ejt0Htp6C-Gg"

#### Technical details:

* sendgrid-python Version: 3.1.0
* Python Version: 3.5.2
* Django 2
* django-sendgrid-v5

**Comment by thinkingserious** [comment]
Hello @DiscoMushroom,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
