### ISSUE TITLE
Apostrophe in Subject Not Parsing Properly

### ISSUE THREAD

**Issue by JamesTheTerry** [sendgrid/sendgrid-python#602]
#### Issue Summary

I've been sending subjects with apostrophes and quotation marks and they've appeared with HTML encoding: `&quot;` and `&apos;`

I've tried encoding it straight strign, with utf_8 encoding, and with utf_8 encoding then decoded for unicode_escape.

When tried in the [API explorer](https://sendgrid.com/docs/API_Reference/api_v3.html) it worked fine, with the characters appearing as they should.

An example: `subject = "Test: \" Charle's - James\'s - chr: " + chr(39)` is received as:
`Test: &quot; Charle&apos;s - James&apos;s - chr: &apos;`

#### Steps to Reproduce

```
import sendgrid
from sendgrid.helpers.mail import *

SENDGRID_API_KEY = 'XXX'
sg = sendgrid.SendGridAPIClient(apikey=SENDGRID_API_KEY)
OUTGOING_EMAIL = 'sender@example.com'
OUTGOING_EMAIL_NAME = 'Mr Example'
SENDGRID_TEMPLATE_ID = 'TEMPLATE'

def sendEmail(to_email, subject, content):
    """ Sends email via sendgrid """
    data = {
        "personalizations": [
            {
                "to": [
                    {
                        "email": to_email
                    }
                ],
                "dynamic_template_data": {
                    "subject": subject,
                    "content": content
                },
            }
        ],
        "from": {
            "email": OUTGOING_EMAIL,
            "name": OUTGOING_EMAIL_NAME
        },
        "reply_to": {
            "email": "noreply@example.com",
            "name": "No Reply"
        },
        "template_id": SENDGRID_TEMPLATE_ID
    }

    response = sg.client.mail.send.post(request_body=data)
    print(response.status_code)
    print(response.body)
    print(response.headers)


# Test content goes here
to_email = 'me@example.com'
subject = "Test: \" Charle's - James\'s - chr: " + chr(39)
subject_utf8 = subject.encode("utf_8").decode("unicode_escape")
content = ["Just testing out apostrophes", "Without escape: ' here", 'With esacpe: \' here']

sendEmail(to_email, subject, content)
sendEmail(to_email, subject_utf8, content)
```

#### Technical details:

* sendgrid-python Version: 5.4.1
* Python Version: 2.7.10

**Comment by JamesTheTerry** [comment]
Update:

After further testing, I've found this appears to be an issue with `dynamic_template_data`'s interpretation of these characters, as passing in the subject line in normally in personalization works fine (see example below).

```
data = {
  "personalizations": [
    {
      "to": [
        {
          "email": "me@example.com"
        }
      ],
      "subject": "Sending with SendGrid is' \" Fun"
    }
  ],
  "from": {
    "email": "test@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "and easy to do anywhere, even with Python"
    }
  ]
}
```

My subject is being passed in as a handlebars variable into the subject line of my transactional template. This seems to be causing the issue.

**Comment by thinkingserious** [comment]
Hello @JamesTheTerry,

This issue should now be resolved, there a fix pushed out server side.

Please re-open if there are any further issues.

Thanks!

With Best Regards,

Elmer

**Comment by JamesTheTerry** [comment]
Hey just wanted to update this, the issue was fixed but there is still some user action that needs to be taken.

You need to triple curly brace your subject variable for it to parse as text instead of HTML so use something like `{{{subject}}}`

Thank you Chewie at Sendgrid support for letting me know about this.

**Comment by af4ro** [comment]
Hey @JamesTheTerry, do you think you could add it to the docs real quick? So that others can benefit from this information!

Thanks a lot for your support!

**Comment by JamesTheTerry** [comment]
@af4ro Probably not the most well written, but here you go: https://github.com/sendgrid/docs/pull/3878

**Comment by rossdargan** [comment]
This caught me out - thanks for adding the solution.
