### ISSUE TITLE
Fillable PDF form attachment corrupted

### ISSUE THREAD

**Issue by dishawagle** [sendgrid/sendgrid-python#606]
While I am able to send a PDF attachment,
when I try to open the attachment, it always says 'File may have been corrupted'
This is a fillable PDF form which I am trying to send.

Code:
```python
with open(file_path,'rb') as f:
			data=f.read()
			f.close()
		encoded=base64.b64encode(data).decode()
		attachment=Attachment()
		attachment.content = encoded
		attachment.type = "application/pdf"
		attachment.filename = file_path.split('/')[-1]
		attachment.disposition = "attachment"
		attachment.content_id = "Example Content ID"
                mail.add_attachment(attachment)
response = sg.client.mail.send.post(request_body=mail.get())
print(response.status_code)
```
'''
output: 202
'''
print(response.body)
'''
output:-
content: b''
content.length: 0
'''

* sendgrid-python Version: 5.3.1
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @dishawagle,

Please send the attachment to dx@sendgrid.com so that we may try to reproduce the error.

Thanks!

With Best Regards,

Elmer

**Comment by dishawagle** [comment]
@thinkingserious  [](url)
[Aetna_Claim_Form_Template.pdf](https://github.com/sendgrid/sendgrid-python/files/2318583/Aetna_Claim_Form_Template.pdf)

This is the pdf form I am trying to attach.

Thanks
Disha

**Comment by thinkingserious** [comment]
Hello @dishawagle,

I was not able to reproduce the issue. Using your attachment, I was able to receive it without corruption. Here is the code I used:

```python
import base64
import sendgrid
import os
from sendgrid.helpers.mail import Email, Content, Mail, Attachment
import urllib.request as urllib

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
from_email = Email("dx@sendgrid.com")
subject = "subject"
to_email = Email("elmer.thomas@sendgrid.com")
content = Content("text/html", "I'm a content example")
mail = Mail(from_email, subject, to_email, content)
file_path = "./aetna.pdf"

with open(file_path, 'rb') as f:
    data = f.read()
    f.close()
    encoded=base64.b64encode(data).decode()
    attachment=Attachment()
    attachment.content = encoded
    attachment.type = "application/pdf"
    attachment.filename = file_path.split('/')[-1]
    attachment.disposition = "attachment"
    attachment.content_id = "Example Content ID"
    mail.add_attachment(attachment)
response = sg.client.mail.send.post(request_body=mail.get())
print(response.status_code)
```

Please take a look and compare with your solution.

I am running Python 3.6.3

**Comment by Code-Crash** [comment]
Any update on this issue, I'm getting a similar issue in node.js, normal pdf is working but editable pdf is not working.

**Comment by thinkingserious** [comment]
Hello @Code-Crash,

I was not able to reproduce the issue on my end. If you like, please send the sample PDF to dx@sendgrid.com and I'll try to reproduce the error.

Thanks!

With Best Regards,

Elmer

**Comment by Code-Crash** [comment]
Hello @thinkingserious,

To give an update, on my case editable pdf is working as I did try with attached pdf on the same thread.

FYI, for my one of the client, I'm using PS-PDF-KIT (https://pspdfkit.com) to make pdf editable (or to create an editable pdf form), when I'm using that editable pdf, I'm facing the issue, I will send you the example pdf shorty.

Thanks.

**Comment by thinkingserious** [comment]
Thanks for the update @Code-Crash, I'll look for your email.

**Comment by thinkingserious** [comment]
Thanks for the update @Code-Crash, I'm glad things worked out!

Hello @dishawagle,

Perhaps you are having a similar issue? Could you please give it a try and let me know what you find?

Thanks!

With Best Regards,

Elmer

**Comment by Code-Crash** [comment]
@thinkingserious Yeah, thank you too. 👍

**Comment by thinkingserious** [comment]
Hello @dishawagle,

Just following up to see if you have resolved your issue. Thanks!
