### ISSUE TITLE
Custom_args not working in V3 but unique_args sends email but not in event_callback.

### ISSUE THREAD

**Issue by bishnusyangja** [sendgrid/sendgrid-python#608]
#### Issue Summary

I have used sendgrid v3 api for sending emails. As mentioned in documentation of V3 API I use custom_args to get my params in event callback but it shows 400 bad request, while I use unique_args, the email was sent but the event callback does not send my unique_args params.

#### Steps to Reproduce

1. data = {"content": [{"value": "dfafds", "type": "text/plain"}], "attachments": [{"content": "UEsDBB......QACAgIAAA=", "type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content_id": "BqzZqz7LaqO9", "filename": "Contactmanager-company.xlsx", "disposition": "attachment"}], "from": {"email": "bishnusyangja@gmail.com"}, "personalizations": [{"to": [{"email": "bishnu@janakitech.com"}], "custom_args": {"email_msg_id": 106}, "subject": "daff"}]}

2. callback data is 
[{"sg_event_id": "aoDNXRAeRuaCAVRiutD-fg",
  "sg_message_id": "epJqlw1JThGw--dDTC1oCQ.filter0099p3las1-8681-5B853F95-29.0",
  "smtp-id": "<epJqlw1JThGw--dDTC1oCQ@ismtpd0006p1maa1.sendgrid.net>",
  "timestamp": 1535459222,
  "email": "bishnu@janakitech.com",
  "event": "processed"}

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 3.3

**Comment by thinkingserious** [comment]
Hello @bishnusyangja,

Could you please let me know what the 400 bad request [error message](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/error_handling.md) is?

Thanks!

With Best Regards,

Elmer

**Comment by bishnusyangja** [comment]
No more information is given, while sendgrid sends bad-requests. I am amazed, 
"HTTP Error 400: Bad Request" this exception is raised while I am trying to send email with that data, you can check it by just removing attachments field from data I have posted in issue.

**Comment by thinkingserious** [comment]
Hello @bishnusyangja,

What is the result of `print(response.body)`?

Also, please try:

`"email_msg_id": "106"`

Thanks!

With Best Regards,

Elmer
