### ISSUE TITLE
python_http_client.exceptions.ForbiddenError

### ISSUE THREAD

**Issue by NikEyX** [sendgrid/sendgrid-python#609]
I am getting a **python_http_client.exceptions.ForbiddenError** doing even a simple request such as follows. This is taken directly from the examples. 

```
    params = {'page': 1, 'page_size': 1}
    response = sg.client.contactdb.recipients.get(query_params=params)
    print(response.status_code)
    print(response.body)
    print(response.headers)
```

It used to work for months until yesterday! Sending transactional emails still works and there are no problems with our billing.

Any idea what could cause this?

**Comment by thinkingserious** [comment]
Hello @NikEyX,

This looks to be a permissions issue with your API Key. I suggest you reach out to our [support team](https://support.sendgrid.com) so that they look into your account.

With Best Regards,

Elmer

**Comment by Cosi-Admin** [comment]
Or it could be that the sender is not authenticated. To authenticate the user
Settings > Sender Authentication.
Verify the email id & you should be able to send mails
