### ISSUE TITLE
if 5 addresses in to/cc/bcc items, each person get 5 emails

### ISSUE THREAD

**Issue by ytldsimage** [sendgrid/sendgrid-python#612]
#### Issue Summary

no error code, and emails were successfully delivered.

however, if there're 5 email addresses together in to/cc/bcc fields, each person received 5 duplicate emails.

#### Steps to Reproduce

1. This is the code

    def Email_st_by_Sendgrid(self,api_key, from_email, to_list, cc_list=[], bcc_list=[], subject='', content='', attachments=[]):

        import sendgrid
        import base64

        from sendgrid.helpers.mail import Email, Mail, Content, Attachment, Personalization
       

        sg = sendgrid.SendGridAPIClient(apikey=api_key)

        mail = Mail()
        mail.from_email = Email(from_email)
        mail.subject = subject
        personalization = Personalization()

        if to_list not in [[], '', None]:

            for to_addr in to_list:
                
                personalization.add_to(Email(to_addr))
                mail.add_personalization(personalization)

        if cc_list not in [[], '', None]:

            for cc_addr in cc_list:
                personalization.add_cc(Email(cc_addr))
                mail.add_personalization(personalization)

        if bcc_list not in [[], '', None]:

            for bcc_addr in bcc_list:
                personalization.add_bcc(Email(bcc_addr))
                mail.add_personalization(personalization)

        mail.add_content(Content("text/html", content))

        if attachments not in [[], '', None]:

            for file in attachments:
                data = open(file, "rb").read()

                encoded = base64.b64encode(data).decode()

                attachment = Attachment()
                attachment.content = encoded

                path, fName = Dir_File_Operation.get_new_file_Path_name(file)  #this is to get path and filename, not important here

                print(path, fName, fName.split('.')[-1])

                attachment.type = "application/{}".format(fName.split('.')[-1])
                attachment.filename = fName
                attachment.disposition = "attachment"  # "inline" 
                mail.add_attachment(attachment)

        response = sg.client.mail.send.post(request_body=mail.get())
        print(response.status_code)
        print(response.body)
        print(response.headers)

        print('SendGrid信封发送成功！')

        return response

2. This is the second step
     please add multi-addresses into to_list, cc_list or bcc_list

3. Further steps, etc.

Run.

#### Technical details:

* sendgrid-python Version: master ((3.1.0))
* Python Version:  3.6

Requirement already up-to-date: sendgrid in /anaconda/lib/python3.6/site-packages (5.6.0)
Requirement already satisfied, skipping upgrade: python-http-client>=3.0 in /anaconda/lib/python3.6/site-packages (from sendgrid) (3.1.0)

**Comment by ytldsimage** [comment]
Any suggestions?

**Comment by thinkingserious** [comment]
Hi @ytldsimage,

Could you please provide your [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body)? 

Thanks!

With Best Regards,

Elmer

**Comment by ytldsimage** [comment]
def Email_st_by_Sendgrid(self,api_key, from_email, to_list, cc_list=[], bcc_list=[], subject='', content='', attachments=[]):

 import sendgrid
 import base64

 from sendgrid.helpers.mail import Email, Mail, Content, Attachment, Personalization


 sg = sendgrid.SendGridAPIClient(apikey=api_key)

 mail = Mail()
 mail.from_email = Email(from_email)
 mail.subject = subject
 personalization = Personalization()

 if to_list not in [[], '', None]:

     for to_addr in to_list:
         
         personalization.add_to(Email(to_addr))
         mail.add_personalization(personalization)

 if cc_list not in [[], '', None]:

     for cc_addr in cc_list:
         personalization.add_cc(Email(cc_addr))
         mail.add_personalization(personalization)

 if bcc_list not in [[], '', None]:

     for bcc_addr in bcc_list:
         personalization.add_bcc(Email(bcc_addr))
         mail.add_personalization(personalization)


 mail.add_content(Content("text/html", content))



 if attachments not in [[], '', None]:

     for file in attachments:
         data = open(file, "rb").read()

         encoded = base64.b64encode(data).decode()

         attachment = Attachment()
         attachment.content = encoded

         path, fName = Dir_File_Operation.get_new_file_Path_name(file)  #this is to get path and filename, not important here

         print(path, fName, fName.split('.')[-1])

         attachment.type = "application/{}".format(fName.split('.')[-1])
         attachment.filename = fName
         attachment.disposition = "attachment"  # "inline" 
         mail.add_attachment(attachment)

 response = sg.client.mail.send.post(request_body=mail.get())
 print(response.status_code)
 print(response.body)
 print(response.headers)

 print('SendGrid信封发送成功！')

 return response



if __name__=="__main__":
    sendgrid_apiKey = '#######'

    from_email='#####'

    to_list=['###','#####']

    cc_list=['#####','######']

    bcc_list=['#######']

    subject='测试单案例'

    content='只是测试一下发几次'


    Email_st_by_Sendgrid(api_key= sendgrid_apiKey, from_email=from_email, to_list=to_list, cc_list=cc_list, bcc_list=bcc_list, subject=subject, content=content, attachments=[])

**Comment by ytldsimage** [comment]
Even only one attachment, the problems reoccur. 

0 attachment, 0 problems.



file='a.jpg'

            if 1:
                data = open(file, "rb").read()
               

                encoded = base64.b64encode(data).decode()
               

                attachment = Attachment()

                attachment.content = encoded

                path, fName = Dir_File_Operation.get_new_file_Path_name(file)

                print(path, fName, fName.split('.')[-1])

                attachment.type = "application/{}".format(fName.split('.')[-1])
                attachment.filename = fName
                
                attachment.disposition = "attachment"  # "inline"

                attachment.content_id = 'Kungfuas'
                mail.add_attachment(attachment)

**Comment by ytldsimage** [comment]
The following code is officially suggested：

        attachment = Attachment()
        attachment.content = "TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gQ3JhcyBwdW12"
        attachment.type = "application/pdf"
        attachment.filename = "balance_001.pdf"
        attachment.disposition = "attachment"
        attachment.content_id = "Balance Sheet"
        mail.add_attachment(attachment)

        attachment2 = Attachment()
        attachment2.content = "BwdW"
        attachment2.type = "image/png"
        attachment2.filename = "banner.png"
        attachment2.disposition = "inline"
        attachment2.content_id = "Banner"

**Comment by ytldsimage** [comment]
The following code is officially suggested：

file_path = "file_path.pdf"
with open(file_path,'rb') as f:
    data = f.read()
    f.close()
encoded = base64.b64encode(data).decode()

attachment = Attachment()
attachment.content = encoded
attachment.type = "application/pdf"
attachment.filename = "test.pdf"
attachment.disposition = "attachment"
attachment.content_id = "Example Content ID"

mail = Mail(from_email, subject, to_email, content)
mail.add_attachment(attachment)

**Comment by ytldsimage** [comment]
It seems as long as the attachment.content=base64.b64encode(data).decode(), this problem will reoccur.

**Comment by ytldsimage** [comment]
> Hi @ytldsimage,
> 
> Could you please provide your [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body)?
> 
> Thanks!
> 
> With Best Regards,
> 
> Elmer

Hi  Elmer,

I'm sorry but I hadn't used the requests library,  and I finally locate the problem is related to this ：
attachment.content=base64.b64encode(data).decode()

if we set attachment.content='ssfsfsfsdfsd', nothing will happen.

**Comment by thinkingserious** [comment]
Hi @ytldsimage,

In your code, right before you call `response = sg.client.mail.send.post(request_body=mail.get())`, can you please do: `print(mail.get())`?

Thanks!

With Best Regards,

Elmer
