### ISSUE TITLE
The last link in About section is an email and not a list of developers

### ISSUE THREAD

**Issue by Bharat123rox** [sendgrid/sendgrid-python#614]
#### Issue Summary

Make it clear that the last link in the About section in README.md is a redirect to an email and not to any members page or developer team page

#### Steps to Reproduce

1. Click on the link
2. It opens up an email client saying mailto: dx@sendgrid.com

I have made a PR #613 to fix this

**Comment by thinkingserious** [comment]
HI @Bharat123rox,

Now that I've read your explanation, I think this is a worthy PR. I will update accordingly.

**Comment by prnvdixit** [comment]
@thinkingserious Is there anything still needs to be done in this issue? I would love to take this up in that case :smile:

**Comment by thinkingserious** [comment]
This one has been completed @prnvdixit, but there are still [many more opportunities](https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/) to join in on the fun :) Thanks!
