### ISSUE TITLE
Upgrade versions of requirements in requirements.txt

### ISSUE THREAD

**Issue by rahulkumaran** [sendgrid/sendgrid-python#623]
#### Issue Summary

Update the version numbers of the requirements in requirements.txt as currently we have versions above the current mentioned ones that are stable.

#### Steps to Reproduce

1. Check requirements.txt

It's better to stay up to date with these as it would help us avoid problems later. 
I'd like to work on this.

**Comment by jamietanna** [comment]
@thinkingserious I think this can probably be closed now?

**Comment by michaelscof** [comment]
Is it still open?If yes i would like to take it up!

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-python/pull/630
