### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#627]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by browniebroke** [comment]
Hi there, I can look into this, but I have a question about the second point:

> - the version is determined by the CHANGELOG.md

Looking at the [latest version bump](https://github.com/sendgrid/sendgrid-python/commit/7438ae17406f6f25cab58f9e807576c94a785d3d), there are a couple of things happening:

- Update Changelog
- Update docker/README
- Update `sendgrid/version.py`
- Add a git tag

Then Travis detects there is a new tag, and pushes to PyPI:

https://github.com/sendgrid/sendgrid-python/blob/dc45b633b7df74ed4456bcbe9b8b79e4c2c6fbe4/.travis.yml#L39-L48

The changelog needs a bit of manual entry, but I guess we could check if the latest changelog version matches the package version and if not do the update?

**Comment by thinkingserious** [comment]
Maybe we grab the version from `sendgrid/version.py` instead.

**Comment by thinkingserious** [comment]
Thanks for taking this on @browniebroke!

**Comment by eshanholtz** [comment]
Fixed by #862
