### ISSUE TITLE
Update documenation for retrieving a list of all templates (dynamic & legacy)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#644]
#### Issue Summary

Please update the `USAGE.md` and corresponding `\example` with the call to list all templates. 

This is the API call required: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

#### Acceptance Criteria

* The Usage.md file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic
* The corresponding `/example` file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

**Comment by vipulgupta2048** [comment]
Hey @thinkingserious, I am willing to work on this. Looks good enough. 
Let me see if I get it right, 
We have to update the [1](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#get-templates) and [2](https://github.com/sendgrid/sendgrid-python/blob/master/examples/templates/templates.py) files with examples to retrieve a list of all templates. Right?
The way to retrieve all templates is through the call - [3](https://api.sendgrid.com/v3/templates?generations=legacy,dynamic)
And the work should match the acceptance criteria.

If TRUE:
    return I_will_proceed

**Comment by Sarthakagarwal22** [comment]
@thinkingserious i have opened a new PR, with the changes rebased against v4, please check

**Comment by eshanholtz** [comment]
Closing this PR as the v4 branch is no longer being maintained.
