### ISSUE TITLE
Throw an exception if a template ID does not exist in your request body

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#645]
#### Issue Summary

You will not receive an error from the API is you send an email with the wrong template. Instead you will get a "Not Delivered" notice in your email activity feed. We want to make that experience better by throwing an exception in the code instead.

This issue is inspired by [this](https://github.com/sendgrid/sendgrid-go/issues/255).

#### Acceptance Criteria

* Use [the API](https://github.com/sendgrid/sendgrid-go/issues/255) to verfiy a template ID exists, if not, throw an exception
* A new test is added that demonstrates that if you use a non-existent template, the code will throw an error

**Comment by rajibmitra** [comment]
I want to take this up.

**Comment by Deborah-Digges** [comment]
I can take this up if nobody is working on it currently

**Comment by 3lnc** [comment]
Tbh, I'm against the idea of preemptive calls to API for template checks. We can provide simple api to do this manually, but checks while sending is really weird.

**Comment by eshanholtz** [comment]
Closing this issue as the v4 branch is no longer being maintained.
