### ISSUE TITLE
Update CONTRIBUTING.md to add Python Version 3.6

### ISSUE THREAD

**Issue by mosesmeirelles** [sendgrid/sendgrid-python#657]
#### Issue Summary

As contributor following listed steps on CONTRIBUTING.md, documentation doesn't bring the Python Version 3.6 on Initial Setup instructions to Test project. This version is declared on Tox commands, which causes an error when executed following initial setup steps.

#### Steps to Reproduce

1. Follow steps described in [Initial Setup](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#initial-setup-1)

I'd would like to take this up.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-python/commit/91f4cd89aef7e4856706791c99cde460d26011af
