### ISSUE TITLE
Auto-generate the CHANGELOG.md file upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#667]
#### Issue Summary

For every release, we currently hand craft a CHANGELOG.md update, now we would like to automate this process. Please see the existing CHANGELOG.md for formatting structure.

#### Acceptance Criteria

* A script, which when run, creates a CHANGELOG.md update based on any merged PRs since the last release.

**Comment by nathanmkaya** [comment]
Hey, I'm thinking of just creating a bash script that generates the list of PR's between the current and previous release(tag) and appends the result to the top of CHANGELOG.md then pushes the changes back to Github if the changes were successfully made to the CHANGELOG.md file. It will be a bash script with the different functions to do the two actions. Pushing changes back to Github will require an access token added to travis as an encrypted variable.

Could I take this up?

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
