### ISSUE TITLE
Document new Git workflow in CHANGELOG.md

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#675]
#### Issue Summary

We want to update our git workflow to function more like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). We need to update the CONTRIBUTING.md file and PULL_REQUEST_TEMPLATE to direct contributors to fork/branch off the `development` branch and to merge their PRs with the `development` branch. Once this issue is complete, we will be creating the `development` branch and making that branch the default. This is part of a larger strategy to execute releases for this SDK on a predictable cadence.

#### Acceptance Criteria

* Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the `development` branch and submitting PRs agains the `development` branch.
* Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.

**Comment by assignment6** [comment]
Hello,  Is this still open?  As a newcomer, I would like to use opportunity to be involved.
Thank you

**Comment by ammarnajjar** [comment]
Is there still anything open here to do?
I think this issue should be closed after #730 was merged, or am I missing something?

**Comment by childish-sambino** [comment]
Closing as we're no longer going with this change of workflow.
