### ISSUE TITLE
Can zip files be sent as attachments?

### ISSUE THREAD

**Issue by rahulkumaran** [sendgrid/sendgrid-python#680]
#### Issue Summary
Is it possible to send zip files as attachments using the Sendgrid API in python3?
If yes, then how do we do it? Can a small piece of code be given?

#### Technical details
* Python Version: 3.6

**Comment by thinkingserious** [comment]
Hello @rahulkumaran,

[Here](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/attachment.md) is an example of how to send an attachment using this SDK. 

In your case you would use type `application/zip`.

With Best Regards,

Elmer

**Comment by moshe770** [comment]
What application type would there be for jpg?

**Comment by childish-sambino** [comment]
@moshe770 You'd use `image/jpeg` ([reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)). Verified locally.
