### ISSUE TITLE
Python 3.7 Support?

### ISSUE THREAD

**Issue by noqcks** [sendgrid/sendgrid-python#691]
Is Python 3.7 supported by this library? (v5.6.0)

If not, is there any ETA on when support will be included?

**Comment by hugovk** [comment]
I don't know but I can tell you:

I created PR https://github.com/sendgrid/sendgrid-python/pull/615 to add Python 3.7 to the `master` branch (which has version 5.6.0):

https://github.com/sendgrid/sendgrid-python/blob/0b683169b08d3a7c204107cd333be33053297e74/sendgrid/version.py#L1

But I was asked to move it instead to the `v4` branch (which has version 5.4.1):

https://github.com/sendgrid/sendgrid-python/blob/63b8134c415b14f6cca58221e038e47e6c46b939/sendgrid/version.py#L1

So I closed #615 and made PR https://github.com/sendgrid/sendgrid-python/pull/637 instead which was merged.

**Comment by thinkingserious** [comment]
Hello @noqcks,

We are working on a new v4 release of this SDK which will specifically included support for 3.7. That said, @hugovk was able to show 3.7 support in this particular library. Please let us know if you run into any trouble.

With Best Regards,

Elmer

**Comment by kevin-brown** [comment]
The tests pass on the master branch (see https://github.com/sendgrid/sendgrid-python/pull/744), so I think it can be said that the library does in fact support Python 3.7.
