### ISSUE TITLE
Documentation on Transactional Templates missing

### ISSUE THREAD

**Issue by AlexandraPosoldova** [sendgrid/sendgrid-python#737]
#### Issue Summary

Use cases -> Transactional Templates leads to 404 missing page. 

I briefly looked through opened and closed issues on Transactional templates but it is unclear to me how to use them.

**Comment by thinkingserious** [comment]
Hello @AlexandraPosoldova,

I believe [this](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md) is the documentation you need. Please let me know if you run into any trouble.

With Best Regards,

Elmer

**Comment by haivp3010** [comment]
There's a typo in the [README](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/README.md), in which `transational_templates.md` should be `transactional_templates.md`
