### ISSUE TITLE
after reboot HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by peckandrew** [sendgrid/sendgrid-python#742]
running the example script but between reboots it kicks back a HTTP Error 401: Unauthorized until I reset the api key with a new one
here is a screenshot of the error
![image](https://user-images.githubusercontent.com/45343168/49842726-acba3a00-fd8a-11e8-8c08-e33f4e86daf1.png)

Thanks

**Comment by thinkingserious** [comment]
Hello @peckandrew,

It sounds like your environment variable is getting reset when you reboot the server. Can you check the value of your API key environment variable after reboot to see if it's still set?

With Best Regards,

Elmer

**Comment by adrianchifor** [comment]
I'm getting the same, my service is getting random intermittent Unauthorized responses.

**Comment by thinkingserious** [comment]
@peckandrew, @adrianchifor,

Are you still experiencing this issue?

**Comment by adrianchifor** [comment]
Nope, last occurrence was 2 weeks ago.

**Comment by thinkingserious** [comment]
@peckandrew,

Are you still experiencing this issue?

Thanks!

Elmer
