### ISSUE TITLE
Broken link (MD filename typo)

### ISSUE THREAD

**Issue by adamatan** [sendgrid/sendgrid-python#745]
#### Issue Summary

Broken link.

#### Steps to Reproduce

Open https://github.com/sendgrid/sendgrid-python/tree/master/use_cases and hit the `Transactional Templates` link, third from the bottom.

#### Technical details:

Caused by a typo. PR #746 submitted.

**Comment by thinkingserious** [comment]
Hi @adamatan,

Please rebase against the `v4` branch and I'll get this merged. Thanks!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Fixed by #758
