### ISSUE TITLE
Email format not rendering properly

### ISSUE THREAD

**Issue by billybabis** [sendgrid/sendgrid-python#751]
#### Issue Summary

When I try to send an email with the sendgrid api, the format of the email is not rendering properly (see photo). I've contacted support and they told me to reach out to the dev's and Elmer just told me to reach out to support! It's been about 3 weeks now and I'd love some help if anyone can throw me a bone.

![](https://user-images.githubusercontent.com/24499054/50453889-f15cde00-0911-11e9-9b8f-0a1a8f83f3de.png)

I've set up a server that receives an email from Sendgrid, modifies the content of the email, and then sends the email to a different recipient using the sendgrid api. For testing, I don't modify the content of the email I received from sendgrid -- I just forward the content. The email successfully sends, but the format of the email is gibberish. When I try to add a Content-Transfer-Encoding header, the email fails to send with a 400.

#### Steps to Reproduce

1. Put the Http email object into a text file
2. In Python, Parse the text/html and text/plain sections of the http email object
3. Use the sendgrid python api to send that email to a new recipient.
4. Check you email.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 3.7

**Comment by thinkingserious** [comment]
Hello @billybabis,

Could you please share the html and the source code?

With Best Regards,

Elmer
