### ISSUE TITLE
Sending HTML doesnt' work

### ISSUE THREAD

**Issue by martinlombana** [sendgrid/sendgrid-python#752]
#### Issue Summary

Sending HTML doesn't work. 

Sending plain TXT works.

(Threre are no other python or django errors)

#### Steps to Reproduce

with Django, (which is not relevant, in this case):

`

        class EmailSendView(View):
		sg = sendgrid.SendGridAPIClient(apikey='********')
		from_email = Email("test@test.com")
		to_email = Email("test@test.com"")
		subject = "Test examples" + str(timezone.now().isoformat())
		
		context = {
			'text': 'example'
		}
		
		mail_html = Content('text/html', get_template('email/reservation_done.html').render(context))
		mail_txt = Content(type_='text/plain', value='This is a test email message.')
		mail = Mail(from_email, subject, to_email, mail_html)
		mail.add_content(mail_txt)
		
		response = sg.client.mail.send.post(request_body=mail.get())
		
		print(response.status_code, flush=True)
		print(response.body, flush=True)
		print(response.headers, flush=True)
		result = str(response.status_code) + str(response.body) + str(response.headers)`
This doesn't work. 

But if I remove the mail_html , and send just plain TXT, this works.

The output is:

`
202b''Server: nginx Date: Sun, 13 Jan 2019 21:29:55 GMT Content-Type: text/plain; charset=utf-8 Content-Length: 0 Connection: close X-Message-Id: moW00FY9Sqyr2r5ekgRDLg Access-Control-Allow-Origin: https://sendgrid.api-docs.io Access-Control-Allow-Methods: POST Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl Access-Control-Max-Age: 600 X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html

`
* sendgrid-python Version: sendgrid==5.6.0
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @martinlombana,

Can you please try setting `mail_txt` before `mail_html`? Thanks!

With Best Regards,

Elmer

**Comment by martinlombana** [comment]
I did that as well. 

No luck.

I received some of the emails 1 day later. Very weird.

You mean this way, right?

```
mail_txt = Content(type_='text/plain', value='This is a test email message.')
		mail_html = Content('text/html', '<html><head></head><body>HTML CONTENT 14 ENERO</body></html>')
	
		mail = Mail(from_email, subject, to_email)
		mail.add_content(mail_txt)
		mail.add_content(mail_html)
		
		# mail.add_content(mail_txt)
		
		response = sg.client.mail.send.post(request_body=mail.get())
		
		print(response.status_code, flush=True)
		print(response.body, flush=True)
		print(response.headers, flush=True)
		result = str(response.status_code) + str(response.body) + str(response.headers)
		return HttpResponse(result)
```

**Comment by martinlombana** [comment]
It seems to work now. Weird that that is not documented :S.

Thanks anyway!

**Comment by thinkingserious** [comment]
Thanks for following up @martinlombana!

In the upcoming v4 of this SDK, we will ensure that the correct ordering happens behind the scenes.

With Best Regards,

Elmer
