### ISSUE TITLE
Have to run source ./sendgrid.env every ~ hour

### ISSUE THREAD

**Issue by futurealecks** [sendgrid/sendgrid-python#762]
#### Issue Summary

Using SendGrid python on Amazon Linux 2. After about an hour of sending an email I get

`python_http_client.exceptions.UnauthorizedError
`

If I run `source ./sendgrid.env` then run the Python file it works as expected.

#### Steps to Reproduce

1. Follow the install readme on Amazon Linux
2. Create a simple sendgrid python script (see below)
3. Run the script, wait an hour and try to run the script again

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: Installed from pip (how to tell version?)
* Python Version: 2.7.15

```
import sendgrid
import os
from sendgrid.helpers.mail import *
from sendgrid.helpers.mail import Email, Substitution, Mail, Personalization
from python_http_client import exceptions

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('MY-API'))
from_email = Email("noreply@myemail.com")
to_email = Email("user@email.com")
subject = "my subject"
content = Content("text/plain", "Some text here")
mail = Mail(from_email, subject, to_email, content)
response = sg.client.mail.send.post(request_body=mail.get())
print(response.status_code)
print(response.body)
print(response.headers)
```

**Comment by thinkingserious** [comment]
Hello @futurealecks,

This appears to be an issue with your server. It looks like it's deleting your environment variables periodically. I would check your server logs for clues and also ping your server provider for help. 

With Best Regards,

Elmer

**Comment by chrisherold** [comment]
@futurealecks are you open to using a package? python-dotenv is how I manage loading the env variables inside the code execution so the key should then always be there when I need it in the code.

https://github.com/theskumar/python-dotenv

You can rename your env file to simply `.env` and then it will load automatically when you call the load function:
```
from dotenv import load_dotenv
load_dotenv()
```

Or you can explicitly provide the filename and call the file whatever you like:
```
from dotenv import load_dotenv
load_dotenv(dotenv_path='./sendgrid.env')
```

**Comment by thinkingserious** [comment]
Hello @chrisherold,

Thanks for helping out, we appreciate it!
