### ISSUE TITLE
Recpients/Contacts not being added to UI from API

### ISSUE THREAD

**Issue by dhhagan** [sendgrid/sendgrid-python#767]
#### Issue Summary

When using this wrapper, I try to add contacts/recipients, but none ever show up in the UI, despite receiving 201's.

#### Steps to Reproduce

```python
import sendgrid

sg = sendgrid.SendGridAPIClient(apikey=<key>)

data = [
  {
    "email": "test@test.com"
  }
]

response = sg.client.contactdb.recipients.post(request_body=data)

```

The response looks like:

```sh
'{"new_count":1,"updated_count":0,"error_count":0,"error_indices":[],"unmodified_indices":[],"persisted_recipients":["dGVzdEB0ZXN0LmNvbQ=="],"errors":[]}\n'
```

I'm a bit confused, because (1) I'm receiving 201's and (2) if I try the example on the Contacts API page, it all works fine.

#### Technical details:

* sendgrid-python Version: 5.6.0
* Python Version: 3.6.5

**Comment by thinkingserious** [comment]
Hello @dhhagan,

What you have posted looks as it should. 

My suggestion would be to reach out to our [support team](https://support.sendgrid.com) so that they may dig into your account to help troubleshoot.

With Best Regards,

Elmer

**Comment by dhhagan** [comment]
Thanks @thinkingserious - I actually went to them first, and they told me they couldn't help and that I should post on GitHub...hmm

**Comment by thinkingserious** [comment]
Could you please send me your ticket number? You can email it to us at dx@sendgrid.com. Thanks!

**Comment by thinkingserious** [comment]
Hello @dhhagan,

When you say "if I try the example on the Contacts API page, it all works fine.", do you mean here? https://sendgrid.com/docs/API_Reference/api_v3.html
