### ISSUE TITLE
DRY refactor for mail.py 

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#770]
#### Issue Summary

There is duplicate code in mail.py that should be refactored into helper methods.

#### Acceptance Criteria

1. Duplicate code is refactored into helper underscore methods.
2. All tests continue to pass.

**Comment by helle253** [comment]
I might want to take a look at this, if it's available.

**Comment by GoelBiju** [comment]
@thinkingserious I am happy to help refactor [mail.py](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py) as you mentioned. I am assuming you want to have the helper methods within the same class?

**Comment by eshanholtz** [comment]
Closing this issue as the v4 branch is no longer being maintained.
