### ISSUE TITLE
Add docstrings to stats.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#772]
#### Issue Summary

[`stats.py`](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/stats/stats.py) does not have any docstrings. Please use the [Sphinx format](https://pythonhosted.org/an_example_pypi_project/sphinx.html)

**Comment by SameeranB** [comment]
Hi! This seems like an interesting issue to me. Would it be okay if I took this up?

**Comment by DougCal** [comment]
Have this done locally.  Working on creating a PR now.
