### ISSUE TITLE
Can not import 'ASM' in 6.0.2

### ISSUE THREAD

**Issue by dongkangli** [sendgrid/sendgrid-python#777]
#### Issue Summary

Got an error when import ASM with 6.0.2

#### Steps to Reproduce

In [3]: from sendgrid.helpers.mail import (
   ...:     ASM, Attachment, Category, Content, Email, Header, Mail, MailSettings, OpenTracking,
   ...:     Personalization, SandBoxMode, Substitution, TrackingSettings
   ...: )
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-1f78f6c37c3f> in <module>()
----> 1 from sendgrid.helpers.mail import (
      2     ASM, Attachment, Category, Content, Email, Header, Mail, MailSettings, OpenTracking,
      3     Personalization, SandBoxMode, Substitution, TrackingSettings
      4 )

ImportError: cannot import name 'ASM'

**Comment by thinkingserious** [comment]
Hello @dongkangli,

It should be `Asm`. Can you please try that?

Thanks!

With Best Regards,

Elmer

**Comment by dongkangli** [comment]
Thanks @thinkingserious 
I using django-sendgrid-v5 which imports _ASM_ I guess I can wait for them to update it.

**Comment by thinkingserious** [comment]
Ah, it seems they are pinned to the [v5 version of the library](https://github.com/sendgrid/sendgrid-python/tree/7438ae17406f6f25cab58f9e807576c94a785d3d) but it looks like they are [already working on it](https://github.com/sklarsa/django-sendgrid-v5/pull/53) :)
