### ISSUE TITLE
Can't attach csv

### ISSUE THREAD

**Issue by tomwwagstaff-product** [sendgrid/sendgrid-python#779]
#### Issue Summary

Several months ago I wrote a script that involved sending a csv file in attachment. I tested this locally with success and uploaded it to a virtual machine to run regularly. Now I find that when I try to run this script locally it throws an error, although it continues to run fine on the virtual machine.

If I omit the attachment it runs fine on both systems.

I have no idea if this relates to issue #704 

Also I don't know what the difference is between the sendgrid module and the sendgrid-python module...

#### Steps to Reproduce

1. Try to run the Python function below.

#### Technical details:

* sendgrid Version: 5.4.1
* Python Version: 3.6

Virtual machine (where it continues to run):
* sendgrid Version: 5.4.0
* Python Version: 3.6

Error:
`BadRequestsError: HTTP Error 400: Bad Request`

## Code
```
import sendgrid
from sendgrid.helpers.mail import Email, Content, Mail, Attachment, Personalization

def sendGrid(recipient, subject, body, file = None, filename = "attachment.csv", bcc = 0):
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
    from_email = Email("myemail@example.com")
    to_email = Email(recipient)
    content = Content("text/plain", body)
    
    mail = Mail(from_email, subject, to_email, content)
    
    if file:
        data = str.encode(file)
        encoded = base64.b64encode(data).decode()
        
        attachment = Attachment()
        attachment.content = encoded
        attachment.type = "text/csv"
        attachment.filename = filename
        attachment.disposition = "attachment"
        attachment.content_id = "Example Content ID"    
        
        mail.add_attachment(attachment)
        
    if bcc == 1:
        mail.personalizations[0].add_bcc(Email("myemail@example.com"))
    
    try:
        response = sg.client.mail.send.post(request_body=mail.get())
    except urllib.HTTPError as e:
        print(e.read())
```

**Comment by dijaitly** [comment]
Hi,

I am also getting an error using python 2.7. 
from sendgrid import *
from sendgrid.helpers.mail import *
import base64
import sys



from_email = Email("dinkar@abaka.me")
to_email = Email("dinkar@abaka.me")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "a")
mail = Mail(from_email, subject, to_email, content)
sg = sendgrid.SendGridAPIClient("key")
data = mail.get()
response = sg.client.mail.send.post(request_body=data)

it is giving following error : 
<sendgrid.helpers.mail.email.Email object at 0x7fa9a65a7690> is not JSON serializable

It was working till yesterday...

**Comment by JagadeeshBoyidi** [comment]
I'm Facing the same issue <sendgrid.helpers.mail.email.Email object at 0x7fa9a65a7690> is not JSON serializable.

Someone can help me out

**Comment by tomwwagstaff-product** [comment]
These examples are not the same as the issue I opened here, being a different error thrown in a different use case using a different version of Python. Can you open a separate issue to avoid confusion?

**Comment by thinkingserious** [comment]
Hello @tomwwagstaff-product,

What is the value of `print(response.body)` right after you make your `post`?

Also, can you check if the local version of the SendGrid library is the same version?

@JagadeeshBoyidi,

This issue is not related, could you please open a new issue? I'm guessing you may have [this issue](https://github.com/sendgrid/sendgrid-python/issues/782).

With Best Regards,

Elmer

**Comment by tomwwagstaff-product** [comment]
Hello @JagadeeshBoyidi, thanks for getting back to me

I'm afraid that `response` never gets successfully assigned because of that error - if I try printing `response.body` in debug mode it just says `NameError: name 'response' is not defined`

So the libraries are not quite the same - v5.4.1 vs v5.4.0 - I'm using Anaconda locally and I only have a limited range of versions available. I'm loathe to update the library on the virtual machine as it's the one instance that's still working...

**Comment by thinkingserious** [comment]
Can you please print the value of mail.get() right before the post?

**Comment by tomwwagstaff-product** [comment]
Sure, here you go:

`{'from': {'email': 'tom.wagstaff@raisingit.com'}, 'subject': 'New charities', 'personalizations': [{'to': [{'email': 'tom.wagstaff@raisingit.com'}], 'bcc': [{'email': 'tom.wagstaff@raisingit.com'}]}], 'content': [{'type': 'text/plain', 'value': 'Hi,\nAttached is the list of new charities that registered with the Charity Commission during the month of April 2019'}], 'attachments': [{'content': 'YSxiCjEsMgozLDQK', 'type': 'text/csv', 'filename': 'newCharities.csv', 'disposition': 'attachment', 'content_id': 'Example Content ID'}]}`

**Comment by thinkingserious** [comment]
Hello @tomwwagstaff-product,

Your JSON looks correct. I would try the following:

1. Double check the location of `myFile.csv`
2. Check the .csv file for any non-standard encoding. Perhaps try a simple .csv files with just one or two entries. 

With Best Regards,

Elmer

**Comment by tomwwagstaff-product** [comment]
Thanks for your continuing help with this, @thinkingserious 

So actually there is no .csv file saved anywhere, the `file` that gets passed to that function is just the following string:
```
a,b
1,2
3,4
```
Given that, I think it will just be Unicode anyway, right?

Cheers,
Tom

**Comment by thinkingserious** [comment]
Hi @tomwwagstaff-product,

Can you verify that the base64 decoded file converts to the .csv file?

**Comment by tomwwagstaff-product** [comment]
Hello @thinkingserious - how can I do that?

**Comment by thinkingserious** [comment]
You can use [this](https://docs.python.org/3.7/library/base64.html) or you can try a [web based service](https://www.base64decode.org/).

**Comment by tomwwagstaff-product** [comment]
Thanks @thinkingserious,

Yeah it decodes back to csv just fine:

```
base64.b64decode(encoded)
b'a,b\n1,2\n3,4\n'
```

**Comment by thinkingserious** [comment]
I think something is happening with your encoding.

What is the data type of `file`?

It may be that you just need to do this `encoded = base64.b64encode(file).decode()`

With Best Regards,

Elmer

**Comment by tomwwagstaff-product** [comment]
Hi @thinkingserious,

Hmm, but haven't we just confirmed that the encoding is fine by successfully decoding the encoded object back to a string? (`file` is a string)

I'm already doing that - it's line 14 of the original code I posted. This `encoded` object is what I've checked decodes back to a string.

**Comment by thinkingserious** [comment]
Hello @tomwwagstaff-product,

I'm not able to confirm the issue on my end, this is why I suspect the encoding issue. Have you tried testing with a local test .csv?

With Best Regards,

Elmer

**Comment by tomwwagstaff-product** [comment]
Hello @thinkingserious,

So I've just tried creating saving a seperate csv and reading it in like this instead:
```
with open(file, 'rb') as f:
            data = f.read()
            f.close()
encoded = base64.b64encode(data).decode()
...
```

It just gives the same result:
`BadRequestsError: HTTP Error 400: Bad Request`

The error does match this thread, where it seems to have been caused by improperly encoding the attachment, but my script already reflects the solutions given here: https://stackoverflow.com/questions/40656019/python-sendgrid-send-email-with-pdf-attachment-file

**Comment by thinkingserious** [comment]
Here is the full code I used along with the test file (note that I had to compress the .csv file to upload here, you will need to unzip it):

```python
import base64
import os
import json
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (
    Mail, Attachment, FileContent, FileName,
    FileType, Disposition, ContentId)
try:
    # Python 3
    import urllib.request as urllib
except ImportError:
    # Python 2
    import urllib2 as urllib

message = Mail(
    from_email='dx@sendgrid.com',
    to_emails='elmer.thomas@sendgrid.com',
    subject='Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
file_path = './test.csv'
with open(file_path, 'rb') as f:
    data = f.read()
    f.close()
encoded = base64.b64encode(data).decode()
attachment = Attachment()
attachment.file_content = FileContent(encoded)
attachment.file_type = FileType('application/pdf')
attachment.file_name = FileName('test.csv')
attachment.disposition = Disposition('attachment')
message.attachment = attachment
try:
    sendgrid_client = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    response = sendgrid_client.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.message)
```

[test.csv.zip](https://github.com/sendgrid/sendgrid-python/files/3090372/test.csv.zip)

**Comment by tomwwagstaff-product** [comment]
Thanks @thinkingserious,

I tried using your sample csv with my last script, and it failed again with the same error:
`BadRequestsError: HTTP Error 400: Bad Request`

When I try to use your script, it fails with the error `ImportError: cannot import name 'FileContent'`
Is there a template script for v5.4.1 of the package (other than the one I've used)?

(I'm reluctant to upgrade the package, because it might break the one instance of this that's still working...)

**Comment by thinkingserious** [comment]
Ah, I was using v6.0.3.

[Here is the example](https://github.com/sendgrid/sendgrid-python/blob/1ac58c6fc491554bc24573393ae6242e579dbabb/use_cases/attachment.md) for v5.4.1.

**Comment by tomwwagstaff-product** [comment]
Thanks @thinkingserious,

Using this script I worked out what the problem was, and I must apologise as it wasn't to do with the attachment at all, it was adding the BCC email address along with it...

The package crashes when you add the recipient email address again as a BCC. I'm normally BCCed into these emails, and when testing I change the recipient to my address too to avoid spamming the end user.

_If_ this is still an  issue in the current package, can I raise this as a **bug**?

**Comment by SendGridDX** [comment]
Hello @tomwwagstaff-product,

It is expected behavior for duplicate emails to be rejected. That said, it would be good to have a better error message for that, so a new issue would be greatly appreciated. Thanks!

With Best Regards,

Elmer

**Comment by safijari** [comment]
I just wasted a good 6 hours of my life to this.

Yes, a better error message would be much much appreciated.
