### ISSUE TITLE
Send grid not working with python 3.5.2

### ISSUE THREAD

**Issue by dijaitly** [sendgrid/sendgrid-python#782]
Hi ,

I am trying to send email using following code in python version 3,5,2 and sendgrid 6.0.2 
from sendgrid import *
from sendgrid.helpers.mail import *
import base64
import sys

from_email = Email("from")
to_email = Email("t0")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "a")
mail = Mail(from_email, subject, to_email, content)
sg = sendgrid.SendGridAPIClient("key")
data = mail.get()
response = sg.client.mail.send.post(request_body=data)

it is giving me following error
TypeError: <sendgrid.helpers.mail.email.Email object at 0x000001B5D47A7668> is not JSON serializable

* sendgrid-python Version: master (latest commit: [commit number]) 6.0.2
* Python Version: 3.5.2

**Comment by thinkingserious** [comment]
Hello @dijaitly,

The equivalent code in sendgrid-python v6.0.2 can be found [here](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_a_single_email_to_a_single_recipient.md).

You would be replacing:
```python
mail = Mail(from_email, subject, to_email, content)
```
with
```python
mail = Mail(from_email, to_email, subject, content)
```
and
```python
data = mail.get()
response = sg.client.mail.send.post(request_body=data)
```
with
```python
response = sg.send(mail)
```

With Best Regards,

Elmer

**Comment by dijaitly** [comment]
Hi ,
I followed your instructions

from sendgrid import *
from sendgrid.helpers.mail import *
import base64
import sys
from_email = Email("from")
to_email = Email("to")
subject = "Sending with SendGrid is Fun"
content = Content("text/plain", "a")
mail = Mail(from_email, to_email, subject, content)
sg = sendgrid.SendGridAPIClient("key")
response = sg.send(mail)



I get the following error..
 raise ValueError('Please use a To, Cc or Bcc object.')
ValueError: Please use a To, Cc or Bcc object.

I followed the instruction on the link provided..

**Comment by stefangordon** [comment]
Seems like a crazy breaking change (reordering parameters) to push out to people automatically via a new package version.

**Comment by thinkingserious** [comment]
Hello @stefangordon,

Please see [this issue](https://github.com/sendgrid/sendgrid-python/issues/323) with respect to the refactor.

Since we hope to very rarely make breaking changes, I tried to fix bad design issues while we had the hood up, so to speak. One of those bad decisions was the original ordering of the parameters. 

We used the semver custom of specifying a major version bump to avoid breaking changes being introduced to folks via auto-update. In your case, how did this major version bump slip through into production? I'd like to learn from you to avoid this issue in the future (that said, I'm really hoping we don't need a breaking change in the foreseeable future).

Thanks for the feedback!

With Best Regards,

Elmer

**Comment by stefangordon** [comment]
Thanks @thinkingserious, I understand sometimes it is necessary to make these changes.  In my case we publish a library on PyPi and we do not pin any package versions as we understand it to be best practice - as such the library just stopped working for users after a deployment one day.  

I suppose if you want to make this change you could make an entirely new method name with your new parameters and mark the old one as deprecated for a while so people have lots of time to see warnings about deprecation before it goes away.  Of course this makes it take much longer to complete the transition.

**Comment by thinkingserious** [comment]
Hello @stefangordon,

Thank you for taking the time to provide thoughtful feedback, I really appreciate it!

I've added your thoughts to our internal notes around improving our developer experience around our helper libraries.

Cheers!

With Best Regards,

Elmer

**Comment by japrogramer** [comment]
@thinkingserious  im experiencing the same error 

I can't tell what im doing wrong
I thought it might have something to do with 

https://github.com/sendgrid/sendgrid-python/issues/738

```
def send_mail_co(subject, from_email, to_email, plain_content=None, html_content=None, categories=None):
    from_email = Email(from_email)
    to_email = Email(to_email)
    mail = Mail()
    mail.subject = subject

    personalization = Personalization()
    personalization.add_to(to_email)
    personalization.add_bcc(from_email)

    mail.add_personalization(personalization)
    mail.add_content(Content("text/plain", plain_content))
    mail.add_content(Content("text/html", html_content))
    if categories:
        for i in categories:
            mail.add_category(Category(i))
    try:
        response = sg.client.mail.send.post(request_body=mail.get())
    except Exception as e:
        __import__('pdb').set_trace()
        print(e)
        raise e

```


```
BadRequestsError(<HTTPError 400: 'Bad Request'>,)

mail.get()

{
    "subject": "kratos has invited you to join !",
    "content": [
        {
            "type": "text/plain",
            "value": "kratos Mars\n\n  from Programming\n  \n\nhas invited you to join ... assistance.\n"
        },
        {
            "type": "text/html",
            "value": "<html></html>"
        }
    ],
    "personalizations": [
        {
            "bcc": [
                {
                    "email": "noreply@site.com",
                    "name": "kratos Mars"
                }
            ],
            "to": [
                {
                    "email": "user@yahoo.com"
                }
            ]
        }
    ]
}
```

**Comment by davegallant** [comment]
> Seems like a crazy breaking change (reordering parameters) to push out to people automatically via a new package version.

It's safer to always specify the arg name when calling a function. It increases readability and order doesn't matter.
