### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by menthas** [sendgrid/sendgrid-python#783]
#### Issue Summary

The docs and examples in a bunch of places are out of date, e.g.
https://github.com/sendgrid/sendgrid-python/blob/master/examples/helpers/mail_example.py
uses `apikey` but the code has `api_key`. Also examples use `Email('....')` but the code requires `To('...')`:
```
raise ValueError('Please use a To, Cc or Bcc object.')
```

#### Technical details:

* sendgrid-python Version: master

**Comment by thinkingserious** [comment]
Thanks for the heads up! I believe we need to update the /examples directory and the USAGE.md.

**Comment by thinkingserious** [comment]
Fixed: https://github.com/sendgrid/sendgrid-python/pull/784
