### ISSUE TITLE
Link for 'Transactional Templates' in use_cases README.md broken

### ISSUE THREAD

**Issue by nguyenpk** [sendgrid/sendgrid-python#785]
#### Issue Summary

The link for transactional templates is broken in use_cases README.md due to a typo in the link.

#### Steps to Reproduce

1. Navigate to: https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md
2. Click 'Transactional Templates' link

The link is set to:
https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transational_templates.md

It should be: 
https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md

#### Technical details:

* sendgrid-python Version: 6.0.4
* Python Version: 3.7.2

**Comment by thinkingserious** [comment]
Thank you! I have fixed the link.
