### ISSUE TITLE
BadRequestsError: HTTP Error 400: Bad Request when using  substitutions

### ISSUE THREAD

**Issue by naiyoma** [sendgrid/sendgrid-python#786]
am getting bad request after adding template_id

#### Steps to Reproduce
this is the code am using

def send_mail(
        subject, content, to_emails,
        from_email=None, subs=None, template=None):

    sg_api = sendgrid.SendGridAPIClient(apikey=settings.SENDGRID_API_KEY)
    substitutions = {}

    # To do:
    #  - Make to emails accept name if provided
    #  - Handle cc and bcc
    # Format to emails in sendgrid format
    to_emails = [{'email': to_email} for to_email in to_emails]

    # If there is no from email
    # Use the settings DEFAULT_FROM_EMAIL
    if from_email is None:
        from_email = settings.DEFAULT_FROM_EMAIL
    from_email = {'name': 'me', 'email': from_email}

    # If there are substitutions and them
    # to the personalization subtitutions item
    if subs:
        for substitution in subs:
            substitutions['%' + substitution + '%'] = subs[substitution]

    data = {
        'personalizations': [
            {
                'to': to_emails,
                'subject': subject,
                'substitutions': substitutions
            },
        ],
        'from': from_email,
        'content': [
            {
                'type': 'text/html',
                'value': content
            }
        ],

        'template_id':'[template_id]'
    }

    # If template is passed set the template Id
    # This will prompt sending of email via template
   
    if template is not None:
        template = data['template_id'] 

    try:
        response = sg_api.client.mail.send.post(request_body=data)
    except HTTPError as error:
        return HttpResponse(error)

    return response

* Python Version: 3.6

**Comment by thinkingserious** [comment]
Hello @naiyoma,

When using templates, please follow [this example](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md).

Please let me know if that helps.

With Best Regards,

Elmer

**Comment by naiyoma** [comment]
@thinkingserious
example code returns :TypeError:__init__() got an unexpected keyword argument 'to_emails'

**Comment by naiyoma** [comment]
@thinkingserious 
i tried the  example code  but:
response = sg.send(message)
returns 'SendGridAPIClient' object has no attribute 'send'

**Comment by thinkingserious** [comment]
Hello @naiyoma,

It looks like you may need to update your SendGrid client. 

Please try: `pip install sendgrid-python --upgrade` to get v6.0.3. Then you should be able to use [this example](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md).

Thanks!

**Comment by naiyoma** [comment]
I upgraded sendgrid but i noticed that my `class SendGridAPIClient` lacks `def send`

**Comment by thinkingserious** [comment]
Hello @naiyoma,

What version do you see in `sendgrid/VERSION.txt`?

**Comment by naiyoma** [comment]
sendgrid==5.4.1
sendgrid-python=0.1.1

**Comment by thinkingserious** [comment]
Hello @naiyoma,

The version needed should be v6.0.3.

What happened when you ran the upgrade command?

With Best Regards,

Elmer

**Comment by naiyoma** [comment]
hey @thinkingserious the first command didn't upgrade but the second one worked

**Comment by thinkingserious** [comment]
Does the version `sendgrid/VERSION.txt` equal 6.0.3?

**Comment by naiyoma** [comment]
sendgrid==6.0.4
@thinkingserious  is it not possible to send the templete_id using sendgrid version 5

**Comment by thinkingserious** [comment]
Can you please describe your development environment? (e.g. are you using virtuanenv, docker, hosting provider, etc...).

**Comment by naiyoma** [comment]
hey @thinkingserious  i was able to get the specific error 
which was `{'errors': [{'message': 'Invalid type. Expected: string, given: array.', 'field': 'personalizations.0.subject', 'help': 'http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.subject'}]}` 
I placed a comma after the subject therefore it was returning an array and not a string

**Comment by thinkingserious** [comment]
Awesome! Thank you for the follow up :)

**Comment by naiyoma** [comment]
also one shouldn't use substitutions with transactional templates

**Comment by fabriciols** [comment]
Im having the same issue... @naiyoma how did you get this detailed error response?

**Comment by naiyoma** [comment]
```   
 try:
        response = sg_api.client.mail.send.post(request_body=data)
    except (HTTPError, python_http_client.exceptions.BadRequestsError) as error:
        return HttpResponse(error)
```
so with that you can use a print statement `print(error.body)` or pdb and still check for the `error.body`
