### ISSUE TITLE
Duplicate emails in the Personalization object are not allowed, make this obvious

### ISSUE THREAD

**Issue by tomwwagstaff-product** [sendgrid/sendgrid-python#788]
#### Issue Summary

When you add a recipient email address again as a BCC address, sending fails with:

`BadRequestsError: HTTP Error 400: Bad Request`

#### Steps to Reproduce

1. Add the same email address as a recipient and BCC.

#### Technical details:

sendgrid Version: 5.4.1
Python Version: 3.6

See this issue: https://github.com/sendgrid/sendgrid-python/issues/779

**Comment by thinkingserious** [comment]
Thanks for taking the time to post this issue @tomwwagstaff-product!

It is expected behavior for the Twilio SendGrid API to reject emails that have duplicate emails within the Personalization object. 

We should provide a meaningful error when someone attempts to add duplicate emails.

**Comment by DougCal** [comment]
Going to look into this one

**Comment by childish-sambino** [comment]
Note that in C# we now de-dupe the recipients rather than error: https://github.com/sendgrid/sendgrid-csharp/pull/991

**Comment by DougCal** [comment]
So I think I have a solution for this right now.  Do we want to de-dupe on a `Mail` object's construction, or do we want to de-dup emails whenever possible on the `Personalization` object, including on setters?  Currently, I'm doing it on a `Mail` object's construction, and whenever `Personalization.add_to`, `Personalization.add_bcc`, or `Personalization.add_cc` are called.  Essentially, I just check if the email already exists somewhere in `_tos`, `_bccs` or `_ccs`, and if so, we don't add the email.

**Comment by childish-sambino** [comment]
I think de-dupe whenever possible, but not de-dupe across to/cc/bcc; dupes are allowed between them.

**Comment by quidlab** [comment]
I am sending login details to users with personalization in bulk (say 500 users at one time). in my application 2 users can have same email.
When I send emails , if 2 users have same email, only one is delivered.
Is there a setting to ignore duplicate emails, as with personalization contents may be different.

**Comment by chriskyndrid** [comment]
The ability to disable this feature would be great. There are plenty of use cases where this behavior is unwanted. E.G. Aggregate mail batching where customers receive multiple correspondence across unique events to the same e-mail address. I'm actually surprised this feature exists at all. If you truly wanted to catch duplicates you'd need to investigate the compiled contents of the entire message and filter them that way, which would be way more accurate, if the purpose is to prevent erroneous duplicate e-mails from poor programming.

**Comment by mohankr123** [comment]
> I am sending login details to users with personalization in bulk (say 500 users at one time). in my application 2 users can have same email. When I send emails , if 2 users have same email, only one is delivered. Is there a setting to ignore duplicate emails, as with personalization contents may be different.

Same issue. Did you get any solution?
