### ISSUE TITLE
Fails to send to list when recipients are the duplicated

### ISSUE THREAD

**Issue by mdeggies** [sendgrid/sendgrid-python#789]
#### Issue Summary

When sending mail to multiple emails (a list of tuples), an empty error is thrown if any of the . email addresses in the list of tuples is repeated.

#### Steps to Reproduce

1. Run the following script:

```
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

email_list = [["hello@gmail.com", ""],
              ["hello@gmail.com", ""]]
mail = Mail(subject=subject,
            html_content=content,
            from_email=("whatever@gmail.com", ""),
            to_emails=email_list,
            )
sendgrid_client = SendGridAPIClient('secret')
try:
    sendgrid_client.send(mail)
except Exception as e:
    print('Exception: {}'.format(e))
```

See that an empty error is returned. 

My code logic is now dealing with the edge case of having duplicate emails in the to_list. It would be nice if either 1) a useful error is returned in this case, or 2) the lib dealt with this case so app logic wouldn't need to be implemented. 

#### Technical details:

* sendgrid-python Version: 6.0.4 (latest)
* Python Version: 2.7.16

**Comment by thinkingserious** [comment]
Hello @mdeggies,

We agree! Please see issue https://github.com/sendgrid/sendgrid-python/issues/788 for progress or if you would like to submit a PR.

With Best Regards,

Elmer
