### ISSUE TITLE
TypeError "name must be of type string" regression when name is Unicode string

### ISSUE THREAD

**Issue by johnpkennedy** [sendgrid/sendgrid-python#790]
#### Issue Summary

We encountered the following regression error after upgrading from sendgrid v5.6 to v6.0.3.

```
TypeError: name must be of type string.
...
  File "sendgrid/helpers/mail/email.py", line 52, in __init__
    self.parse_email(email)
  File "sendgrid/helpers/mail/email.py", line 207, in parse_email
    self.name = name
  File "sendgrid/helpers/mail/email.py", line 86, in name
    raise TypeError('name must be of type string.')
```

#### Steps to Reproduce

The following code should reproduce the problem:

```
        from_address = u"John Doe <john@example.com>"
        mail = Mail()
        mail.from_email = Email(from_address)
```

This code works in v5.6.

#### Technical details:

* sendgrid-python Version: 6.0.3
* Python Version: 2.7

In v5.6, the name setter method in the Email class (helpers/mail/email.py) was simply this:

```
    @name.setter
    def name(self, value):
        self._name = value
```

In v6, the name setter method was changed to the following:

```
    @name.setter
    def name(self, value):
        if not (value is None or isinstance(value, str)):
            raise TypeError('name must be of type string.')
```

Note that **isinstance()** is using **str** not **basestring**.

**Comment by patelnav** [comment]
@thinkingserious this is quite a serious regression. Can't pass unicode values for Email name.

**Comment by thinkingserious** [comment]
Thanks for being awesome and creating the PR for this @johnpkennedy!
