### ISSUE TITLE
Using transactional template example results in ValueError: Please use a To, Cc or Bcc object.

### ISSUE THREAD

**Issue by edcolmar** [sendgrid/sendgrid-python#796]
#### Issue Summary

Run the example here:
https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md

Results in ValueError: Please use a To, Cc or Bcc object.

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: X.X

**Comment by thinkingserious** [comment]
Hello @edcolmar,

I was not able to reproduce this error with the example provided. Could you please confirm what version of this library you are running? My tests were run on v6.0.3.

Thanks!

With Best Regards,

Elmer

**Comment by edcolmar** [comment]
This is using the latest.  It is working after adding To()

to_emails='To(to@example.com)',

**Comment by thinkingserious** [comment]
Hi @edcolmar,

Can you please provide your code? I am not able to reproduce the error with the example.

Thanks!

Elmer

**Comment by coldice** [comment]
Sample at https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md needs an update.
