### ISSUE TITLE
Change default display name

### ISSUE THREAD

**Issue by connelevalsam** [sendgrid/sendgrid-python#799]
#### Issue Summary

I just want to change the display name of the `sender`'s name.
for example, i have: info@myname.com
The name displayed will be: Info.

I want a default name like: Assleek

* django-sendgrid-v5==0.8.0
* sendgrid==6.0.4
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @connelevalsam,

You can change the from email to be `('from@example.com', 'Example From Name')`. Does that work for you?

With Best Regards,

Elmer

**Comment by connelevalsam** [comment]
Thanks for your reply.

It still didn't change.
Here's my code:

`send_mail('Request Accepted', reply, ('info@smartalaba.com', 'Smartalaba'), [mail], fail_silently=True)`

**Comment by thinkingserious** [comment]
Hello @connelevalsam,

Could you please provide me with the [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body)? Thanks!

With Best Regards,

Elmer

**Comment by connelevalsam** [comment]
I don't really get how to do that

**Comment by thinkingserious** [comment]
Hi @connelevalsam,

Please see this link: https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#viewing-the-request-body

Thanks!

With Best Regards,

Elmer

**Comment by connelevalsam** [comment]
Okay Thanks
here it is:
```
Django version 2.1.7, using settings 'smartalaba.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: Request Rejected
From: ('info@smartalaba.com', 'Smartalaba')
To: connelblaze@gmail.com
Date: Tue, 02 Jul 2019 11:51:33 -0000
Message-ID: <156206829350.5016.2413891739432056265@DESKTOP-P6L8JP6>
```

**Comment by cbouvier15** [comment]
Using ('mail', 'SENDER NAME') in the `from_mail` parameter works for me, as pointed by @thinkingserious.

Example:
```
message = Mail(
    from_email=('test@test.com', 'Custom Sender Name'),
    to_emails='to@mail.com',
    subject='Subjet',
    html_content='<strong>Example</strong>')
```

**Comment by connelevalsam** [comment]
Yeah thanks

**Comment by connelevalsam** [comment]
Yeah thanks

**Comment by coldice** [comment]
This should probably be added to the doc (readme) or a sample. The current sample for mail (https://github.com/sendgrid/sendgrid-python/blob/master/examples/mail/mail.py) just shows how to construct a body manually.

**Comment by childish-sambino** [comment]
@coldice Feel free to add an example and I can review it.

**Comment by coldice** [comment]
@childish-sambino looking closer into it, I realized I was blind ;) - there is a good full example for all parameters at https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/kitchen_sink.md and the main helper index page is listed in the mail example (L31) and in the main readme. I did not see that before, as I was just looking into the examples/mail folder.

So not sure if any change is required, maybe we could add a small sample pointing to the existing further samples. Something like this: https://github.com/coldice/sendgrid-python/blob/is-add-example/examples/mail/mail_helpers.py ?

**Comment by childish-sambino** [comment]
@coldice Works for me. I can review a PR if needed.

**Comment by josylad** [comment]
> 'Custom Sender Name'

This works well.

**Comment by josylad** [comment]
**This works well.**

> Using ('mail', 'SENDER NAME') in the `from_mail` parameter works for me, as pointed by @thinkingserious.
> 
> Example:
> 
> ```
> message = Mail(
>     from_email=('test@test.com', 'Custom Sender Name'),
>     to_emails='to@mail.com',
>     subject='Subjet',
>     html_content='<strong>Example</strong>')
> ```

**Comment by nmk0462** [comment]
You can use like this:
from_email='name <from@mail.com>'
