### ISSUE TITLE
UnauthorizedError: HTTP Error 401: Unauthorized error appears when sending e-mail

### ISSUE THREAD

**Issue by sakthips** [sendgrid/sendgrid-python#801]
#### Issue Summary

In my local it's working good. But when i deployed my Django app to nginx+gunicorn configuration. I'm getting this 401 HTTP UnauthorizedError. I'm not able to reproduce.

1. I created new API key.
2. Given Full Permission.
3. Access the SENDGRID_API_KEY via env variable.
eventhough i'm getting this error

I'm using v3 API Sendgrid-Python. Can you help to reproduce this issue.

#### Technical details:

* sendgrid-python Version: 5.2.0
* Python Version: 3.5.3
* Django==2.2.1
* gunicorn==19.9.0
* nginx version: nginx/1.10.3

**Comment by OlafvdSpek** [comment]
Tried putting the API key directly in the code?

**Comment by thinkingserious** [comment]
Hello @sakthips,

As @OlafvdSpek is alluding to (thanks for trying to help out @OlafvdSpek), the likely problem is that in your deployed app, it is likely the API Key is not getting set correctly. I'd suggest that you verify the API Key is being read correctly from your server environment variable.

With Best Regards,

Elmer

**Comment by tainguyen7597** [comment]
I am having the exact same problem with 401 HTTP UnauthorizedError and Django app/nginx+gunicorn configuration. I had verified that the environment API Key is correctly inputed. @thinkingserious I would really appreciate your support in this. Thank you!
