### ISSUE TITLE
Content-Type and other details are being sent in email while using sendgrid module

### ISSUE THREAD

**Issue by rahul3887** [sendgrid/sendgrid-python#803]
#### Issue Summary
Hi All,

Content-Type and other details are being sent in email while using sendgrid mail helper module. Below is the sample python code. Can someone please help here to debug?

#!/usr/bin/env python
import sys, traceback
from requests import *
import json
import base64
import sendgrid
from sendgrid import *
from sendgrid.helpers.mail import *

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_mail_info(api_key):
    sg = sendgrid.SendGridAPIClient(apikey=api_key)
    from_email = Email("sendgridtesting@gmail.com")
    to_email = Email("sendgridtesting@gmail.com")
    subject = "Test Email"

    msg = MIMEMultipart('alternative')

    text = "Hi!\nHow are you?\nHere is the link you wanted:\nhttps://www.python.org"
    html = """\
    <html>
      <head></head>
      <body>
        <p>Hi!<br>
           How are you?<br>
           Here is the <a href="https://www.python.org">link</a> you wanted.
        </p>
      </body>
    </html>
        """

    part1 = MIMEText(text, 'plain')
    part2 = MIMEText(html, 'html')
    
    
    msg.attach(part1)
    msg.attach(part2)
    content = Content('text/html', msg.as_string())
    mail = Mail(from_email, subject, to_email, content)
    response = sg.client.mail.send.post(request_body=mail.get())

def main():
    send_mail_info('Sendgrid-api-key************')

if __name__ == '__main__':
    main()

===========================================
Email Response
===========================================

Content-Type: multipart/alternative; boundary="===============3846481769962992750==" MIME-Version: 1.0 --===============3846481769962992750== Content-Type: text/plain; charset="us-ascii" MIME-Version: 1.0 Content-Transfer-Encoding: 7bit Hi! How are you? Here is the link you wanted: https://www.python.org --===============3846481769962992750== Content-Type: text/html; charset="us-ascii" MIME-Version: 1.0 Content-Transfer-Encoding: 7bit
Hi!
How are you?
Here is the link you wanted.

--===============3846481769962992750==--

==============================================

#### Technical details:
* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hello @rahul3887,

I'm not quite sure I understand the issue. However, I do notice that you may need to update your code to utilize the new Mail constructor signature, please [see here](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_a_single_email_to_a_single_recipient.md) for an example.

Could you please provide the [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body) so I can further assist?

With Best Regards,

Elmer
