### ISSUE TITLE
apikey parameter does not exist but is on the example code

### ISSUE THREAD

**Issue by tcullum-gpsw** [sendgrid/sendgrid-python#804]
#### Issue Summary

macOS 10.13.6
Python 3.7.0
Sendgrid 6.0.5

Code - The example given on the https://sendgrid.com/docs/for-developers/sending-email/v3-python-code-example/ page.

Error:

`Traceback (most recent call last):
  File "sendgrind.py", line 5, in <module>
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
TypeError: __init__() got an unexpected keyword argument 'apikey'`

I tried directly in the interpreter commandline and did a `help(sendgrid.SendGridAPIClient` which says that the apikey= should exist. However, when I try `api_key` I seem to bypass this error.

Could you guys/gals perhaps put a warning message at the top of the page that this is the outdated version/format? It looks like the GitHub example works and this is the old way, but there is no notice about that and the old v3 page is what pops up first on Google for examples.

**Comment by thinkingserious** [comment]
Hello @tcullum-gpsw,

Thanks for the heads up! I've put in a PR to update our documentation. 

With Best Regards,

Elmer
