### ISSUE TITLE
Considere squash merge the PRs instead of just merge to reduce the noise in the commits

### ISSUE THREAD

**Issue by lipis** [sendgrid/sendgrid-python#811]
There is no need to have all the commit messages https://github.com/sendgrid/sendgrid-python/commits/master

**Comment by thinkingserious** [comment]
That's a good idea @lipis, I believe my colleague @childish-sambino would agree :)

**Comment by childish-sambino** [comment]
1 PR = 1 Commit (to master)

**Comment by childish-sambino** [comment]
@thinkingserious You can update this in the repo settings.
