### ISSUE TITLE
SSL related error using urllib2

### ISSUE THREAD

**Issue by mwv-swappa** [sendgrid/sendgrid-python#812]
#### Issue Summary

We have started receiving the following error when trying to make sendgrid api calls to send an email using urllib2.  We have made no changes.

URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

#### Steps to Reproduce
We receive this error on some of our previously working requests, unable to trigger this directly 100% of the time.

File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

#### Technical details:

* sendgrid (3.6.3)
* Python Version: 2.7.12

**Comment by thinkingserious** [comment]
Hello @mwv-swappa,

I believe this is an issue that is being tracked by our support team. [Please open a ticket](https://support.sendgrid.com) with them. Thank you!

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this is a non-library issue.
