### ISSUE TITLE
BCC Send Not Working On SendGrid Email via Python (Django)

### ISSUE THREAD

**Issue by sgrobert** [sendgrid/sendgrid-python#814]
#### Issue Summary

Hi there, I'm new to SendGrid and only have been attempting at the API last 2 days. I have been trying to forward the email sent via a BCC rather than TO or CC  in the Email sent via SendGrid. For every email I have test-sent, the TO-email was sent successfully but never once was the BCC-email sent successfully. 

#### Steps to Reproduce

I have read the API that specifically states that as long as I insert the BCC-email within "mail_settings" > "bcc", a copy of the email will be sent (https://sendgrid.com/docs/API_Reference/api_v3.html), but none showed up. 

I've tried the examples shown in the following links:
a. https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md
b. https://github.com/sendgrid/sendgrid-python/blob/master/examples/mail/mail.py

---

But none of the above seem to work, even though I have shifted the BCC entry into the various other locations where the API support. Typically, this step will result a 500 error, so the above API step seemed to be the safest way, but it is not working still.

1. JSON settings on Python 
 ```
 message = {
            'mail_settings': {
                'bcc': {
                    'email': json_data['bcc_email'],
                    'enable': True,
                },
            },
            'personalizations': [
                {
                    'to': [
                        {
                            'email': json_data['to_email'],
                            'name': json_data['to_name'],
                        }
                    ],
                    'dynamic_template_data': {
                        'subject': json_data['subject'],
                        'email': json_data['to_email'],
                    },
                    'subject': json_data['subject'],
                }
            ],
            'from': {
                'email': json_data['from_email'],
                'name': json_data['from_name'],
            },
            "reply_to": {
                'email': json_data['reply_to_email'],
                'name': json_data['reply_to_name'],
            },
            'template_id': json_data['template_id'],
            'attachments': [
                {
                    'content': encoded,
                    'content_id': json_data['attachment_name'],
                    'disposition': 'attachment',
                    'filename': json_data['attachment_filename'],
                    'name': json_data['attachment_name'],
                    'type': 'application/pdf'
                }
            ],
        }
```

#### Technical details:

* sendgrid-python: sendgrid==6.0.5
* python: 2.7

---

Hope someone may assist me on this as I faced a number of issues and will be posting different issue docs in hopes to address them as soon as possible. Thank you!

**Comment by thinkingserious** [comment]
Hello @sgrobert,

Here is what I would try to debug:
1. Verify the value of `json_data['bcc_email']`
2. Try this:
```javascript
{
           'mail_settings': {
               'bcc': {
                   'email': json_data['bcc_email'],
                   'enable': True,
               },
           },
           'personalizations': [
               {
                   'to': [
                       {
                           'email': json_data['to_email'],
                           'name': json_data['to_name'],
                       }
                   ],
                    'bcc': [
                       {
                           'email': json_data['bcc_email']
                       }
                   ],                
                   'dynamic_template_data': {
                       'subject': json_data['subject'],
                       'email': json_data['to_email'],
                   },
                   'subject': json_data['subject'],
               }
           ],
           'from': {
               'email': json_data['from_email'],
               'name': json_data['from_name'],
           },
           "reply_to": {
               'email': json_data['reply_to_email'],
               'name': json_data['reply_to_name'],
           },
           'template_id': json_data['template_id'],
           'attachments': [
               {
                   'content': encoded,
                   'content_id': json_data['attachment_name'],
                   'disposition': 'attachment',
                   'filename': json_data['attachment_filename'],
                   'name': json_data['attachment_name'],
                   'type': 'application/pdf'
               }
           ],
       }
```

It may also be useful to view the contents of this request_body just before you send it off to ensure all the variables filled in where expected.

With Best Regards,

Elmer

**Comment by sgrobert** [comment]
Hi @thinkingserious,

Thank you on the reply.

I have been trying the above code a number of times and even changed the original BCC email address to another email for testing, but no mail was being sent out via BCC, despite the original TO email was sent. 

Are there any potential alternatives to work around this? As there is also no sort of error message to inform me of what is going wrong in this segment. 

Thank you.

**Comment by sgrobert** [comment]
Hi @thinkingserious ,

Just want to add on as I was trying to sieve out how to potentially resolve the issue. I have found that apparently the backlog on SendGrid via "Suppressions > Blocks", I found that the BCCs have gotten blocked due to the following reason:

**550 "JunkMail rejected - xtrwsxhs.outbound-mail.sendgrid.net [167.89.106.6]:60047 is in an RBL: Blocked - see https://www.spamcop.net/bl.shtml?167.89.106.6"**

This is even though I have changed across 2x different, working emails that are brand new and am a little confused how this would happen at such an early stage.

Hope you may have some idea how I might get around this issue as it is odd that BCC copies will get sorted into this category. 

Thank you!

**Comment by sgrobert** [comment]
Hi @thinkingserious ,

I have been tinkering around and have managed to somehow solved this segment. 

Thank you for your previous code that it worked. Basically there are two caveats that I found to help resolve and clean up my issue:

1. Emails are being sent but are blocked by the JunkMail clause under Spambot, which I have no clear idea how to unblock at this juncture, but sought to create a new email address to handle the re-routing. 

For code wise, essentially having the TWO parts below will be sufficient, as adding an email to Part A, will somehow caused an additional email to be sent out but any dynamic fields added via {{}} will totally not work, in this mail under mail_settings, which is pretty odd. Having Part B will just work smoothly, though sadly the previous mail allocated seemed to be locked under SPAMBot at the moment. 

**PART A:**
```
'mail_settings': {
                'bcc': {
                    'enable': True,
                },
            },
```

**PART B:**
'personalizations': [
                {
                    'to': [
                        {
                            'email': json_data['to_email'],
                            'name': json_data['to_name'],
                        }
                    ], 
                    'bcc': [
                        {
                            'email': json_data['bcc_email']
                        }
                    ],
                }
]

---

Hopefully this solution will help someone else resolve their problem in due time as it took me the last 3 days to clean it out. 

Thanks for the help nonetheless @thinkingserious ! Cheers! ;)
