### ISSUE TITLE
Inline Website Link Not Working

### ISSUE THREAD

**Issue by sgrobert** [sendgrid/sendgrid-python#816]
#### Issue Summary

Hi there,

I am currently using SendGrid's template interface to create a template email to send out. Within the template, I have attempted to utilize the "Link" option on the top right hand side of the templating interface to create a new URL link. 

The problem surfaced when I sent out a TO email and attempted to test the link created in the email, and the link just didn't work. 

---

#### Steps to Reproduce

1. Created the link through SendGrid's templating interface

<img width="847" alt="Screenshot 2019-06-17 09 05 47" src="https://user-images.githubusercontent.com/759805/59572337-2c7ce480-90df-11e9-824f-329e00b9e5b6.png">

2. Sent email to receiving TO address

3. Tested link within email and the link didn't work as apparently SendGrid appending a list of items within the URL. 

<img width="1030" alt="Screenshot 2019-06-17 09 08 02" src="https://user-images.githubusercontent.com/759805/59572440-e2483300-90df-11e9-81a7-885120ba7469.png">

I've added "Click_Tracking", "Open_Tracking" and "Ganalytics" to "True", to test out those functionalities, though I am unsure whether it did affect the URL. 

Do let me know how I am remove that "auto-appending", so that my link will actually work. 

---

#### Technical details:

* sendgrid-python: sendgrid==6.0.5
* python: 2.7

**Comment by childish-sambino** [comment]
Since this is related to the template editor and not the python lib, I suggest reaching out to the [support team](https://support.sendgrid.com/) for further assistance.
