### ISSUE TITLE
Invalid SMTPAPI header for email with subject: Video-"overvågning" på 2..?

### ISSUE THREAD

**Issue by jeffoneill** [sendgrid/sendgrid-python#822]
I've been using this Python library for a few years and everything generally works great.  However, for this particular email subject

> Video-"overvågning" på 2..?

the SendGrid console shows it as a "Drop" with the message "Invalid SMTPAPI header".  

This happens regardless of which email address I send it to (including my own email address).  I send lots of emails every day with subjects in many different languages (Chinese, etc.) and they all get sent fine.  Just this one subject has caused a problem!

I'm using Python 2.7 and the latest release of the Python library (6.0.5).

This is a msg-id of an example email message with this subject:

> yW3KMilTRz22IjZomo3I5g.filter0100p3iad2-24768-5D2CDA1C-18

Below I've copied relevant portions of my code.  Please let me know if I can provide more info to help diagnose the problem.

```
from email import header
import sendgrid
SG = sendgrid.SendGridAPIClient(SG_KEY)
data = {
    "from": ...,
    "personalizations": [
        {
        "to": [{"email": ...}],
        "subject": str(header.Header(subject, "utf-8"))   
        }
    ]
}
SG.client.mail.send.post(request_body=data)
```

**Comment by thinkingserious** [comment]
Hello @jeffoneill,

We've added this to our backlog for review, but in the meantime, I have a follow up question. If you try to make this call directly (without the library, e.g. via cURL) do you have the same issue?

With best regards,

Elmer

**Comment by onkartibe** [comment]
I have similar type of question: 

This is my simple piece of code and with subject, if we add apostrophe or single quote, it coverts in to HTML code (&#39;) at receiver end. 

```
message = Mail(
from_email=from_email,
to_emails=individual_address,
subject=title,
html_content=html_content)

sg = sendgrid.SendGridAPIClient(settings.SENDGRID_API_KEY)
response = sg.send(message)
```


Any solution around this?

**Comment by childish-sambino** [comment]
In order to properly debug this issue, please [file a support ticket](https://support.sendgrid.com/hc/en-us).
