### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by lipis** [sendgrid/sendgrid-python#823]
There are quite a few new changes, so it would be nice to make a new release.

https://github.com/sendgrid/sendgrid-python/compare/v6.0.5...master

**Comment by lipis** [comment]
A friendly ping...

**Comment by lipis** [comment]
Is there anybody out there?

**Comment by thinkingserious** [comment]
Hello @lipis,

We have a release scheduled within our current sprint :)

With best regards,

Elmer
