### ISSUE TITLE
Doesn't work with new Marketing Campaigns?

### ISSUE THREAD

**Issue by jer-tx** [sendgrid/sendgrid-python#824]
#### Issue Summary

Trying to insert new contacts using:
```

sg = SendGridAPIClient(EnvironmentAPI.get_env_var('SENDGRID_API_KEY'))

response = sg.client.mail.send.post(request_body=mail_data)
```

That ends up in the "legacy" marketing campaigns side. I opened a support ticket asking about that and it seems there's no support for the new marketing campaign with this library? I'd really rather not have 2 different ways of contacting sendgrid's api. It works just fine for basically everything else, like actually sending emails, but this one thing doesn't seem to work properly, and its a pretty big thing.

#### Technical details:

* sendgrid-python Version: 6.0.5
* Python Version: 2.7

**Comment by Lukahhh** [comment]
I also have come across this, where I'm trying to use the existing [examples](https://github.com/sendgrid/sendgrid-python/blob/master/examples/contactdb/contactdb.py) for contactdb like so:

```
        response = sg.client.contactdb.lists.get()
        
        print(response.status_code)
        print(response.body)
        print(response.headers)
```

But I'm getting a 403 from python_http_client. I guess the new/legacy marketing split has changed something, because this definitely worked a few weeks ago.

**Comment by thinkingserious** [comment]
Hello @jer-tx,

I believe you may be trying to do [this](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#add-a-single-recipient-to-a-list)? Please confirm.

Thanks!

With best regards,

Elmer

**Comment by anna-ssi** [comment]
Dear @thinkingserious, I have tried to add a recipient to the list the way that is written in the link you attached, but I get this error
`LIST ID must be integer`

**Comment by khose** [comment]
I get a _403: forbidden_ error when using `.contactdb.recipients.post()`. Same story using Postman. If I use the new _/marketing/_ endpoints, they do respond. So I'm not totally sure if this library currently supports  the new endpoints. The docs only mention _/contactdb/_ ones.

**Comment by m4k5** [comment]
Can confirm. Still not solved.

**Comment by paramono** [comment]
Sendgrid implements a [Fluent interface](https://sendgrid.com/blog/using-python-to-implement-a-fluent-interface-to-any-rest-api/), hence the API for new marketing campaigns should work just fine if you use the appropriate endpoints/verbs. You can find them in official, language-agnostic documentation for the API.

The endpoint you're looking for:
https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact

## Examples:

### Add a new contact:
```
sg.client.marketing.contacts.put(
    request_body=dict(
        contacts=[{'email': 'example@example.org'}]
    )
)
```

### Add contact to a list:
```
sg.client.marketing.contacts.put(
    request_body=dict(
        list_ids=[list_id], 
        contacts=[{'email': 'example@example.org'}]
    )
)
```
and so on

* * *

Still, none of that is mentioned in this repository - neither in the readme, nor in examples section. 

Documentation for this library needs to be updated to include information about the new API and how to use it with python.

**Comment by Urazbaev** [comment]
> Documentation for this library needs to be updated to include information about the new API and how to use it with python.

 I agree that documentation lacks any examples. Right now I'm struggling with 

`sg.client.marketing.contacts.search.post(request_body= dict(query=[{'email': 'test@gmail.com'}]))`

And get `json: invalid format`. Any ideas how to search correctly?

[SendGrid V3 Search](https://sendgrid.api-docs.io/v3.0/contacts/search-contacts)

**Comment by childish-sambino** [comment]
@Urazbaev The query value needs to a a string (SGQL string according to the docs). An example string in the docs: `email LIKE 'ENTER_COMPLETE_OR_PARTIAL_EMAIL_ADDRESS_HERE%' AND CONTAINS(list_ids, 'YOUR_LIST_IDs')`

So maybe:
```
sg.client.marketing.contacts.search.post(request_body= dict(query='email = "test@gmail.com"'))
```

**Comment by Urazbaev** [comment]
`sg.client.marketing.contacts.search.post(request_body= dict(query='email = "test@gmail.com"'))`

It worked! Thanks @childish-sambino

**Comment by aaronn** [comment]
I'm having trouble understanding how we should be structuring the Fluent Interface calls with a parameter in the url, like this API call: https://sendgrid.api-docs.io/v3.0/lists/remove-contacts-from-a-list

How can I structure the client to call this `/marketing/lists/{id}/contacts`?

**Comment by childish-sambino** [comment]
@aaronn Some examples here: https://github.com/sendgrid/python-http-client#quick-start
```
sg.client.marketing.lists._(id).contacts.delete()
```
