### ISSUE TITLE
我在登录sendGrid账号时 出现 “You are not authorized to access SendGrid, please contact ” 提示 如何解决？ 还有通过php 尝试使用sendgrid时返回202没有收到邮件 请告诉我如何使用 谢谢

### ISSUE THREAD

**Issue by burt00** [sendgrid/sendgrid-python#832]
![image](https://user-images.githubusercontent.com/30595984/63987957-961c6480-cb0c-11e9-9891-207e6021f8de.png)
php 返回的是这样的 但是我没有收到邮件

**Comment by eshanholtz** [comment]
Hello @burt00,

Can you please translate your request to English so we can better assist you?

Thanks,
Elise
