### ISSUE TITLE
Category isn't being added to emails sent

### ISSUE THREAD

**Issue by siquick** [sendgrid/sendgrid-python#837]
#### Issue Summary

I'm using the Sendgrid Python library and adding the category as described in the Kitchen Sink example. The email sends successfully but no category is recorded against the send.

Here's my code

        sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
	    from_email = Email(email='Me <my@email.com>')
    	print(from_email)
    	subject = subject
    	to_email = Email(send_to)
    	content = Content("text/html", html)
    	bcc = 'my@email.com'
    	mail = Mail(from_email, subject, to_email, content)
    	mail.category = Category('my-category')
    	response = sg.client.mail.send.post(request_body=mail.get())
    	

  [1]: https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/kitchen_sink.md

**Comment by eshanholtz** [comment]
Hi @siquick,

Can you provide a little more info so I can try to reproduce the issue? What version of the sendgrid-python library are you using?
