### ISSUE TITLE
Marketing Campaigns Stats | API 

### ISSUE THREAD

**Issue by MIKNOTAURO** [sendgrid/sendgrid-python#843]
Is there a way to get the following stats per campaign
recipients/opened
recipients/clicked

requests
bounces
unsubscribes
spam reports

?

**Comment by childish-sambino** [comment]
I'm not seeing any API directly linked to MC stats. Are you able to use the email activity API to get this data? https://sendgrid.api-docs.io/v3.0/email-activity
