### ISSUE TITLE
How to track sent email?

### ISSUE THREAD

**Issue by waltersdmh** [sendgrid/sendgrid-python#847]
#### Issue Summary

Hi,

I'd like to track the status of a sent email, like success, clicks, opens etc. Is this possible? 

I'm able to extract the X-Message-Id from my response header but am finding the documentation abit unclear on how to do anything further. Is web-hooks the thing to do? I couldn't find documentation or any examples of these.

#### Steps to Reproduce
1. How I send email:

```
message = Mail(
    from_email=from_email,
    to_emails=recipient_list,
    subject=subject,
    html_content=render_to_string('template.html', html_context)
  )
```
```
try:
    sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
    response = sg.send(message)
     return response
except Exception as e:
    print(str(e))

```
2. Response
`response.headers.get_all('X-Message-Id')`

#### Technical details:

* sendgrid-python Version: 6.1.0
* Python Version: 3.5

**Comment by fannigurt** [comment]
Hi! It's easy:
First, you need to allow open/click tracking. 
`Settings - > Tracking -> Click Tracking`
`Settings - > Tracking -> Open Tracking`
Sendgrid obfuscates your links in an email with their own tracker link. 
After a user clicks on such link Sendgrid send you postback (HTTP POST request) on your endpoint. 
Then you need to set up your postback endpoint and types of postback that you want to receive:
`Settings -> Mail Settings -> Event Notification` 
Specify your endpoint and select the types of notifications.

Pay attention, Sendgrid can't send postback on your localhost: port
You have several options:
1) Deploy solution with logging to see event formats and play with this feature.
2) Use [Ngrok](https://ngrok.com) it could proxy postbacks to your localhost. It's super cool for development.
3) Use online services to receive postbacks: ex. [requestbin.com](https://requestbin.com)

In your app, you could match X-Message-Id that you've already stored in your DB with postback data.

**Comment by eshanholtz** [comment]
Hi @waltersdmh 
The response above is correct. If you have any further questions about how to set up click tracking, please feel free to contact [support](https://support.sendgrid.com).

**Comment by colindjk** [comment]
@fannigurt Is the send `SendGridApiClient.send` function executed serially?

Basically: Is there a chance that a webhook could be sent before the request to send and email actually returns a response (with the ID)?

I'm mainly concerned here about persistence issues + having webhooks reference messages that aren't there (yet).
