### ISSUE TITLE
Getting bad request error while trying to send batch emails.

### ISSUE THREAD

**Issue by Erenaliaslangiray** [sendgrid/sendgrid-python#852]
#### Hi! I am getting bad request error from sendgrid api while trying to send multiple (batch) emails.

I am using python 3.6 and trying to use sendgrid api and doing exact same operation as send_multiple_emails_to_multiple_recipients.md shows. With same codes I got no error but when i change html message, I got error. My html template is a bit huge (32.000 chars). When I make my template smaller like 9000 chars api works again. So what I got here is the size creates problem with api. When I change my sending mechanism to sendgrid single mail send example(The base example code provided from sendgrid python api)  things work, I could send my 32k char long mail. But for better performance, I need to send my big email with batch send method. So how can we fix this? Is there a size limit on a sendgrid batch api that I didnt saw?

Can you please enlighten me? 

Technical details:
* sendgrid-python Version: master
* Python Version: 3.6

**Comment by childish-sambino** [comment]
There are limitations to the size of the email and the number of recipients. Docs here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations

That said, could you provide more details about the error you're seeing? Maybe just provide the full error response payload here?
