### ISSUE TITLE
The Mail class does not provide a way to specify sender's name.

### ISSUE THREAD

**Issue by timuster** [sendgrid/sendgrid-python#859]
#### Issue Summary

The 'Mail' class does not have an option to specify the sender's name. Other SendGrid libraries, like the NodeJS library, have the option to specify the sender's name along with the email address. However, no such option exists for the Python library. There should exist a parameter, 'from_name' for example, to allow end-users to add the name to the request body. 

Here's how it's done in the NodeJS library for example: 

```
sendgrid.send({
  to: 'you@yourdomain.com',
  from: {
      email: 'example@example.com',
      name: 'Sender Name'
  },
  subject: 'Hello World',
  text: 'My first email through SendGrid'
});
```

**Comment by SameeranB** [comment]
Hi! I would like to take up this issue if no one is already working on it. I'm new to this codebase, so I might need a little help if that's okay :)

**Comment by sandeepsajan0** [comment]
@SameeranB Are you working on it or may I move forward for this?

**Comment by SameeranB** [comment]
Hey @sandeepsajan0, please go ahead...

**Comment by sandeepsajan0** [comment]
@timuster It already has a functionality to pass a name with email in a tuple. Take a look [here at L664](https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/mail.py#L664) It'll pass the name as 2nd value of tuple to [here at L27](https://github.com/sendgrid/sendgrid-python/blob/5f251e868ca932fd28f8900b2f600ae0c9e6a42d/sendgrid/helpers/mail/email.py#L27).
You can pass it like this 
```
...
from_email=("from_email@mail.com", "from_email_name"),
...
```
