### ISSUE TITLE
Underused Mail Setting Retirement & sendgrid-python module [ Question ]

### ISSUE THREAD

**Issue by artempronevskiy** [sendgrid/sendgrid-python#861]
#### Issue Summary
Hello. We use sendgrid==5.6.0 python module and we don't want to upgrade to the latest module version by some reasons. We received a letter with info about [Underused Mail Setting Retirement](https://sendgrid.com/docs/ui/account-and-settings/retired-mail-settings/). Will the change in API affect the sendgrid-python module and its usage? Thanks.

#### Technical details:

* sendgrid-python Version: 5.6.0
* Python Version: 2.7

**Comment by eshanholtz** [comment]
Hi @artempronevskiy,

Yes, the sunset of features in the underlying API will render that functionality of the `sendgrid-python` module obsolete. If you are not using those features, then you should have no problem continuing your use of the module. If you were, then attempting to use those features via the `sendgrid-python` helper library will fail, and you should follow the recommended action listed next to the deprecated feature in the link you posted.
