### ISSUE TITLE
sendgrid 5.6.0 sending blank templates when params have been provided

### ISSUE THREAD

**Issue by RAcharya1** [sendgrid/sendgrid-python#867]
Sendgrid sends out blank template when proper parameters have been provided for personalization.  The rate of error is high where two emails are sent to the recipient using templates wherein one of the email has no details populated in the template and the second email to the same recipient has the templates properly populated.

This issue happens with v5.6.0.  We cannot update to the latest because that would require a lot of regression testing to be done if changing our code to use the new 6.1.0 library version.

Ran numerous tests were I was sending email for 10 test users using templates and personalization.  Every user got two copies of the email wherein one had no fields populated in the email and the second email possibly had the fields populated.

I was able to track down the issue to the helpers/mail/mail.py library, in the Mail constructor.
The following declaration creates an empty personalization record with the recepient's address and adds it to the _personalization list. 
        if to_email:
            personalization = Personalization()
            personalization.add_to(to_email)
            self.add_personalization(personalization)

In our script, we are instantialing the Mail class and doing the following
             mail = Mail(from_email, subject, to_email, content)
             mail.template_id = templateid
             p = Personalization()
             p.dynamic_template_data = params
             -- other initializations ---
             p.add_to(to_email)
             mail.add_personalization(p)

at this stage a properly populated personalizations are added to the already existing empty personalization object.  And when the data is sent to sendgrid, we end up getting two emails for each recepient.

Temporarly, did the following in the mail.py sendgrid library to overcome the issue.
        #if to_email:
        #    personalization = Personalization()
        #    personalization.add_to(to_email)
        #    self.add_personalization(personalization)

After doing the above, reran for the same 10 users. All 10 users got emails with fields properly populated.

### Technical details:
* sendgrid-python version: 5.6.0
* python version: 3.6/3.7

**Comment by eshanholtz** [comment]
Hi @RAcharya1,

Glad to see you were able to find a workaround! Unfortunately we are no longer making updates to the v5.x versions of this helper library. It looks like this issue was fixed in more recent versions of the library, but if you are unable to upgrade to the version that fixes this issue, then there is little we can do to help you. I suggest you continue to use this workaround until you are able to upgrade to a more recent version of this library.

**Comment by pgigindia** [comment]
I am using SendGrid v6.9.0 and having the same issue, any updates here?
