### ISSUE TITLE
Building 6.1.1 fails `config.yml`

### ISSUE THREAD

**Issue by xfoxawy** [sendgrid/sendgrid-python#868]
### Issue Summary
Building the 6.1.1 version with NixOS Packages fails 

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
running build_ext
error: [Errno 2] No such file or directory: '/private/var/folders/bn/fl964j9j6vj937b6q9wmj2lw0000gp/T/nix-build-python3.7-sendgrid-6.1.1.drv-0/sendgrid-6.1.1/sendgrid/helpers/inbound/config.yml'
builder for '/nix/store/incx71lxq9wis1kf8hh4134lfdnk1kg7-python3.7-sendgrid-6.1.1.drv' failed with exit code 1
```

### Technical details:
* sendgrid-python version: 6.1.1
* python version: 3

**Comment by eshanholtz** [comment]
Hi @xfoxawy 

Thanks for pointing this out! I've gone ahead and updated the `MANIFEST.in` file to make sure the `config.yml` file gets included in future releases. The change will be reflected in the next release scheduled for 2020-03-04.
