### ISSUE TITLE
creating subuser returns 403 FORBIDDEN

### ISSUE THREAD

**Issue by sunandchakradhar** [sendgrid/sendgrid-python#873]
Request to create subuser returns a 403 FORBIDDEN, I have tried using the python sdk version 6.1.0, 6.1.1 and 6.1.2.  I verified the scopes for the specific API_KEY there exists permissions related to sub users 
i,e `"subusers.create","subusers.read","subusers.update","subusers.delete"`

I have tried using
```
    self.sg = sendgrid.SendGridAPIClient(mail_config['api_key'])

    data = {
        "email": email,
        "username": username,
        "password": uuid.uuid4().hex
    }
    ips = self.get_ips()
    if len(ips) == 0:
        raise MailerException("Failed to create Subuser - Missing ips", 400)
    data['ips'] = ips
    try:
        response = self.sg.client.subusers.post(request_body=data)
        resp = response.body
        resp = json.loads(resp) 
    except Exception as e:
        logging.error("Failed to create subuser" + str(e))
        logging.error(e.body)
```
__Error log:__
```
10:39:48 ERROR:root: Failed to create subuserHTTP Error 403: FORBIDDEN
10:39:48 ERROR:root: b'{"errors":[{"message":"User does not have permission to create subuser"}]}'
10:39:48 ERROR:root: Traceback (most recent call last):
  File "/opt/app/mailer.py", line 283, in create_user
    response = self.sg.client.subusers.post(request_body=data)
  File "/usr/local/lib/python3.7/site-packages/python_http_client/client.py", line 262, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/python_http_client/client.py", line 178, in _make_request
    raise exc
python_http_client.exceptions.ForbiddenError: HTTP Error 403: FORBIDDEN
```

**Comment by sunandchakradhar** [comment]
Tried below curl code to receive the same response.
curl -i --request POST \
> --url https://api.sendgrid.com/v3/subusers \
> --header 'Authorization: Bearer YOUR_API_KEY_HERE' \
> --header 'Content-Type: application/json' \
> --data '{"username": "test","email": "foo@bar.com","password": "password","ips": ["X.X.X.X"]}'

Response:
HTTP/1.1 403 FORBIDDEN
Server: nginx
Date: Fri, 06 Mar 2020 10:46:12 GMT
Content-Type: application/json; charset=utf8
Content-Length: 74
Connection: keep-alive
Access-Control-Allow-Methods: HEAD, GET, PUT, POST, DELETE, OPTIONS, PATCH
Access-Control-Max-Age: 21600
Access-Control-Expose-Headers: Link, Location
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: AUTHORIZATION, Content-Type, On-behalf-of, x-sg-elas-acl, X-Recaptcha, X-Request-Source
Content-Security-Policy: default-src https://api.sendgrid.com; frame-src 'none'; object-src 'none'
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
X-Ratelimit-Remaining: 0
X-Ratelimit-Limit: 1
X-Ratelimit-Reset: 1583491575

{"errors":[{"message":"User does not have permission to create subuser"}]}

**Comment by childish-sambino** [comment]
Do you have a **Pro** or **Premier API** plan or an **Advanced Marketing Campaigns** plan?

https://sendgrid.com/docs/ui/account-and-settings/subusers/

**Comment by sunandchakradhar** [comment]
We have a Pro account. will verify the user count and recheck.

**Comment by eshanholtz** [comment]
It's also worth checking that the API key used has the right permissions for managing subusers.
