### ISSUE TITLE
You are not authorized to access SendGrid, please contac

### ISSUE THREAD

**Issue by nu11secur1ty** [sendgrid/sendgrid-python#874]
I've reset my password 100 times, WTF dear friends? I lose my patient :( If all your services are the same... .... :D Please CHEC OUT DEAR FRIENDS :D

**Comment by nu11secur1ty** [comment]
I've reset my password 100 times, WTF dear friends? I lose my patient :( If all your services are the same... .... :D

**Comment by nu11secur1ty** [comment]
How do you want me to buy something from your organization? :D
Now I'm serious!!! PLEASE CHECK THE ISSUE!
BR V.Varbanovski SAIE

**Comment by childish-sambino** [comment]
This is not something that can be fixed in this library and is an issue that only support can resolve. Please submit a request for login support here: https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by thinkingserious** [comment]
Hello @nu11secur1ty,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by nu11secur1ty** [comment]
Ok, friend, I hope this will happen! thank you!
BR

**Comment by childish-sambino** [comment]
@nu11secur1ty Let me know if you've not received a response and your email in case I need to follow-up.

**Comment by NikhilP97** [comment]
@childish-sambino It's been 3 days and I still haven't received a response on mail. Could you please help me with the issue. I'm facing the same issue as mentioned above.

**Comment by childish-sambino** [comment]
@NikhilP97 Please post or email me your SendGrid username and the email you submitted using this form: https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by oweskeez** [comment]
Greetings! Just ran into this issue and reached out using the form linked above. Thank you!

**Comment by CloudMojoTech** [comment]
I have been using SendGrid for the last 6 months but today suddenly it is giving an error on logon "You are not authorized to access SendGrid"

**Comment by Hamaad-Siddiqui** [comment]
Just made an account and it says "You are not authorized to access SendGrid, please contact Support." 
Like why, Dont you want me to use your service?!

**Comment by ali01imani01** [comment]
Same problem 
they never fix this - _ -
