### ISSUE TITLE
Got an unexpected keyword argument 'apikey' (out of date README?)

### ISSUE THREAD

**Issue by c0bra** [sendgrid/sendgrid-python#875]
### Issue Summary

Following the docs in the README, if you specify the apikey as a keyword argument like so:

```python
sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
```

You will get the error:

    Got an unexpected keyword argument 'apikey'

Other docs in this library show passing in api key as a regular argument, which works

```python
sendgrid.SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
```

Perhaps the docs need to be updated?

**Comment by childish-sambino** [comment]
Looks like both `api_key` and `apikey` used to be supported but now it's only `api_key` as of this https://github.com/sendgrid/sendgrid-python/pull/769

I've updated the README.
