### ISSUE TITLE
Email mentioned in From - Got marked as SPAM

### ISSUE THREAD

**Issue by anandandy139** [sendgrid/sendgrid-python#876]
I am using sendgrid for sending transactional emails to our customers. But with a fresh email created and after sending 500 emails. The email is now marked as spam. Could you help me here with why it could have happened?

The emails which i was sending through email portal is now getting send in SPAM.

**Comment by childish-sambino** [comment]
Best to start here: https://sendgrid.com/blog/10-tips-to-keep-email-out-of-the-spam-folder/
