### ISSUE TITLE
GCP Cloud Function - Python - Templates not working

### ISSUE THREAD

**Issue by lsherry8375** [sendgrid/sendgrid-python#879]
### Issue Summary
I am not able to utilize a Cloud Function (not via Firebase but just using a standard cloud function) on the GCP platform to utilize a dynamic template
I have used the standard code below
When I use the the plain html basic email code, it works fine
When I add the line message.template_id = 'MY TEMPLATE ID' I do not get errors but the email does not get sent
I am using sendgrid>=6.0.5 in the requirements.txt

```python
import os
import json
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='from_email@example.com',
    to_emails='to@example.com',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
}
message.template_id = 'd-f43daeeaef504760851f727007e0b5d0'
try:
    sendgrid_client = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    response = sendgrid_client.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.message)
```

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-python version:
* python version:

**Comment by thinkingserious** [comment]
Hello @lsherry8375,

It looks like you are missing the `dynamic_template_data`. Please see [this example](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md).

If that is not the issue, could you please post the [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body) along with the contents of your template so that we may try to reproduce?

Thanks!

With best regards,

Elmer

**Comment by lsherry8375** [comment]
Elmer & Google

YOU GUYS ARE THE BEST!!!

WE LOVE GOOGLE AND THE GCP PLATFORM!!!

THANKS A MILLION FOR YOUR HELP!!!

**Comment by lsherry8375** [comment]
Dear Elmer

It appears when I have a very simple dynamic template everything works
perfectly

<html><head>
    <title></title></head><body>
Hello {{ name }},<br /><br/>
I'm glad you are trying out the template feature!<br /><br/>
I hope you are having a great day in {{ city }} :)<br /><br/></body></html>


However, when I copy a design from the send grid image gallery with images
and complex styling and use this as a template.  I get a success but never
receive the email.

here is the json.dumps output

{
insertId: "000000-d691352b-77d1-446e-aad8-65f9b4762108"
labels: {…}
logName: "projects/focused-veld-203115/logs/cloudfunctions.googleapis.com
%2Fcloud-functions"
receiveTimestamp: "2020-03-26T18:55:44.985199675Z"
resource: {
labels: {…}
type: "cloud_function"
}
severity: "INFO"
textPayload: "json.dumps Output"
timestamp: "2020-03-26T18:55:42.557Z"
trace:
"projects/focused-veld-203115/traces/953fb0cd70d045b58c9371ac7f036b6c"
}

here is the email design
[image: image.png]

**Comment by thinkingserious** [comment]
Hello @lsherry8375,

Thank you for the kind words!

With respect to the template, I believe you may be using the [marketing templates](https://sendgrid.com/solutions/email-marketing-templates/) instead of the [transactional templates](https://sendgrid.com/solutions/transactional-email-templates/). Could you please verify? Thanks!

With best regards,

Elmer

**Comment by lsherry8375** [comment]
Dear Elmer,

I was using a cloud function correctly for the transactional templates
The code was correct but the pre-designed templates (with images, styling,
and fonts) supplied by sendgrid in their Design library immediate get
filtered out by our gmail spam filter; they never even arrived to spam.
I was able to get the email working by using a simplified, clean html
template

It would be great if the sendgrid partner could add a few simplified html
templates for gmail and modern spam emailing systems

Thank-you Google - Your engineers are the best! This is why we love Google

**Comment by thinkingserious** [comment]
Thank you for the follow up @lsherry8375!

I will pass along your feedback to the product team with respect to the Design library.

For SPAM related issues, please check out [this documentation](https://sendgrid.com/docs/glossary/spam). 

Thank you!

With best regards,

Elmer
