### ISSUE TITLE
not receiving mails with dynamic template data

### ISSUE THREAD

**Issue by altaf-navalur** [sendgrid/sendgrid-python#883]
I am able to send normal email, but when I try to send an email with dynamic template, I get status code as 202, but the email is never delivered. I checked my spam folder & its not there either. I also checked, Activity feed, I don't see any entry over there either

### Code Snippet
```python
            message = Mail(
                from_email='wish@ericatechnologies.in',
                to_emails=self.default_to_email,
                html_content='<strong>and easy to do anywhere, even with Python</strong>')
            message.dynamic_template_data = {
                # 'subject': 'Testing Templates',
                'name': 'Some One'
                # 'city': 'Denver'
            }
            message.template_id = self.template_id
            response = self.client.send(message)
```

### Exception/Log
```
response code is 202
```

### Technical details:
* sendgrid-python version: 6.2.2
* python version: 3.6

**Comment by thinkingserious** [comment]
Hello @altaf-navalur,

Thanks for reaching out!

Can you please verify your `template_id` is correct and that you have a [version set to active](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/versions.html)?

With best regards,

Elmer

**Comment by margot-bonilla** [comment]
I don't receive the email either. I checked the template_id and it's correct and active.

**Comment by Cosi-Admin** [comment]
Turns out the the domain from which I was trying to send was not whitelisted by send grid. Surprisingly, it never threw any error or warning & I ended up spending too much time trying to figure it out. When I created a new account to start fresh, then it threw error of domain not being whitelisted. It worked after that.
