### ISSUE TITLE
403 Forbidden on 'Retrieve all recipients on a List'

### ISSUE THREAD

**Issue by w1-naserieh** [sendgrid/sendgrid-python#889]
### Issue Summary
When I try to get all reciptiens from a list, it returns a forbidden response.
This also happens in Postman.
My API key has full access and works on every endpoint except /contactdb/lists.

### Steps to Reproduce
https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md#retrieve-all-recipients-on-a-list

### Code Snippet
```python
    # Fetch recipients from list.
    def list_recipients(self, list_id):
        params = {
            'page': '1',
            'page_size': '1',
        }
        try:
            response = self.sg.client.contactdb.lists._(list_id).recipients.get(query_params=params)
        except Exception as e:
            print(e)
```

### Exception/Log
```
HTTP Error 403: FORBIDDEN
```

### Technical details:
* sendgrid-python version: sendgrid==6.3.0
* python version: Python 3.7.5

**Comment by w1-naserieh** [comment]
Still not solved, can anyone look into this please.

**Comment by childish-sambino** [comment]
Think this comment will help: https://github.com/sendgrid/sendgrid-nodejs/issues/957#issuecomment-535584964

Basically, use the new `/marketing` APIs instead of the legacy `/contactdb` APIs.

**Comment by tagawa** [comment]
Thanks @childish-sambino. I was having the same problem but using ```/marketing``` seemed to fix it.

E.g. the following didn't work for me:

    response = sg.client.contactdb.lists.get() 

but this does:

    response = sg.client.marketing.lists.get()

**Comment by tagawa** [comment]
Just for the record, the workaround here works but it looks like other code that uses the legacy API could be affected too, so I made a broader issue for that: #897
