### ISSUE TITLE
how to solve error on library not found 

### ISSUE THREAD

**Issue by soumilshah1995** [sendgrid/sendgrid-python#890]
Hello this is for everyone who has error saying module not Found 
How to make it work 

app/
----->demo
------>sendgrid folder 

download the zip file and copy just the folder and paste it in you directory where the file lies 
this should work 

it seems like problem with this is Path its not able to find the path 

either you can manually do sys.path.append()
or use this hack

**Comment by childish-sambino** [comment]
Thanks for the info @soumilshah1995
