### ISSUE TITLE
Send transactional template to multiple recipients

### ISSUE THREAD

**Issue by stockcj** [sendgrid/sendgrid-python#899]
### Issue Summary
Is it possible to use transactional templates and send to multiple recipients that have their own dynamic data? If it is possible it would be great if an example could be added to the documentation.

I'm doing this currently by creating a message for each recipient individually, and then sending individually. What I'd like to do is a cross between the [sending multiple emails to multiple recipients](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_multiple_emails_to_multiple_recipients.md) example and the [transactional templates example](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md).

This is my current solution:

```
import csv
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, To

key = MY_KEY
sg = SendGridAPIClient(key)

with open("test.csv") as csv_file:
    recipients = [
        {k: v for k, v in row.items()}
        for row in csv.DictReader(csv_file, skipinitialspace=True)
    ]

for recipient in recipients:
    message = Mail(from_email="from_email@example.com", to_emails=recipient["email"],)
    message.dynamic_template_data = {
        "name": recipient["name"],
        "dummy": recipient["dummy"],
    }
    message.template_id = MY_TEMPLATE_ID
    try:
        response = sg.send(message=message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e)
```
I'd like to be able to submit this all as one job though.

**Comment by childish-sambino** [comment]
Yup, that's totally possible. You'd basically be merging the two examples that you've linked.

May be simplest to use [sending multiple emails to multiple recipients](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_multiple_emails_to_multiple_recipients.md) as a starting point and replace `substitutions` with `dynamic_template_data` and then add your `template_id`.

**Comment by apanagar** [comment]
> Yup, that's totally possible. You'd basically be merging the two examples that you've linked.
> 
> May be simplest to use [sending multiple emails to multiple recipients](https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_multiple_emails_to_multiple_recipients.md) as a starting point and replace `substitutions` with `dynamic_template_data` and then add your `template_id`.

I tried this but got the following error 
`TypeError: __init__() got an unexpected keyword argument 'dynamic_template_data'`

Is there a working example somewhere of the sendgrid v3 syntax for sending a message to multiple recipients using personalization?

**Comment by childish-sambino** [comment]
Ack, you're right. I'll look into an update to make this simpler.
