### ISSUE TITLE
You are not authorized to access SendGrid. 

### ISSUE THREAD

**Issue by monicayokogawa** [sendgrid/sendgrid-python#902]
I’ve been attempting to login into my client’s account and I’ve been getting a message of “you are not authorized to access SendGrid, please contact Support”. 

Since I can’t login, I can’t contact support. 

SendGrid sent me billing a day after I filled the login issue and sent an email to billing. 

I have used another account to submit the ticket since I can’t through this account. 

The whole website is based on SendGrid’s API and also all of our Marketing campaigns. 

Need to enable my account’s access again ASAP. 
![0D504B94-0E21-4768-ABED-95C731C9AF85](https://user-images.githubusercontent.com/59889639/83949491-b5f25e80-a7e9-11ea-9ce8-69e048c12d14.jpeg)

**Comment by childish-sambino** [comment]
https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md

> If you have an issue logging into your Twilio SendGrid account, please read this [document](https://sendgrid.com/docs/ui/account-and-settings/troubleshooting-login/). For any questions regarding login issues, please contact our [support team](https://support.sendgrid.com).
