### ISSUE TITLE
Using `get` as method name, a dangerous practice

### ISSUE THREAD

**Issue by lucasgnavarro** [sendgrid/sendgrid-python#906]
https://github.com/sendgrid/sendgrid-python/blob/6fe3d3c78e9a9aeb498d588529600af8018b63ab/sendgrid/helpers/mail/email.py#L238

This is dangerous, why you are using that method name? Could be confused with https://docs.python.org/3/library/stdtypes.html#dict.get

**Comment by childish-sambino** [comment]
I've not seen this confusion in my python usage. I see `get` as a method name being used 56 times in this repo. I'm inclined to consider this a non-issue given that `get` is not a reserved word; it's just a method name on a common python type.

**Comment by lucasgnavarro** [comment]
Yeah, it was used 56 times, but that doesn't mean that is correct. 

> In the face of ambiguity, refuse the temptation to guess.

**Comment by childish-sambino** [comment]
My point being it's used in abundance and without issue in this repo. I've seen no reference of this being a bad practice.
