### ISSUE TITLE
Dynamic Template Error:  sending multiple message to multiple recipents (Python)

### ISSUE THREAD

**Issue by Ptorres91** [sendgrid/sendgrid-python#909]
Hello everyone, i'm following this example with python (https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/send_multiple_emails_to_multiple_recipients.md)  to send multiple messages to multiple recipents using dynamic templates, but i'm getting this error:

### Exception/Log
```
# TypeError                                 Traceback (most recent call last)
<ipython-input-77-3e8056bd5ca4> in <module>
     10            'url': 'https://example.com/test0',
     11        },
---> 12        subject='Override Global Subject'),
     13     To(email='test+to1@example.com',
     14        name='Example Name 1',

TypeError: __init__() got an unexpected keyword argument 'dynamic_template_data'
```

What i'm doing wrong?

Thanks

**Comment by eshanholtz** [comment]
Looks like this is the same issue as #899, which is solved in #908 and will be included in the next release on 2020-06-24
