### ISSUE TITLE
SSLError: The read operation timed out

### ISSUE THREAD

**Issue by houmie** [sendgrid/sendgrid-python#91]
We just have sent out 270 emails via Sendgrid's APi using this library when we got the exception

`SSLError: The read operation timed out`

This is not great, as its hard to say who has received it.
What can be done to fix this please?

Thanks,
Houman

**Comment by Tyrdall** [comment]
I'm experiencing the same issue, but only from time to time. Maybe once or twice a week, while searching for recipients or while requesting a recipient's lists, and we are calling your API a lot. Are there any performing issues regarding your API?

**Comment by thinkingserious** [comment]
Hello @Tyrdall,

The best place to discover SendGrid's system health is here: http://status.sendgrid.com

If you happen to catch an issue soon after it happens, you can always reach out to our support team directly at https://support.sendgrid.com.

Thanks!

With Best Regards,

Elmer
