### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by asimsheikhviion** [sendgrid/sendgrid-python#910]
Issue Summary
Hello, I'm sorry when I log in my account it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.

Steps to Reproduce
My email is asim@viiontech,com
After I sign up, it shows error as mentioned in title
I am unable to login and cannot launch ticket.
**I have a paid account**
**i have already submitted the issue on below link last week and this week also but no response
very poor support from send grid**

https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by rohit0803** [comment]
Hi,
Was facing the same issue since last 4 days and then after many tries, the account gets created but now I am not able to use any API, getting 403 on Send mail API.
My email id is mridul.gupta@innovaccer.com
**I have a paid account too**

**Comment by thinkingserious** [comment]
Hello @asimsheikhviion,

Please submit your request [here](https://github.com/sendgrid/sendgrid-nodejs/issues/1149). Or, navigate to https://support.sendgrid.com and click on the `Trouble Logging In` prompt under `Login & Contact Support` for additional options to submit tickets without the need to log in. 

Please note that our support team is pretty backed up, so there may be a delayed response.

Thanks!

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @asimsheikhviion,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
