### ISSUE TITLE
Error in importing Sendgrid library

### ISSUE THREAD

**Issue by TheShivamChand** [sendgrid/sendgrid-python#916]
### Issue Summary
I installed the sendgrid library and while importing the module, I am getting ModuleNotFound Error.

### Exception/Log
```
File "send_sendgridemail.py", line 2, in <module>
from sendgrid import SendGridAPIClient
File "/home/shivam/PycharmProjects/venv/lib/python3.6/site-packages/sendgrid/__init__.py", line 21, in <module>
from .helpers.eventwebhook import * # noqa
File "/home/shivam/PycharmProjects/venv/lib/python3.6/site-packages/sendgrid/helpers/eventwebhook/__init__.py", line 1, in <module>
from ellipticcurve.ecdsa import Ecdsa
ModuleNotFoundError: No module named 'ellipticcurve'

```

### Technical details:
* sendgrid-python version: 6.4.0
* python version: 3.6

I had to switch to a previous version

**Comment by whoek** [comment]
Exactly the same issue on my side

using sendgrid:  6.4.0
python:    3.7

It worked OK yesterday on version 6.3.1

**Comment by raymondfx** [comment]
why don't they just make this library work on all versions of python?

**Comment by TheShivamChand** [comment]
@whoek They forgot to add one dependency.
Just add `pip install starkbank-ecdsa` and it will work properly with the latest version.

**Comment by raymondfx** [comment]
> pip install starkbank-ecdsa

Thanks, A lot, this solution worked

**Comment by childish-sambino** [comment]
Duplicates #913
