### ISSUE TITLE
You are not authorized to access SendGrid

### ISSUE THREAD

**Issue by HanSeo0507** [sendgrid/sendgrid-python#923]
I signed up through the Github Student Pack. After signing up, I logged out and logged in again, but you are not authorized to access SendGrid.

My email is khan3618@naver.com and I tried to contact you about the problem by using the khan3618@naver.com email from support.sendgrid.com about the error that occurred about 2 weeks ago, but I couldn't get it. I contacted you again through hishge4242@gmail.com, but I still haven't heard from you. Please support.
![Picture](https://user-images.githubusercontent.com/56479293/87224610-a86c5d80-c3c1-11ea-8e8d-c5606cf3b215.PNG)

**Comment by childish-sambino** [comment]
https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md

> If you have an issue logging into your Twilio SendGrid account, please read this [document](https://sendgrid.com/docs/ui/account-and-settings/troubleshooting-login/). For any questions regarding login issues, please contact our [support team](https://support.sendgrid.com).

**Comment by thinkingserious** [comment]
Hello @HanSeo0507,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by childish-sambino** [comment]
It sounds like your account status might be under review. You should have received [a notice](https://sendgrid.com/docs/ui/account-and-settings/account-under-review/) in your e-mail with more details.

If you would like to discuss it, please respond to the email you received regarding the notice. 

If you cannot find this e-mail, we ask our customers do the following:

> 
> 1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
> 2. Click on Trouble Logging In
> 3. Click "I am having a different log in issue"
> 
> To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

Support cannot assist in reactivation of banned accounts.

Hope this helps!
Twilio SendGrid Team

**Comment by HanSeo0507** [comment]
After posting the issue, I saw the answers and received the inquiry through the following method.

> 1. Go to support.sendgrid.com
> 2. Click on Trouble Logging In
> 3. Click "I am having a different log in issue"
> To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

However, 2 weeks after receiving it, I still haven't received the relevant mail and answers.
