### ISSUE TITLE
Feature Request: Implement Request Logging Options

### ISSUE THREAD

**Issue by LaikaN57** [sendgrid/sendgrid-python#927]
### Issue Summary
We should implement request logging. SendGrid support will frequent want this information when helping customers debug their application. This information should include what API they are calling, what response code, and what error message we get back.

I have created an [issue](https://github.com/sendgrid/python-http-client/issues/141) with the underlying [sendgrid/python_http_client](https://github.com/sendgrid/python-http-client) repo, but also wanted to create one here as well in-case it was a more appropriate place to do so.

I welcome feedback and would like to know if the community has any objections to adding dependencies on the logging library.

### Technical details:
* sendgrid version: 6.4.1
* python-http-client version: 3.2.7
* python version: 3.7.8

**Comment by LaikaN57** [comment]
If the upstream `python_http_client` package does not want to implement the feature we may also be able to do something similar to https://github.com/DataDog/datadog-lambda-layer-python/blob/master/datadog_lambda/patch.py#L58-L66

**Comment by childish-sambino** [comment]
Closing as I'm fine with the changes just going in `python_http_client`. Let's track it there.
