### ISSUE TITLE
Terrible documentation and error messages

### ISSUE THREAD

**Issue by Instrumedley** [sendgrid/sendgrid-python#939]
You guys seriously need to update/write better documentation as well as your error messages. 

I decided to give it a try with integrating the service with my python application.

First, while using the integration guide for python, things don't work at the very basic steps.

> Send your first email
The following is the minimum needed code to send an email

No it's not, I get error: HTTP Error 401: Unauthorized

Why? No info or description of what should I do

Then I decided to go here https://sendgrid.com/docs/for-developers/sending-email/curl-examples/#hello-world and try a Hello World with Curl. What can go wrong with a simple hello world right?

I get error:

```
Rafaels-MBP:~ rafaelsantos$ curl --request POST \
>   --url https://api.sendgrid.com/v3/mail/send \
>   --header 'Authorization: Bearer REDACTED' \
>   --header 'Content-Type: application/json' \
>   --data '{"personalizations": [{"to": [{"email": "recipient@example.com"}]}],"from": {"email": "sendeexampexample@example.com"},"subject": "Hello, World!","content": [{"type": "text/plain", "value": "Heya!"}]}'
{"errors":[{"message":"The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requiremRafaelRafaelRafaelRafaels-MRafaels-MBP:~ rRafaels-MBP:Rafaels-MBP:~ rRafaels-MBP:~ rafaRafaels-MRafRafaelRafaelRafRafRafRafRafRafaelRafaelRafRafaelRafRafRafRafRafRafRafRafRafRafRafRafRafRafaelRafaelRafaelRafaelRafRafaelRafaels-MBP:Rafaels-MBP:RafRafaelRafRafRafRafRafRafRafRafRafRafaelRafael
```

well from the message error I see that I can deduce that I need to add the from_address in my integration settings. But then again, why not state that before the user actually tries? And also replace the values on these emails by something like [your_from_email] since I can't really have "sendeexampexample@example.com" in my settings since I need also to verify the sender email in my settings! What a mess.

Then ok, I do all that hassle, and now I get this beautiful error message

```
{"errors":[{"message":"Bad Request","field":null,"help":null}]}Rafaels-MBP:~ rafaelsantos$ curl --request POST \
>   --url https://api.sendgrid.com/v3/mail/send \
>   --header 'Authorization: Bearer REDACTED' \
>   --header 'Content-Type: application/json' \
>   --data '{"personalizations": [{"to": [{"email": "recipient@example.com"}]}],"from": {"email": “theemailIregistered@domain.com”},”subject": "Hello, World!”,content": [{"type": "text/plain", "value": "Heya!"}]}'
```

here: `{"errors":[{"message":"Bad Request","field":null,"help":null}]}`

This is enough for me to know the service is gonna be bad

**Comment by eshanholtz** [comment]
Hi @Instrumedley 
I'm sorry to hear you're having trouble getting started. I noticed you're using cURL to send your requests. This GitHub page is intended to provide support for those using the `sendgrid-python` library, which provides some nicer interfaces to using SendGrid, as well as providing the ability to [read more specific error messaging](https://github.com/sendgrid/sendgrid-python/blob/main/TROUBLESHOOTING.md#error-messages) than what's returned with cURL. I recommend [referring to out quick start guide](https://github.com/sendgrid/sendgrid-python#quick-start) if you're interested in getting started with the `sendgrid-python` helper library. However, if you wish to interact with the SendGrid API using cURL, I recommend [reaching out to support](https://support.sendgrid.com/hc/en-us) for further help.
