### ISSUE TITLE
message.add_to no longer accepts tuples

### ISSUE THREAD

**Issue by reustle** [sendgrid/sendgrid-python#94]
The old `add_to` equivalent method would take a tuple like `(email, name)` when setting the recipient, but that doesn't seem to be the case now. It looks like I'll have to compile my own `name <email>` strings.

I see that the API has changed (a lot) since then, but I think this would still be something worth supporting. What are your thoughts?

Thanks!

**Comment by elbuo8** [comment]
@eddiezane what are your thoughts on this? I like @reustle suggestion. And it shouldn't break previous versions of the lib.

**Comment by eddiezane** [comment]
Should be good. Just more type checking in that method. :+1:

**Comment by elbuo8** [comment]
https://github.com/sendgrid/sendgrid-python/commit/d78be6aaf65568085f65ded84aa76f6b41521e65#diff-4f4ef55b97e3b72353032ef609a865d2R41 Added. Also fixed the bug on top.
