### ISSUE TITLE
Support for text/x-amp-html mime type

### ISSUE THREAD

**Issue by SergeNasr** [sendgrid/sendgrid-python#940]
### Issue Summary - Feature Request
I am trying to use the SendGrid python client to send AMP dynamic emails. AMP emails require the `text/x-amp-html` content type [as per SendGrid's doc](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure/?format=websites)
However the python library [does not support](https://github.com/sendgrid/sendgrid-python/blob/main/sendgrid/helpers/mail/mime_type.py) the `text/x-amp-html` mime type yet.

**Comment by thinkingserious** [comment]
Hello @SergeNasr,

Thank you for this request! This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

Note: the [mime-type ordering](https://github.com/sendgrid/sendgrid-python/blob/e5253a571c1537f51be3a9e16057187cb7386653/sendgrid/helpers/mail/mail.py#L728) will likely need to be considered.

With best regards,

Elmer

**Comment by SergeNasr** [comment]
@childish-sambino I think we would also need to add a `if amp_content` in https://github.com/sendgrid/sendgrid-python/blob/v6.1.0/sendgrid/helpers/mail/mail.py#L74 and also the mime-type ordering linked by @thinkingserious

**Comment by modernwarfareuplink** [comment]
@SergeNasr have added support for this [here](https://github.com/sendgrid/sendgrid-python/pull/945). Feel free to clone that branch and use if you are blocked on something and add your feedback. Thanks
