### ISSUE TITLE
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized 

### ISSUE THREAD

**Issue by Godwhitelight** [sendgrid/sendgrid-python#946]
Hello, i am trying to send mail's and that is not working well. i have this error

Traceback (most recent call last):
  File "D:/devoleper/PYTHON/Startup/main.py", line 79, in <module>
    Menu()
  File "D:/devoleper/PYTHON/Startup/main.py", line 32, in Menu
    WorngMan()
  File "D:/devoleper/PYTHON/Startup/main.py", line 76, in WorngMan
    response = sg1.send(message)
  File "D:\devoleper\PYTHON\startup\venv\lib\site-packages\sendgrid\base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
  File "D:\devoleper\PYTHON\startup\venv\lib\site-packages\python_http_client\client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "D:\devoleper\PYTHON\startup\venv\lib\site-packages\python_http_client\client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized

Process finished with exit code 1

my code.

    import os
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail

    message = Mail(
        from_email='jarvissystemgod@gmail.com',
        to_emails='bargigon@gmail.com',
        subject='Sending with Twilio SendGrid is Fun',
        html_content='<strong>and easy to do anywhere, even with Python</strong>')

    sg1 = SendGridAPIClient(os.environ.get('API HERE(i temp removed it for safety.)'))
    response = sg1.send(message)
    print(response.status_code, response.body, response.headers)

**Comment by modernwarfareuplink** [comment]
The problem probably is because 
- API key does not have access to send mail
- API key is not valid
You can generate a new API KEY and test it out.

**Comment by childish-sambino** [comment]
@modernwarfareuplink Thanks for the info.

@Godwhitelight Let us know if this helps.

**Comment by xiphos71** [comment]
Hello! I am having similar problems but didn't realize I could comment on other issues. I cut a new issue, #948, which has my particular details. If it looks like the same issue please feel free to merge with this one. My apologies!
