### ISSUE TITLE
set_headers method not working

### ISSUE THREAD

**Issue by heitortsergent** [sendgrid/sendgrid-python#95]
The set_headers method should accept a dictionary, like the following:

```
message.set_headers({'X-Sent-Using': 'SendGrid-API', 'X-Transport': 'web'});
```

But that only raises the following error:

```
sendgrid.exceptions.SendGridClientError: (400, '{"message": "error", "errors": ["JSON in headers could not be parsed"]}')
```

I couldn't find any code related to the headers parameters on the send method as well.

**Comment by elbuo8** [comment]
https://github.com/sendgrid/sendgrid-python/commit/1aa8a89708099f1e37e01baa24720dc1f070a2d4

Yay
