### ISSUE TITLE
IncompleteRead(0 bytes read, 76 more expected)

### ISSUE THREAD

**Issue by wasauce** [sendgrid/sendgrid-python#952]
### Issue Summary
IncompleteRead(0 bytes read, 76 more expected)

I have been running sendgrid for months as a part of our web service with no problems. We send email to new users, and when users take certain actions.

Today, while doing some testing, for the first half of the day -- everything is working fine, the emails are sending.
Then, suddenly, they stop working. We had not changed any of the email related code. Below you can see the issue we are seeing.

I have seen this once before and the issue was that our API key was no longer valid (we weren't sure why/how it became invalid). 

So, I have tested our API key using:

curl -X "GET" "https://api.sendgrid.com/v3/templates" -H "Authorization: Bearer <key here>" -H "Content-Type: application/json"

And I get back:
{"templates":[]}

Which indicates the key is good.

### Steps to Reproduce
Run the snippet below. Of course, you need my API key which I am not providing -- but consistently that fails.

### Code Snippet
```python
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, ReplyTo

from constants import SENDGRID_API_KEY

from_email = "bill@pods.jckhq.com"
to_email = "wferrell@sidekick.im"
subject = "test"
html_content = "content"


message = Mail(
    from_email=from_email,
    to_emails=to_email,
    subject=subject,
    html_content=html_content)


sg = SendGridAPIClient(api_key=SENDGRID_API_KEY)
response = sg.send(message)

```

### Exception/Log
```
  File "<stdin>", line 1, in <module>
  File "/Users/wferrell/.pyenv/versions/jckjck373/lib/python3.7/site-packages/sendgrid/base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
  File "/Users/wferrell/.pyenv/versions/jckjck373/lib/python3.7/site-packages/python_http_client/client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/Users/wferrell/.pyenv/versions/jckjck373/lib/python3.7/site-packages/python_http_client/client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
```

### Technical details:
* sendgrid-python version: 6.4.7
* python version: Python 3.7.3

**Comment by thinkingserious** [comment]
Hello @wasauce,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
