### ISSUE TITLE
app.sendgrid.com docs: supported python versions are outdated

### ISSUE THREAD

**Issue by jaredhanson11** [sendgrid/sendgrid-python#963]
### Issue Summary

Not entirely sure if this is the right place to report this, but anyways...

The documentation https://app.sendgrid.com/guide/integrate/langs/python (login required) states:

> Our library requires Python 2.6, 2.7, 3.4 or 3.5.

A red flag went off in my head because we're running 3.7 and I wanted to make sure it was supported. After visiting the README in this repo, I was relieved to find that the prereqs are really:

> Python version 2.7, 3.5, 3.6, 3.7, or 3.8

I would suggest keeping the documentation on SendGrid's website up to date with this repository to avoid this confusion for future customers.

### Steps to Reproduce
1. Visit https://app.sendgrid.com/guide/integrate/langs/python and observe python versions supported
2. Visit https://github.com/sendgrid/sendgrid-python/blob/main/README.md#prerequisites and observe python versions supported
3. Notice discrepancy between the two

**Comment by JenniferMah** [comment]
Hi @jaredhanson11,
Thanks for bringing this to our attention. The information in our README is correct we do support Python 3.7. Can you file an issue [here](https://github.com/sendgrid/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) so the appropriate team can make these changes?
