### ISSUE TITLE
Python 3.9 support?

### ISSUE THREAD

**Issue by OlafvdSpek** [sendgrid/sendgrid-python#965]
The perquisites don't show support for Python 3.9.. 
Maybe it's simpler to list 3.5+?

**Comment by thinkingserious** [comment]
Hello @OlafvdSpek,

We have not tested against 3.9 yet. I have [created a branch](https://travis-ci.com/github/sendgrid/sendgrid-python/builds/212228707) to start exploration.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by XiaoYiyichonga** [comment]
Hello Team,
Now, the sendgrid api cannot be used with python 3.9.
If it could be improved which can be used to applied to python 3.9 it would add more benifits.
Could you kindly consider to add it?
Best Regards
Face of Sendgrids

**Comment by arman-mahtabfar** [comment]
Any update on this? I am trying to use sendgrid with python 3.9.5.

**Comment by shwetha-manvinkurke** [comment]
@XiaoYiyichonga @arman-mahtabfar what issues are you running into with python 3.9.x?
