### ISSUE TITLE
Sendgrid Email Validation

### ISSUE THREAD

**Issue by tmartin2089** [sendgrid/sendgrid-python#969]
### Issue Summary
I apologize if I'm missing something obvious but I don't see any documentation on how to validate email addresses via this library, or even any reference to the email validation API.  Is this not an included feature in this library?

**Comment by shwetha-manvinkurke** [comment]
Hi @tmartin2089, 

We do not have a handcrafted helper for [this](https://sendgrid.api-docs.io/v3.0/email-address-validation/validate-an-email) endpoint; however, you can utilize [this](https://github.com/sendgrid/sendgrid-python/blob/main/USAGE.md#post-alerts) example to craft your call:

```
data = {
  "email": "john.doe@gmial.com",
  "source": "signup"
}
sg.client.validations.email.post(request_body=data)
```

Thanks,
Shwetha
