### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SendGridClient'

### ISSUE THREAD

**Issue by TaqiOfficial** [sendgrid/sendgrid-python#97]
*I am trying to send emails via sendgrid in django. But each time it says;*

```sg = sendgrid.SendGridClient(settings.SENDGRID_USERNAME, settings.SENDGRID_PASSWORD, raise_errors=True)```

```AttributeError: 'module' object has no attribute 'SendGridClient'```

However in requirements.txt file sendgrid ok and also import sendgrid.
and in setttings file it is properly configured.

**Comment by elbuo8** [comment]
Are you using virtualenv? Make sure you install it on your local environment. Also, you can take a look at this lib:
https://github.com/elbuo8/sendgrid-django

**Comment by changhaz** [comment]
make sure you do not have any other file named as "sendgrid"

**Comment by eddiezane** [comment]
Could very well be it @changhaz. Thanks for the insight!

**Comment by TaqiOfficial** [comment]
@elbuo8  i was using it without `virtualenv`, So i setup `venv` and problem is solved. thanks
