### ISSUE TITLE
ImportError                               Traceback (most recent call last) <ipython-input-16-88328595fb8a> in <module>()       6 import matplotlib.pylab as plt       7  ----> 8 from sandpile import ASM       9 from plot_avalanches import plot_avalanches, plot_pile      10   ImportError: cannot import name 'ASM'

### ISSUE THREAD

**Issue by Abhinna-Sundar** [sendgrid/sendgrid-python#975]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-python version: 
* python version:

**Comment by shwetha-manvinkurke** [comment]
@Abhinna-Sundar From the error, it doesn't look like you are using sendgrid at all? Also, in the future, please enter issue details in the body of the issue.
