### ISSUE TITLE
Pull stats data via API

### ISSUE THREAD

**Issue by junyanyao** [sendgrid/sendgrid-python#982]
Hi Team,

Do you know how to pull the statistics data like open, click (user behavior data) via API? I saw these readership data in the platform. Not sure how could we generate it periodically via API? 

Thanks

**Comment by thinkingserious** [comment]
Hello @junyanyao,

I believe [this endpoint](https://github.com/sendgrid/sendgrid-python/blob/main/USAGE.md#stats) is what you would need.

With best regards,

Elmer

**Comment by junyanyao** [comment]
Thank you Elmer, this is exactly what I need!
