### ISSUE TITLE
Plans to Async/Non-block

### ISSUE THREAD

**Issue by alexandre** [sendgrid/sendgrid-python#99]
Do you have plans to use something like asyncio?

**Comment by elbuo8** [comment]
Not at the moment. 

@eddiezane @kunal732 consider this for future versions.

**Comment by marioidival** [comment]
And now? =)

**Comment by thinkingserious** [comment]
@marioidival not on our current roadmap. However, we will be adding a helpers folder where extensions to the library can be added. Do you think that would work for your needs?

**Comment by 1024kilobyte** [comment]
Any update regarding this issue?

**Comment by thinkingserious** [comment]
Hi @1024kilobyte,

Please follow [this thread](https://github.com/sendgrid/sendgrid-python/issues/296) for updates. Thanks!

With Best Regards,

Elmer
