### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'mime_type'

### ISSUE THREAD

**Issue by Kitwradr** [sendgrid/sendgrid-python#991]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

I am using the sendgrid email API to send email. Although the code **works perfectly fine on windows** it gives this error when I run the same code in **Linux** 

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```python
def send_email(text,emailid):
    message = Mail(
        from_email=from_email,
        to_emails=emailid,
        subject='Subject',
        html_content=text)
    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e.message)



def notifier():
    ...
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
    for var in list_:
        x = requests.get(url,headers)
        data = json.loads(x.text)
        ...
        for center in data["centers"]:
            ...
            for session in center["sessions"]:
                ...
            if condition:
                print(center)
                string_to_email = string_to_email + "<br>" + center["name"]+"<br>"+str(center["pincode"])+"<br>"+center["block_name"]+"<br>fee type:"+center["fee_type"]+"<br>min age:"+str(min_age)+"<br>avail slots"+str(slotsavail)+"<br>-----------------<br>"
    print(string_to_email)
    string_to_email = "<strong>" + string_to_email + "</strong>"
    response = send_email(string_to_email)

```

### Exception/Log
```
File "script_test.py", line 20, in send_email
    html_content=email_body)
  File "/home/azureuser/.local/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 80, in __init__
    self.add_content(html_content, MimeType.html)
  File "/home/azureuser/.local/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 734, in add_content
    if content.mime_type == MimeType.text:
AttributeError: 'unicode' object has no attribute 'mime_type'
```

### Technical details:
* sendgrid-python version: 6.7.0
* python version: 3.7.6

**Comment by shwetha-manvinkurke** [comment]
@Kitwradr Can you share your code snippet?

**Comment by Kitwradr** [comment]
@shwetha-manvinkurke here it is
`def send_email(text,emailid):
    message = Mail(
        from_email=from_email,
        to_emails=emailid,
        subject='Subject',
        html_content=text)
    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(e.message)



def notifier(prev_email):
    ...
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36'}
    for var in list_:
        x = requests.get(url,headers)
        data = json.loads(x.text)
        ...
        for center in data["centers"]:
            ...
            for session in center["sessions"]:
                ...
            if condition:
                print(center)
                string_to_email = string_to_email + "<br>" + center["name"]+"<br>"+str(center["pincode"])+"<br>"+center["block_name"]+"<br>fee type:"+center["fee_type"]+"<br>min age:"+str(min_age)+"<br>avail slots"+str(slotsavail)+"<br>-----------------<br>"
    print(string_to_email)
    string_to_email = "<strong>" + string_to_email + "</strong>"
    response = send_email(string_to_email)`

**Comment by thinkingserious** [comment]
Hello @Kitwradr,

What version of this helper library are you using? The [latest version](https://github.com/sendgrid/sendgrid-python/blob/16eb0c33c97f8ca293fbc0d8965afd87c0d2f99a/sendgrid/helpers/mail/content.py#L39) does have the property.

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Perhaps the version you are using on Azure is different? I noticed that in your original logs, the version of python is 2.7. Can you please take a look at `/home/azureuser/.local/lib/python2.7/site-packages/sendgrid/version.py` and verify the library version? Thank you!

**Comment by Kitwradr** [comment]
The error was due to the final text parameter not being of type `string`. Only on Linux for some reason it was getting converted to unicode. Fixed it by casting the string email using `str()`
