### ISSUE TITLE
Access the Email Activity API for a specific message using the python library

### ISSUE THREAD

**Issue by Skiem** [sendgrid/sendgrid-python#992]
### How to access the Email Activity API for a specific message 
Hi, a simple question which I couldn't find in the documentation.
How can I access the Email Activity API for a specific message using the python library?
To be precise, I want to make this type of API call: https://sendgrid.api-docs.io/v3.0/email-activity/filter-messages-by-message-id
But with the python library, which python function do I need to use for that?
Thanks in advance :)

### Technical details:
* sendgrid-python version: 6.7.0
* python version: 3.9.0

**Comment by shwetha-manvinkurke** [comment]
Hi @Skiem, you would need to pass in the msg_id as a query parameter something like [this](https://github.com/sendgrid/sendgrid-python/blob/main/USAGE.md#get-access_settingsactivity). Let us know if that helps.
